import { NextRequest, NextResponse } from 'next/server'
import * as Sentry from '@sentry/nextjs'
import { requireCsrfToken } from '@/lib/csrf'
import { requireBodySizeLimit, getSizeLimitForContentType } from '@/lib/requestSizeLimit'
import { createCheckoutSession, aedToFils, getCheckoutSession } from '@/lib/stripe'
import { addOrder, OrderData, OrderItemData } from '@/lib/orderStorageDb'
import { enhanceOrderItemWithDefaultSize } from '@/lib/orderSizeDefaults'
import { debugLog, errorLog } from '@/lib/logger'
import { Product } from '@/types/index'
import { generateUniqueOrderNumber } from '@/lib/orderNumber'
import { getPreferredEmail } from '@/lib/emailHelpers'
import { findUserByEmail } from '@/lib/userStorageDb'
import { calculateMobileShipping, calculateVatIncluded } from '@/lib/mobileCheckoutConfig'
import { prisma } from '@/lib/prisma'
import { getProductById } from '@/lib/productsDb'
import { getCartLinePricing } from '@/lib/cartPricing'
import { CartItem } from '@/types'
import {
  getValidatedBundleDiscountPercent,
  isAllowedFreeGiftProduct,
  isSubmittedBundleLine,
  allowedFreeGiftUnits,
  freeGiftKind,
} from '@/lib/checkoutPricingGuards'
import { rateLimitSimple, getClientIdentifierFromNextRequest } from '@/lib/rateLimitSimple'

// Each call hits Stripe (billable) + writes an order + N product lookups.
const checkoutSessionLimiter = rateLimitSimple({ windowMs: 60 * 1000, max: 8 })

interface CheckoutItem {
  product: Product
  quantity: number
  selectedColor?: string
  selectedSize?: string
  fromBundle?: boolean
  bundleDiscountPercent?: number
}

interface StripeProductData {
  name: string
  description: string
  metadata?: {
    product_id: string
    color: string
    size: string
  }
  images?: string[]
}

interface ServerPricedCheckoutItem {
  product: Product
  quantity: number
  selectedColor?: string
  selectedSize?: string
  unitPrice: number
  lineTotal: number
  discountAmount: number
  discountPercentage: number
  discountType: string
  fromBundle?: boolean
  bundleDiscountPercent?: number
}

function isSubmittedFreeGift(item: CheckoutItem): boolean {
  const submittedName = String(item.product?.name || '').toLowerCase()
  const submittedCategory = String(item.product?.category || '').toLowerCase()
  const submittedPrice = Number(item.product?.price)

  return (
    submittedPrice === 0 ||
    submittedName.includes('(free)') ||
    submittedCategory === 'free-gift' ||
    String(item.selectedSize || '').trim() === '__PROMO__'
  )
}

function getSubmittedProductId(item: CheckoutItem): string {
  return String(item.product?.id || item.product?.productNumber || '').trim()
}

export async function POST(request: NextRequest) {
  // Per-IP rate limit (before any expensive work)
  const rl = await checkoutSessionLimiter(`cs:${getClientIdentifierFromNextRequest(request)}`)
  if (!rl.success) {
    return NextResponse.json(
      { error: 'Too many payment attempts. Please wait a moment and try again.' },
      { status: 429 }
    )
  }

  // CSRF protection
  const csrfCheck = await requireCsrfToken(request)
  if (!csrfCheck.valid) {
    return csrfCheck.response!
  }

  // Request body size limit check
  const sizeLimit = getSizeLimitForContentType(request)
  const sizeCheck = requireBodySizeLimit(request, sizeLimit)
  if (!sizeCheck.valid) {
    return sizeCheck.response!
  }

  try {
    const { 
      items, 
      customerEmail, 
      customerName, 
      customerPhone, 
      customerEmirate, 
      customerAddress,
      locale 
    } = await request.json()

    // Validate required fields
    if (!items || !Array.isArray(items) || items.length === 0) {
      return NextResponse.json(
        { error: 'Cart items are required' },
        { status: 400 }
      )
    }

    if (!customerEmail || !customerName || !customerPhone || !customerEmirate || !customerAddress) {
      return NextResponse.json(
        { error: 'Customer information is required' },
        { status: 400 }
      )
    }

    debugLog('🔄 Creating Stripe checkout session:', {
      customerEmail,
      customerName,
      itemCount: items.length,
      emirate: customerEmirate
    })

    // Fetch user to check for contactEmail (for Apple Private Relay users)
    const user = await findUserByEmail(customerEmail)
    const emailToUse = user ? getPreferredEmail(user) : customerEmail

    debugLog('📧 Email routing for Stripe:', {
      customerEmail,
      hasUser: !!user,
      hasContactEmail: !!(user?.contactEmail),
      emailToUse,
      isAppleRelay: customerEmail.includes('@privaterelay.appleid.com')
    })

    // Calculate totals from server-recomputed prices. Client-submitted item prices
    // are ignored except for explicit free-gift markers generated by checkout.
    const userDiscountPct = Number(user?.discountPercentage || 0)
    let subtotal = 0
    let discountAmount = 0
    let bundleDiscountAmount = 0
    let bundleDiscountPercent: number | null = null
    const pricedItems: ServerPricedCheckoutItem[] = []
    const productRecords: Array<{ item: CheckoutItem; product: Product }> = []
    
    for (const item of items as CheckoutItem[]) {
      const productId = getSubmittedProductId(item)
      if (!productId) {
        return NextResponse.json(
          { error: 'Invalid cart item' },
          { status: 400 }
        )
      }

      const product = await getProductById(productId)
      if (!product) {
        return NextResponse.json(
          { error: `Product not found: ${item.product?.name || productId}` },
          { status: 400 }
        )
      }

      productRecords.push({ item, product })
    }

    const bundleLineCount = productRecords.filter(({ item, product }) =>
      isSubmittedBundleLine(item.bundleDiscountPercent, product)
    ).length

    // Free-gift candidates, validated against the spend threshold after the
    // paid subtotal is known (below).
    const freeGiftCandidates: Array<{ item: CheckoutItem; product: Product; quantity: number; selectedColor: string; selectedSize: string }> = []

    for (const { item, product } of productRecords) {
      const quantity = Number(item.quantity) || 0
      if (quantity <= 0) {
        return NextResponse.json(
          { error: `Invalid quantity for ${product.name}` },
          { status: 400 }
        )
      }

      const selectedSize = String(item.selectedSize || '').trim()
      const selectedColor = String(item.selectedColor || '').trim()
      const isFreeGift = isSubmittedFreeGift(item) && isAllowedFreeGiftProduct(product)
      const bundlePct = getValidatedBundleDiscountPercent(item.bundleDiscountPercent, product, bundleLineCount)

      if (isFreeGift) {
        freeGiftCandidates.push({ item, product, quantity, selectedColor, selectedSize })
        continue
      }

      // Out-of-stock enforcement (paid items only).
      if (!product.inStock) {
        return NextResponse.json(
          { error: `${product.name} is currently out of stock` },
          { status: 400 }
        )
      }

      const cartItem: CartItem = {
        product,
        quantity,
        ...(selectedColor ? { selectedColor } : {}),
        ...(selectedSize ? { selectedSize } : {}),
        ...(bundlePct ? { fromBundle: true, bundleDiscountPercent: bundlePct } : {}),
      }
      const pricing = getCartLinePricing(cartItem, user)
      subtotal += pricing.lineTotal

      if (pricing.discountType === 'bundle') {
        bundleDiscountAmount += pricing.discountAmount
        if (pricing.discountPercentage > 0) bundleDiscountPercent = pricing.discountPercentage
      } else if (pricing.discountType === 'user' || pricing.discountType === 'black_friday') {
        discountAmount += pricing.discountAmount
      }

      pricedItems.push({
        product,
        quantity,
        ...(selectedColor ? { selectedColor } : {}),
        ...(selectedSize ? { selectedSize } : {}),
        unitPrice: pricing.unitPrice,
        lineTotal: pricing.lineTotal,
        discountAmount: pricing.discountAmount,
        discountPercentage: pricing.discountPercentage,
        discountType: pricing.discountType,
        ...(pricing.discountType === 'bundle' ? { fromBundle: true } : {}),
        ...(pricing.discountType === 'bundle' ? { bundleDiscountPercent: pricing.discountPercentage } : {}),
      })
    }
    
    // Round to 2 decimal places
    subtotal = Math.round(subtotal * 100) / 100
    discountAmount = Math.round(discountAmount * 100) / 100
    bundleDiscountAmount = Math.round(bundleDiscountAmount * 100) / 100

    // Admit only the free masks the spend threshold allows.
    {
      const allowance = allowedFreeGiftUnits(subtotal)
      let collagenLeft = allowance.collagen
      let seaAlgaeLeft = allowance.seaAlgae
      for (const g of freeGiftCandidates) {
        const kind = freeGiftKind(g.product)
        let grant = 0
        if (kind === 'collagen') { grant = Math.min(g.quantity, collagenLeft); collagenLeft -= grant }
        else if (kind === 'sea_algae') { grant = Math.min(g.quantity, seaAlgaeLeft); seaAlgaeLeft -= grant }
        if (grant <= 0) continue
        pricedItems.push({
          product: {
            ...g.product,
            name: String(g.item.product?.name || `${g.product.name} (FREE)`),
          },
          quantity: grant,
          ...(g.selectedColor ? { selectedColor: g.selectedColor } : {}),
          ...(g.selectedSize ? { selectedSize: g.selectedSize } : {}),
          unitPrice: 0,
          lineTotal: 0,
          discountAmount: 0,
          discountPercentage: 0,
          discountType: 'free_gift',
        })
      }
    }

    // Use shared mobile checkout config for consistency
    const shipping = calculateMobileShipping(subtotal, customerEmirate)
    
    const total = subtotal + shipping
    const vat = calculateVatIncluded(total)

    // Idempotency check: Look for recent pending CARD orders from same customer with same total
    // This prevents duplicate orders from double-clicks or network retries
    const recentDuplicateCheck = await prisma.order.findFirst({
      where: {
        customerEmail: customerEmail.trim().toLowerCase(),
        paymentMethod: 'stripe',
        paymentStatus: 'pending',
        total: total,
        createdAt: {
          gte: new Date(Date.now() - 5 * 60 * 1000) // Within last 5 minutes
        }
      },
      orderBy: { createdAt: 'desc' }
    })

    if (recentDuplicateCheck) {
      debugLog('⚠️ Duplicate order detected, returning existing session:', {
        existingOrderNumber: recentDuplicateCheck.orderNumber,
        customerEmail,
        total
      })
      
      // Return existing session info if available
      if (recentDuplicateCheck.stripeSessionId) {
        try {
          // Retrieve the existing session from Stripe to get the URL
          const existingSession = await getCheckoutSession(recentDuplicateCheck.stripeSessionId)
          
          // Check if the session is still active (not expired)
          if (existingSession.status === 'open' && existingSession.url) {
            debugLog('✅ Returning existing active session URL:', {
              sessionId: existingSession.id,
              url: existingSession.url
            })
            return NextResponse.json({ 
              sessionId: recentDuplicateCheck.stripeSessionId,
              url: existingSession.url,
              orderId: recentDuplicateCheck.orderNumber,
              message: 'Using existing checkout session',
              isDuplicate: true
            })
          }
          
          // Session is expired or completed, proceed to create a new one
          debugLog('⚠️ Existing session is no longer active, creating new session:', {
            sessionStatus: existingSession.status
          })
        } catch (sessionError) {
          // Failed to retrieve session (might be deleted), proceed to create new
          debugLog('⚠️ Could not retrieve existing session, creating new one:', sessionError)
        }
      }
    }

    // Generate canonical order number (Card + Website)
    const orderId = await generateUniqueOrderNumber({ channel: 'W', payment: 'CARD' })

    // Create order items for database
    const orderItems: OrderItemData[] = pricedItems.map((item) => {
      const enhanced = enhanceOrderItemWithDefaultSize({
        productName: item.product.name,
        size: item.selectedSize || null,
        color: item.selectedColor || null
      })
      
      return {
        productId: item.product.id,
        productName: item.product.name,
        price: item.unitPrice,
        quantity: item.quantity,
        image: item.product.image,
        color: enhanced.color || '',
        size: enhanced.size || '',
        ...(item.fromBundle && item.bundleDiscountPercent ? { bundleDiscount: item.bundleDiscountPercent } : {})
      }
    })

    // Create Stripe line items
    const lineItems = pricedItems.map((item) => {
      // Ensure image URL is absolute and valid
      let imageUrl: string | undefined
      try {
        if (item.product.image) {
          if (item.product.image.startsWith('http')) {
            // Already absolute URL
            new URL(item.product.image) // Validate URL
            imageUrl = item.product.image
          } else {
            // Make relative URL absolute
            const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'
            const fullUrl = `${baseUrl}${item.product.image.startsWith('/') ? '' : '/'}${item.product.image}`
            new URL(fullUrl) // Validate URL
            imageUrl = fullUrl
          }
        }
      } catch {
        // If image URL is invalid, don't include it (Stripe will show default)
        debugLog('⚠️ Invalid image URL for product, skipping:', item.product.name, item.product.image)
        imageUrl = undefined
      }
      
      const productData: StripeProductData = {
        name: item.product.name,
        description: item.product.description.substring(0, 300), // Stripe has limits
        metadata: {
          product_id: item.product.id,
          color: item.selectedColor || '',
          size: item.selectedSize || ''
        }
      }
      
      // Only add images if we have a valid URL
      if (imageUrl) {
        productData.images = [imageUrl]
      }
      
      return {
        price_data: {
          currency: 'aed',
          product_data: productData,
          unit_amount: aedToFils(item.unitPrice), // Convert AED to fils
        },
        quantity: item.quantity,
      }
    })

    // Add shipping as a line item if applicable
    if (shipping > 0) {
      lineItems.push({
        price_data: {
          currency: 'aed',
          product_data: {
            name: `Shipping to ${customerEmirate}`,
            description: 'Standard delivery',
          },
          unit_amount: aedToFils(shipping),
        },
        quantity: 1,
      })
    }

    // Create Stripe checkout session (use preferred email)
    const session = await createCheckoutSession({
      lineItems,
      customerEmail: emailToUse, // Use preferred email for Stripe
      customerName,
      customerPhone,
      shippingAddress: {
        line1: customerAddress,
        city: customerEmirate,
        country: 'AE', // UAE
      },
      orderNumber: orderId,
      locale: locale || 'en'
    })

    // Create order in database with PENDING status and Stripe session ID
    const order: OrderData = {
      orderNumber: orderId,
      customerEmail,
      customerName,
      customerPhone,
      customerEmirate,
      customerAddress,
      items: orderItems,
      subtotal,
      discountPercentage: discountAmount > 0 ? userDiscountPct : 0,
      discountAmount,
      ...(bundleDiscountPercent ? { bundleDiscountPercentage: bundleDiscountPercent } : {}),
      bundleDiscountAmount,
      shipping,
      vat,
      total,
      status: 'PENDING',
      paymentMethod: 'stripe',
      paymentStatus: 'pending',
      stripeSessionId: session.id,
      locale: locale || 'en'
    }

    // Store the order
    await addOrder(order)

    debugLog('✅ Order created with Stripe session:', {
      orderId,
      sessionId: session.id,
      total,
      customerEmail
    })

    // Return session details for frontend
    return NextResponse.json({ 
      sessionId: session.id,
      url: session.url,
      orderId: orderId,
      message: 'Checkout session created successfully'
    })

  } catch (error) {
    // Type guard for Stripe-like errors with additional properties
    interface StripeErrorLike extends Error {
      code?: string
      statusCode?: number
      requestId?: string
      param?: string
      type?: string
    }
    
    const isStripeError = (err: unknown): err is StripeErrorLike => {
      return err instanceof Error && ('type' in err || 'code' in err)
    }
    
    // Extract error details safely
    const stripeErr = isStripeError(error) ? error : null
    Sentry.captureException(error, { tags: { area: 'checkout', op: 'create-checkout-session' } })
    
    errorLog('❌ Error creating Stripe checkout session:', {
      message: error instanceof Error ? error.message : 'Unknown error',
      stack: error instanceof Error ? error.stack : undefined,
      type: error instanceof Error ? error.constructor.name : typeof error,
      code: stripeErr?.code,
      statusCode: stripeErr?.statusCode,
      requestId: stripeErr?.requestId,
      param: stripeErr?.param,
      stripeError: stripeErr?.type || (error instanceof Error ? error.name : 'Unknown'),
      fullError: error
    })
    
    // Return user-friendly error message with more details for debugging
    if (error instanceof Error && error.message.includes('Invalid API key')) {
      return NextResponse.json(
        { error: 'Payment service configuration error. Please try again later.' },
        { status: 503 }
      )
    }
    
    // Provide more detailed error in development
    const isDev = process.env.NODE_ENV === 'development'
    return NextResponse.json(
      { 
        error: 'Failed to create payment session. Please try again.',
        details: isDev ? {
          message: error instanceof Error ? error.message : 'Unknown error',
          type: error instanceof Error ? error.constructor.name : typeof error,
          code: stripeErr?.code,
          param: stripeErr?.param
        } : undefined
      },
      { status: 500 }
    )
  }
}