import fs from 'fs'
import path from 'path'

/**
 * Fetch products from API and translate to Russian
 * This script fetches products from the running API and generates Russian translations
 */

interface Product {
  id: string
  productNumber?: string | null
  name: string
  description: string
  productDetails?: string | null
  keyFeatures?: string | null
  benefits?: string | null
  ingredients?: string | null
  howToUse?: string | null
  directions?: string | null
}

interface ProductTranslation {
  description?: string
  productDetails?: string
  keyFeatures?: string | null
  benefits?: string
  ingredients?: string | null
  howToUse?: string
  directions?: string
}

// Translation function - translates English to Russian
function translateToRussian(text: string): string {
  // This is a placeholder - in production you'd use a translation API
  // For now, return a note that manual translation is needed
  // In production, integrate with Google Translate API, DeepL, etc.
  return `[TRANSLATE: ${text}]`
}

// Translate JSON content
function translateJSONContent(jsonStr: string | null): string | null {
  if (!jsonStr) return null
  
  try {
    const parsed = JSON.parse(jsonStr)
    
    if (Array.isArray(parsed)) {
      const translated = parsed.map((item: any) => {
        if (typeof item === 'string') {
          return translateToRussian(item)
        } else if (typeof item === 'object' && item !== null) {
          const translatedObj: Record<string, any> = {}
          for (const [key, value] of Object.entries(item)) {
            if (typeof value === 'string') {
              translatedObj[key] = translateToRussian(value)
            } else {
              translatedObj[key] = value
            }
          }
          return translatedObj
        }
        return item
      })
      return JSON.stringify(translated, null, 2)
    } else if (typeof parsed === 'object' && parsed !== null) {
      const translated: Record<string, any> = {}
      for (const [key, value] of Object.entries(parsed)) {
        if (typeof value === 'string') {
          translated[key] = translateToRussian(value)
        } else {
          translated[key] = value
        }
      }
      return JSON.stringify(translated, null, 2)
    }
    
    return jsonStr
  } catch {
    console.error('Error parsing JSON:', e)
    return jsonStr
  }
}

async function fetchProductsFromAPI(): Promise<Product[]> {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'
  
  try {
    const response = await fetch(`${baseUrl}/api/products`)
    if (!response.ok) {
      throw new Error(`API returned ${response.status}`)
    }
    const products = await response.json()
    return products
  } catch {
    console.error('Error fetching products from API:', error)
    throw error
  }
}

async function translateProduct(product: Product): Promise<ProductTranslation> {
  const translation: ProductTranslation = {}
  
  if (product.description) {
    translation.description = translateToRussian(product.description)
  }
  
  if (product.productDetails) {
    const translated = translateJSONContent(product.productDetails)
    if (translated) {
      translation.productDetails = translated
    }
  }
  
  if (product.keyFeatures) {
    translation.keyFeatures = translateJSONContent(product.keyFeatures)
  }
  
  if (product.benefits) {
    const translated = translateJSONContent(product.benefits)
    if (translated) {
      translation.benefits = translated
    }
  }
  
  if (product.ingredients) {
    translation.ingredients = translateJSONContent(product.ingredients)
  }
  
  if (product.howToUse) {
    const translated = translateJSONContent(product.howToUse)
    if (translated) {
      translation.howToUse = translated
    }
  }
  
  if (product.directions) {
    translation.directions = translateToRussian(product.directions)
  }
  
  return translation
}

async function main() {
  console.log('Fetching products from API...')
  
  try {
    const products = await fetchProductsFromAPI()
    console.log(`Found ${products.length} products`)
    
    const translations: Record<string, ProductTranslation> = {}
    
    for (const product of products) {
      const productId = product.productNumber || product.id
      console.log(`Processing product ${productId}: ${product.name}`)
      
      try {
        translations[productId] = await translateProduct(product)
      } catch {
        console.error(`Error translating product ${productId}:`, error)
      }
    }
    
    // Generate TypeScript file
    const fileContent = `/**
 * Russian translations for products
 * Auto-generated by fetch-and-translate-products.ts
 * 
 * NOTE: This file contains placeholder translations marked with [TRANSLATE: ...]
 * Replace these with actual Russian translations
 */

export interface ProductTranslation {
  description?: string
  productDetails?: string
  keyFeatures?: string | null
  benefits?: string
  ingredients?: string | null
  howToUse?: string
  directions?: string
}

export const productTranslationsRu: Record<string, ProductTranslation> = ${JSON.stringify(translations, null, 2)}

/**
 * Get Russian translation for a product field
 */
export function getProductTranslationRu(
  productId: string,
  field: keyof ProductTranslation
): string | null {
  const translation = productTranslationsRu[productId]
  return translation?.[field] || null
}

/**
 * Get all Russian translations for a product
 */
export function getProductTranslationsRu(productId: string): ProductTranslation | null {
  return productTranslationsRu[productId] || null
}
`
    
    const filePath = path.join(process.cwd(), 'data', 'productTranslationsRu.ts')
    fs.writeFileSync(filePath, fileContent, 'utf-8')
    
    console.log(`\n✓ Generated ${filePath}`)
    console.log(`✓ Processed ${Object.keys(translations).length} products`)
    console.log('\n⚠️  NOTE: Translations are placeholders. Replace [TRANSLATE: ...] with actual Russian translations.')
    
  } catch {
    console.error('Error:', error)
    process.exit(1)
  }
}

main()

