/**
 * Which copy module speaks for which product.
 *
 * The bespoke product pages hold the catalogue's best writing - the claims
 * checked against the Intertek dossier, the ingredient reconciliations, the
 * clinical figures - and it existed only inside React components, so the mobile
 * app showed a far thinner product than the website did.
 *
 * Rather than copy that text into the database and then have to keep two
 * versions honest, the mobile API imports the same modules the pages render
 * from. One source, no sync.
 *
 * Generated by scripts/generate-bespoke-copy-registry.js. Regenerate it when a
 * product gains a bespoke page; do not hand-edit.
 */

import { getAfsCopy } from '@/components/product/afs/afsCopy'
import { getAntiWrinkleCopy } from '@/components/product/antiwrinkle/antiWrinkleCopy'
import { getAntiWrinkleCreamCopy } from '@/components/product/antiwrinklecream/antiWrinkleCreamCopy'
import { getBbCushionCopy } from '@/components/product/bbcushion/bbCushionCopy'
import { pickBeautyBoxLocale } from '@/components/product/beautybox/beautyBoxCopy'
import { BEAUTY_BOXES } from '@/components/product/beautybox/beautyBoxes'
import { getBioFermentCopy } from '@/components/product/bioferment/bioFermentCopy'
import { getBioMesoCopy } from '@/components/product/biomeso/biomesoCopy'
import { getBioMesoExpertCopy } from '@/components/product/biomeso/biomesoExpertCopy'
import { getBlemishBalmCopy } from '@/components/product/blemishbalm/blemishBalmCopy'
import { getBoosterCopy } from '@/components/product/booster/boosterCopy'
import { getCeraCopy } from '@/components/product/cerabarrier/cerabarrierCopy'
import { getCollagenMaskCopy } from '@/components/product/collagenmask/collagenMaskCopy'
import { getEpiCopy } from '@/components/product/epi/epiCopy'
import { getEyeCreamCopy } from '@/components/product/eyecream/eyecreamCopy'
import { getEyeKitCopy } from '@/components/product/eyekit/eyekitCopy'
import { getEyePatchCopy } from '@/components/product/eyepatch/eyepatchCopy'
import { getEyeSerumCopy } from '@/components/product/eyeserum/eyeserumCopy'
import { getEzCo2Copy } from '@/components/product/ezco2/ezco2Copy'
import { getGenoLedCopy } from '@/components/product/genoled/genoLedCopy'
import { getHairStampCopy } from '@/components/product/hairstamp/hairstampCopy'
import { getHairGenBoosterCopy } from '@/components/product/hr3/hairGenBoosterCopy'
import { getHairGentronCopy } from '@/components/product/hr3/hairGentronCopy'
import { getHairSolutionCopy } from '@/components/product/hr3/hairSolutionCopy'
import { getHairTonicCopy } from '@/components/product/hr3/hairTonicCopy'
import { getMediShampooCopy } from '@/components/product/hr3/mediShampooCopy'
import { getMesopeciaKitCopy } from '@/components/product/hr3/mesopeciaKitCopy'
import { getScalpPeelingCopy } from '@/components/product/hr3/scalpPeelingCopy'
import { getHsserumCopy } from '@/components/product/hsserum/hsserumCopy'
import { getHydroCoolCopy } from '@/components/product/hydrocool/hydroCoolCopy'
import { getHydroSoothingCopy } from '@/components/product/hydrosoothing/hydroSoothingCopy'
import { getMhcreamCopy } from '@/components/product/mhcream/mhcreamCopy'
import { getMistCopy } from '@/components/product/mist/mistCopy'
import { getMultiSunCopy } from '@/components/product/multisun/multiSunCopy'
import { getMvcreamCopy } from '@/components/product/mvcream/mvcreamCopy'
import { getMvserumCopy } from '@/components/product/mvserum/mvserumCopy'
import { getNdCellCopy } from '@/components/product/ndcell/ndCellCopy'
import { getOvernightCopy } from '@/components/product/overnight/overnightCopy'
import { getPccreamCopy } from '@/components/product/pccream/pccreamCopy'
import { getPcserumCopy } from '@/components/product/pcserum/pcserumCopy'
import { getPctTonerCopy } from '@/components/product/pcttoner/pctTonerCopy'
import { getPdrnMaskCopy } from '@/components/product/pdrnmask/pdrnMaskCopy'
import { getPeptideGelCopy } from '@/components/product/peptidegel/peptideGelCopy'
import { getPostcreamCopy } from '@/components/product/postcream/postcreamCopy'
import { getAwsCopy } from '@/components/product/powersolution/awsCopy'
import { getCtsCopy } from '@/components/product/powersolution/ctsCopy'
import { getHesCopy } from '@/components/product/powersolution/hesCopy'
import { getPcsCopy } from '@/components/product/powersolution/pcsCopy'
import { getPowerSolutionCopy } from '@/components/product/powersolution/powerSolutionCopy'
import { getSwsCopy } from '@/components/product/powersolution/swsCopy'
import { getRemoverCopy } from '@/components/product/remover/removerCopy'
import { getRevitaGlowCopy } from '@/components/product/revitaglow/revitaGlowCopy'
import { getScalpBrushCopy } from '@/components/product/scalpbrush/scalpBrushCopy'
import { getSeaAlgaeCopy } from '@/components/product/sealgae/seaAlgaeCopy'
import { getSnowO2Copy } from '@/components/product/snowo2/snowo2Copy'
import { getSpcreamCopy } from '@/components/product/spcream/spcreamCopy'
import { getSrsCopy } from '@/components/product/srs/srsCopy'
import { getUltraShieldCopy } from '@/components/product/ultrashield/ultraShieldCopy'

/**
 * Each copy module returns its own interface, and those interfaces carry no
 * index signature, so the registry is typed by what it is used for - an object
 * to be read by name - rather than by any one product's shape.
 */
export type BespokeCopyGetter = (locale: string) => object

export const BESPOKE_COPY_GETTERS: Record<string, BespokeCopyGetter> = {
  '3': getHairGenBoosterCopy,
  '4': getHesCopy,
  '5': getPowerSolutionCopy,
  '6': getCtsCopy,
  '7': getPcsCopy,
  '8': getSwsCopy,
  '9': getAwsCopy,
  '10': getSnowO2Copy,
  '11': getRemoverCopy,
  '12': getEpiCopy,
  '13': getSrsCopy,
  '14': getMistCopy,
  '15': getPctTonerCopy,
  '16': getBoosterCopy,
  '17': getEyeSerumCopy,
  '18': getHsserumCopy,
  '19': getAfsCopy,
  '20': getPcserumCopy,
  '21': getMvserumCopy,
  '22': getAntiWrinkleCopy,
  '23': getNdCellCopy,
  '24': getEyeCreamCopy,
  '25': getPostcreamCopy,
  '27': getSpcreamCopy,
  '28': getHydroSoothingCopy,
  '29': getMhcreamCopy,
  '30': getPccreamCopy,
  '31': getMvcreamCopy,
  '32': getAntiWrinkleCreamCopy,
  '33': getEyePatchCopy,
  '34': getOvernightCopy,
  '35': getHydroCoolCopy,
  '36': getSeaAlgaeCopy,
  '37': getPeptideGelCopy,
  '38': getEzCo2Copy,
  '39': getUltraShieldCopy,
  '40': getMultiSunCopy,
  '41': getBbCushionCopy,
  '42': getBlemishBalmCopy,
  '43': getHairTonicCopy,
  '44': getMediShampooCopy,
  '45': getHairSolutionCopy,
  '46': getScalpPeelingCopy,
  '47': getMesopeciaKitCopy,
  '48': getHairGentronCopy,
  '49': getGenoLedCopy,
  '50': getEyeKitCopy,
  '51': getBioFermentCopy,
  '52': getPdrnMaskCopy,
  '53': getCollagenMaskCopy,
  '55': (locale: string) => pickBeautyBoxLocale(BEAUTY_BOXES['55'].copy, locale),
  '56': (locale: string) => pickBeautyBoxLocale(BEAUTY_BOXES['56'].copy, locale),
  '57': (locale: string) => pickBeautyBoxLocale(BEAUTY_BOXES['57'].copy, locale),
  '58': (locale: string) => pickBeautyBoxLocale(BEAUTY_BOXES['58'].copy, locale),
  '59': (locale: string) => pickBeautyBoxLocale(BEAUTY_BOXES['59'].copy, locale),
  '60': getBioMesoExpertCopy,
  '61': getScalpBrushCopy,
  '62': (locale: string) => pickBeautyBoxLocale(BEAUTY_BOXES['62'].copy, locale),
  '63': getRevitaGlowCopy,
  '64': getHairStampCopy,
  '65': getBioMesoCopy,
  '66': getCeraCopy,
}

export function getBespokeCopy(
  productNumber: string | number | null | undefined,
  locale: string
): Record<string, unknown> | null {
  const getter = BESPOKE_COPY_GETTERS[String(productNumber ?? '')]
  return getter ? (getter(locale) as Record<string, unknown>) : null
}
