import { Partner } from '@/types/partner';

export const partnersData: Partner[] = [
  {
    id: "persona-marina",
    name: "UNIQUE PERSONA, DUBAI MARINA",
    type: "Beauty & Aesthetic Center",
    description: "Professional beauty salon offering comprehensive skincare and aesthetic services in Dubai Marina",
    location: "The Residences at Marina Gate 1, Dubai Marina",
    phone: "+971 52 948 1238",
    website: "https://persona-dubai.com/eng",
    directions: "https://www.google.com/maps/dir//The+Residences+at+Marina+Gate+1+-+Dubai+-+%D0%9E%D0%90%D0%AD/@25.086284,55.1398907,14.76z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3e5f6bdd6fb9a655:0x9d88db1312e9d2e3!2m2!1d55.147257!2d25.0862329?entry=ttu&g_ep=EgoyMDI1MTAyMi4wIKXMDSoASAFQAw%3D%3D",
    logo: "/images/partners/Persona.png",
    theme: "pink"
  },
  {
    id: "persona-palm",
    name: "UNIQUE PERSONA, PALM JUMEIRAH",
    type: "Beauty & Aesthetic Center",
    description: "Second location of professional beauty salon offering comprehensive skincare and aesthetic services in Palm Jumeirah",
    location: "LG floor, Nakheel Mall - Palm Jumeirah, Dubai",
    phone: "+971 52 723 6572",
    website: "https://persona-dubai.com/palm",
    directions: "https://www.google.com/maps?sca_esv=254941356981cfe9&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifNZ5hzw_WMOirnwpcghXVhwM3hBJw:1761383254480&gs_lp=Egxnd3Mtd2l6LXNlcnAiCnBlcnNvbmEgbmEqAggAMgoQIxiABBgnGIoFMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBSOURUIEBWL0IcAF4AZABAJgBhwGgAYMHqgEDMC43uAEDyAEA-AEBmAIIoAK5B8ICChAAGLADGNYEGEfCAgYQABgWGB7CAggQLhiABBjLAcICCxAuGIAEGNQCGMsBmAMAiAYBkAYIkgcDMS43oAf_O7IHAzAuN7gHuAfCBwUwLjEuN8gHKQ&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KT9ts0Vza18-MV2OH9RxvODz&daddr=LG+floor,+Nakheel+Mall+-+Nakhlat+Jumeira+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/Persona.png",
    theme: "pink"
  },
  {
    id: "persona-downtown",
    name: "UNIQUE PERSONA, DOWNTOWN",
    type: "Beauty & Aesthetic Center",
    description: "Third location of professional beauty salon offering comprehensive skincare and aesthetic services in Downtown Dubai",
    location: "Downtown Dubai - South Ridge, Dubai",
    phone: "+971 58 298 0622",
    website: "https://persona-dubai.com/downtown",
    directions: "https://www.google.com/maps?sca_esv=254941356981cfe9&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifMcvEfeB5vjDCsZXY1dxYn3F-03KA:1761385503810&uact=5&gs_lp=Egxnd3Mtd2l6LXNlcnAiIFVOSVFVRSBQRVJTT05BIHNvdXRoIHJpZGdlIHRvd2VyMgcQIRigARgKMgcQIRigARgKMgcQIRigARgKSM0lUFBY6iRwAXgBkAEAmAHbAqAB6BOqAQgwLjE2LjAuMbgBA8gBAPgBAZgCEqACxxTCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICDhAuGIAEGMcBGMsBGK8BwgIIEAAYgAQYywHCAgUQABiABMICCxAuGIAEGMcBGK8BwgIIEAAYFhgKGB7CAgYQABgWGB7CAh0QLhiABBjHARjLARivARiXBRjcBBjeBBjgBNgBAcICBxAAGIAEGA3CAg0QLhiABBjHARgNGK8BwgIFECEYoAHCAgQQIRgVwgIFECEYnwWYAwCIBgGQBgm6BgYIARABGBSSBwgxLjE2LjAuMaAHykOyBwgwLjE2LjAuMbgHxRTCBwYwLjE1LjPIBy4&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KQEgvFUnaV8-MW_iFs8DwPSX&daddr=Downtown+Dubai+-+South+Ridge+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/Persona.png",
    theme: "pink"
  },
  {
    id: "faceroom",
    name: "FACE ROOM, DUBAI MARINA",
    type: "Facial Care & Massage Studio",
    description: "Professional facial massage and cosmetology services with unique techniques for skin care and relaxation",
    location: "The Residences at Marina Gate 2, Dubai Marina",
    phone: "+971 52 829 0457",
    website: "https://face-rooms.com",
    directions: "https://www.google.com/maps/search/The+Residences+at+Marina+Gate+2+Dubai+Marina",
    logo: "/images/partners/logo-faceroom.png",
    theme: "blue"
  },
  {
    id: "evolution",
    name: "EVOLUTION AESTHETICS CLINIC, JUMEIRAH 3",
    type: "Aesthetic Medical Clinic",
    description: "Elevating aesthetics standards with comprehensive aesthetic cosmetology, gynecology, injectables, and advanced beauty treatments",
    location: "49 Umm Al Sheif Rd - Jumeira Third - Jumeirah 3 - Dubai",
    phone: "+971 4 706 5000",
    website: "https://evoclinic.ae",
    directions: "https://www.google.com/maps?rlz=1C5CHFA_enAE820AE820&gs_lcrp=EgZjaHJvbWUyCQgAEEUYORiABDIHCAEQABjvBTIKCAIQABiABBiiBDIKCAMQABiABBiiBDIHCAQQABjvBdIBCDU5NjRqMGo3qAIAsAIA&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KZmTgf_la18-MRupdQ8rSJ36&daddr=49+Umm+Al+Sheif+Rd+-+Jumeira+Third+-+Jumeirah+3+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/evo.png",
    theme: "purple"
  },
  {
    id: "shakirovna",
    name: "SHAKIROVNA LADIES BEAUTY SALOON, DUBAI MARINA",
    type: "Ladies Beauty Salon",
    description: "Professional beauty services for women with expert care and attention to detail in Jumeirah Beach Residence",
    location: "Jumeirah Beach Residence 2, Marina Wharf 1",
    phone: "+971 50 409 9407",
    website: "https://shakirovna.com",
    directions: "https://www.google.com/maps?rlz=1C5CHFA_enAE820AE820&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KS37CzxUE18-MV_-F9n4c6n1&daddr=Marina+Promenade+-+Marsa+Dubai+-+Dubai+Marina+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/Shakirovna.png",
    theme: "purple"
  },
  {
    id: "shakirovna-business-bay",
    name: "ELITE SHAKIROVNA BEAUTY CENTER, BUSINESS BAY",
    type: "Elite Beauty Center",
    description: "Premium beauty center offering comprehensive beauty services including hair, eyelashes, cosmetology, massage therapy, and specialized treatments in Business Bay",
    location: "One by Omniyat, Business Bay, Dubai",
    phone: "+971 58 875 9719",
    website: "https://shakirovna.com/bb",
    directions: "https://www.google.com/maps/search/One+by+Omniyat+Business+Bay+Dubai",
    logo: "/images/partners/Shakirovna.png",
    theme: "purple"
  },
      {
        id: "face-only",
        name: "THE FACE ONLY, BLUEWATERS ISLAND",
        type: "Specialized Facial Treatment Salon",
    description: "Professional facial treatment salon specializing in signature TFO massage, skin therapy, and advanced facial treatments with focus on natural beauty and effective results",
    location: "Blue Waves Residence - 9 A Street - Marsa Dubai, Dubai",
    phone: "+971 54 348 8117",
    website: "https://thefaceonly.com",
    directions: "https://www.google.com/maps?sca_esv=254941356981cfe9&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifPF4L5bN-vsNASbTGi2iDyOGwbNcQ:1761385666402&uact=5&gs_lp=Egxnd3Mtd2l6LXNlcnAiFWZhY2Ugb25seSBzYWxvbiBkdWJhaTIFECEYoAEyBRAhGKABMgUQIRigATIFECEYnwUyBRAhGJ8FMgUQIRifBTIFECEYnwUyBRAhGJ8FMgUQIRifBTIFECEYnwVIkB9QmghYnx1wAngBkAEAmAGYAaAB9AmqAQQwLjEwuAEDyAEA-AEBmAIMoAK4CsICChAAGLADGNYEGEfCAgQQIxgnwgIIEAAYBRgNGB7CAgUQABjvBcICCBAAGIAEGKIEwgIIEAAYCBgNGB7CAgYQABgWGB7CAgQQIRgVwgIHECEYoAEYCpgDAIgGAZAGCJIHBDIuMTCgB8gvsgcEMC4xMLgHsgrCBwUwLjQuOMgHJw&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KQG0tOpTFV8-Maa3vu0wEN-S&daddr=Blue+Waves+Residence+-+9+A+Street+-+Marsa+Dubai+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/thefaceonly.png",
    theme: "blue"
  },
  {
    id: "egoistka",
    name: "EGOISTKA BEAUTY SALON, DUBAI MARINA",
    type: "Comprehensive Beauty Salon",
    description: "Professional beauty salon offering comprehensive beauty services including manicure, pedicure, podiatry, eyebrow and eyelash services, hair treatments, cosmetology, massage, and advanced beauty treatments in Dubai Marina",
    location: "Dubai Marina Promenade, Delphine Tower, Ground Floor, Shop 2",
    phone: "+971 58 558 4002",
    website: "https://davaidubai.ae/en/my-daily-life-in-dubai/beauty-and-self-care/egoistka-beauty-salon",
    directions: "https://www.google.com/maps?sca_esv=254941356981cfe9&biw=1554&bih=862&sxsrf=AE3TifMsU4ygFJB7jBNdHE1kZZkhtC-Q7g:1761386513035&uact=5&gs_lp=Egxnd3Mtd2l6LXNlcnAiH2Vnb2lzdGthIGJlYXV0eSBzYWxvbiBkdWJhaSBtYXAyCBAhGKABGMMESOAPUPwIWOsNcAJ4AJABAJgBpQGgAbUGqgEDMC42uAEDyAEA-AEBmAIFoAK4A8ICCBAAGLADGO8FwgILEAAYgAQYsAMYogTCAgoQIRigARjDBBgKmAMAiAYBkAYFkgcDMi4zoAeuFLIHAzAuM7gHtQPCBwMwLjXIBwg&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KXdgif0DE18-MaAmDFkVt05k&daddr=Marina+Promenade,+Delphine+Tower,+Shop+No+2+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/Egoistka.png",
    theme: "purple"
  },
  {
    id: "vesna",
    name: "VESNA BEAUTY LOUNGE, DUBAI MARINA",
    type: "Beauty Lounge",
    description: "Professional beauty lounge offering comprehensive beauty services and treatments in Dubai Marina",
    location: "The Zen - Al Seba St - Marsa Dubai - Dubai Marina, Dubai",
    phone: "+971 55 341 1859",
    directions: "https://www.google.com/maps/dir//The+Zen+-+Al+Seba+St+-+Marsa+Dubai+-+Dubai+Marina+-+Dubai+-+%D0%9E%D0%90%D0%AD/@25.0675537,55.0485508,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3e5f13045e9c3d51:0x33cac3f11886f661!2m2!1d55.1309523!2d25.0675764?entry=ttu&g_ep=EgoyMDI1MTAyMi4wIKXMDSoASAFQAw%3D%3D",
    logo: "/images/partners/Vesna.png",
    theme: "pink"
  },
  {
    id: "kindcare",
    name: "KINDCARE MEDICAL CENTER, JUMEIRAH",
    type: "Multispeciality Medical Center",
    description: "Integrative multispeciality healthcare provider offering comprehensive medical services including family medicine, dermatology, plastic surgery, and specialized treatments in Jumeirah",
    location: "Villa number 794 - Jumeira St - Umm Suqeim Second - Jumeirah 3 - Dubai",
    phone: "+971 4 338 8588",
    website: "https://kindcare.ae",
    directions: "https://www.google.com/maps?rlz=1C5CHFA_enAE820AE820&gs_lcrp=EgZjaHJvbWUqCggAEAAY4wIYgAQyCggAEAAY4wIYgAQyDQgBEC4YrwEYxwEYgAQyCQgCEAAYChiABDIHCAMQABiABDIICAQQABgWGB4yCAgFEAAYFhgeMggIBhAAGBYYHjIICAcQABgWGB4yCAgIEAAYFhgeMggICRAAGBYYHtIBCDIxNzRqMGo3qAIAsAIA&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KcMzGY5QQl8-MYaoJDpzrhyP&daddr=Villa+number+794+-+Jumeira+St+-+Umm+Suqeim+Second+-+Jumeirah+3+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/KIND.png",
    theme: "emerald"
  },
  {
    id: "hortman-1",
    name: "HORTMAN CLINICS, BUSINESS BAY",
    type: "Premium Aesthetic Clinic",
    description: "Renowned aesthetic clinic specializing in cosmetic surgeries, dermatology, anti-aging treatments, and wellness services",
    location: "32 Floor - 1 Sheikh Zayed Rd - Trade Center First - Dubai",
    phone: "+971 4 566 2615",
    website: "https://hortmanclinics.com",
    directions: "https://www.google.com/maps?sca_esv=254941356981cfe9&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifPTZte0PBmw_HTgKUi-In8WvlDkGQ:1761382021983&uact=5&gs_lp=Egxnd3Mtd2l6LXNlcnAiEGhvcnRtYW4gY2xpbmljcyAyEBAuGIAEGMcBGCcYigUYrwEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMgYQABgWGB4yBRAAGO8FMgUQABjvBTIdEC4YgAQYxwEYigUYrwEYlwUY3AQY3gQY4ATYAQFI7wRQCFiEAnABeACQAQCYAW-gAcwCqgEDMC4zuAEDyAEA-AEBmAIIoAK5B8ICDRAuGLADGMcBGCcYrwHCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICBRAAGIAEmAMAiAYBkAYKugYGCAEQARgUkgcDMS4yoAe7H7IHAzAuMrgH6AHCBwUwLjEuMsgHCg&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KSEXfIP9Q18-MRkmpM9ul2lD&daddr=32+Floor+-+1+Sheikh+Zayed+Rd+-+Trade+Center+First+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/hortman.png",
    theme: "emerald"
  },
  {
    id: "hortman-2",
    name: "HORTMAN CLINICS 2, JUMEIRAH 3",
    type: "Premium Aesthetic Clinic",
    description: "Second location of renowned aesthetic clinic specializing in cosmetic surgeries, dermatology, and wellness services",
    location: "450 Jumeira St - Jumeirah - Jumeirah 3 - Dubai",
    phone: "+971 52 200 5011",
    website: "https://hortmanclinics.com/contact",
    directions: "https://www.google.com/maps?sca_esv=254941356981cfe9&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifNdK-nhSVi0UM_BIxnB3Rm8KYCyPg:1761382025361&uact=5&gs_lp=Egxnd3Mtd2l6LXNlcnAiEWhvcnRtYW4gY2xpbmljcyAyMhAQLhiABBjHARgnGIoFGK8BMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMgYQABgWGB4yBRAAGO8FMgUQABjvBTIdEC4YgAQYxwEYigUYrwEYlwUY3AQY3gQY4ATYAQFI7wRQCFiEAnABeACQAQCYAW-gAcwCqgEDMC4zuAEDyAEA-AEBmAIIoAK5B8ICDRAuGLADGMcBGCcYrwHCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICBRAAGIAEmAMAiAYBkAYKugYGCAEQARgUkgcDMS4yoAe7H7IHAzAuMrgH6AHCBwUwLjEuMsgHCg&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KWNJRzEAQ18-MZtAmPB8BfjS&daddr=450+Jumeira+St+-+Jumeirah+-+Jumeirah+3+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/hortman.png",
    theme: "emerald"
  },
  {
    id: "lfk-clinic",
    name: "LFK CLINIC, BUSINESS BAY",
    type: "Luxury Aesthetic Clinic",
    description: "Award-winning luxury aesthetic clinic specializing in Russian Lips technique, Hollywood Face, and advanced cosmetic procedures with expert care from leading Russian specialists",
    location: "Al Saqr Business Tower, 11th floor, DIFC, Dubai",
    phone: "+971 54 233 6281",
    website: "https://lipsforkiss.com/dubai_clinic",
    directions: "https://www.google.com/maps/dir//Al+Saqr+Business+Tower+-+Trade+Center+Second+-+DIFC+-+Dubai+-+%D0%9E%D0%90%D0%AD/@25.2139349,55.1956632,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3e5f439c6c9f96a5:0x7ac63fa8a8735ce!2m2!1d55.2780647!2d25.2139577?entry=ttu&g_ep=EgoyMDI1MTAyMi4wIKXMDSoASAFQAw%3D%3D",
    logo: "/images/partners/kiss.png",
    theme: "purple"
  },
  {
    id: "elaris",
    name: "ELARIS BEAUTY SALON, BUSINESS BAY",
    type: "Luxury Beauty Salon",
    description: "Dubai's newest and most ambitious Beauty City offering luxury beauty services, expert stylists, and comprehensive beauty treatments in Business Bay",
    location: "Business Bay, Maison Prive, Shop #3 & 4 - Dubai",
    phone: "+971 58 697 1090",
    website: "https://elarisalon.com",
    directions: "https://www.google.com/maps/dir/28.2295568,-16.8407006/Elaris+Beauty+Salon+-+Business+Bay,+Maison+Prive,+Shop+%233+%26+4+-+Dubai+-+%D0%9E%D0%90%D0%AD/@33.1022972,-2.0987042,4z/data=!4m9!4m8!1m1!4e1!1m5!1m1!1s0x89af6d6aa285182f:0xfb3c239d4e636169!2m2!1d55.2751612!2d25.1846245?entry=ttu&g_ep=EgoyMDI1MTAyMi4wIKXMDSoASAFQAw%3D%3D",
    logo: "/images/partners/elaris.png",
    theme: "pink"
  },
  {
    id: "milyne",
    name: "MILYNE AESTHETIC CENTER, DUBAI CREEK HARBOUR",
    type: "Aesthetic Medical Center",
    description: "Your one-stop beauty solution offering Morpheus8, Forma, Hydrafacial, Fillers, Skin Boosters, Endospheres, Body Treatments, Professional Skin Care, Mesojet and many more advanced treatments",
    location: "Dubai Creek Residences - Ground Floor - Al Kheeran First - Dubai Creek Harbour - Dubai",
    phone: "+971 52 117 9436",
    website: "https://milyne.ae",
    directions: "https://www.google.com/maps?rlz=1C5CHFA_enAE820AE820&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIJCAEQABgTGIAEMgcIAhAAGO8FMgcIAxAAGO8FMgcIBBAAGO8FMgcIBRAAGO8FMgcIBhAAGO8F0gEIMzY2NWowajmoAgawAgHxBSFPW0ktbJMd&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KQHeW0f2_02CMXP3qlhiZjlO&daddr=Dubai+Creek+Residences+-+Ground+Floor+-+Al+Kheeran+First+-+Dubai+Creek+Harbour+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/milyne.png",
    theme: "emerald"
  },
  {
    id: "hideaway",
    name: "THE HIDEAWAY FOR WOMEN SALON, JUMEIRAH 3",
    type: "Hair & Beauty Salon",
    description: "Family owned and run hair and beauty salon established in 2021",
    location: "La Plage Shop 6 - 403 jumeirah Street - Al Athar Street - Dubai",
    phone: "+971 4 591 8879",
    website: "https://thehideaway.ae",
    directions: "https://www.google.com/maps?sca_esv=408005786895665f&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifOwLEVh0KaiO4iVJsSIlFTBM1SLxw:1761426054574&uact=5&gs_lp=Egxnd3Mtd2l6LXNlcnAiIXRoZSBoaWRld2F5IGZvciB3b21lbiBzYWxvbiBkdWJhaTIGEAAYFhgeMgUQABjvBTIFEAAY7wUyBRAAGO8FMggQABiABBiiBEi2CFBqWOUGcAF4AJABAJgBkwGgAfIFqgEDMi41uAEDyAEA-AEBmAIHoAK6BcICChAAGLADGNYEGEeYAwDiAwUSATEgQIgGAZAGB5IHAzIuNaAH5ByyBwMxLjW4B7cFwgcFMC42LjHIBw8&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KY-K7sUuQ18-MZ8GtMbLO0UX&daddr=La+Plage+Shop+6+-+403+jumeirah+Street+-+Al+Athar+Street+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/hideaway.png",
    theme: "pink"
  },
  {
    id: "skinstory",
    name: "SKIN STORY DUBAI",
    type: "Korean Skincare Online Store",
    description: "Renowned Korean skincare online store offering an extensive collection of authentic Korean skincare products including GENOSYS products",
    location: "Online Store - UAE Wide Delivery",
    phone: "+971 58 509 2199",
    website: "https://skinstorydubai.com",
    logo: "/images/partners/skinstory.png",
    theme: "blue"
  },
  {
    id: "melanta",
    name: "MELANTA AESTHETIC MEDICAL CLINIC, JUMEIRAH 3",
    type: "Medical Aesthetic Clinic",
    description: "Professional medical aesthetic clinic offering advanced cosmetic treatments and skincare solutions in Jumeirah 3",
    location: "748A Al Wasl Rd - Jumeirah - Jumeirah 3 - Dubai",
    phone: "+971 50 577 3043",
    website: "https://clinicamelanta.com",
    directions: "https://www.google.com/maps?sca_esv=5f8ad457132af750&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifOw07ZH8BqJw7gWtf_Tq1KX9XyhAQ:1761576218126&gs_lp=Egxnd3Mtd2l6LXNlcnAiB21lbGFudGEqAggAMg4QLhiABBjHARjLARivATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyDhAuGIAEGMcBGMsBGK8BMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIdEC4YgAQYxwEYywEYrwEYlwUY3AQY3gQY4ATYAQFI3B1QxQdYlRNwAXgBkAEAmAGyAqABlQ-qAQUyLTQuM7gBA8gBAPgBAZgCCaACohnCAgoQABiwAxjWBBhHwgIEECMYJ8ICChAAGIAEGEMYigXCAgsQLhiABBjHARivAcICCxAuGIAEGNEDGMcBwgIFEAAYgATCAhAQLhiABBjHARgnGIoFGK8BwgIKECMYgAQYJxiKBcICChAAGIAEGBQYhwLCAgoQLhiABBhDGIoFwgIFEC4YgATCAhQQLhiABBjHARiYBRiZBRieBRivAcICGRAuGIAEGEMYigUYlwUY3AQY3gQY4ATYAQHCAggQLhiABBjLAcICGRAuGIAEGEMYigUYlwUY3AQY3gQY3wTYAQHCAgoQABiABBgKGMsBmAMA4gMFEgExIECIBgGQBgi6BgYIARABGBSSBwsxLjAuNC4zLjctMaAH4oQBsgcFMi00LjO4B9APwgcHMC4xLjcuMcgHMw&um=1&ie=UTF-8&fb=1&gl=ae&sa=X&geocode=KU83fM2taV8-McWNMxayfSN1&daddr=748A+Al+Wasl+Rd+-+Jumeirah+-+Jumeirah+3+-+Dubai",
    logo: "/images/partners/melanta.png",
    theme: "purple"
  },
  {
    id: "sugar-wax",
    name: "SUGAR & WAX BEAUTY SALON, DUBAI MARINA",
    type: "Beauty Salon",
    description: "Professional beauty salon offering comprehensive beauty services including waxing, skincare, and beauty treatments in Dubai Marina",
    location: "Dubai Marina, Al Sayorah Street, Marina Wharf 2, Basement 2, Shop 4, Dubai, United Arab Emirates",
    phone: "050 829 8727",
    website: "https://sugarwaxuae.com/",
    directions: "https://www.google.com/maps?s=web&rlz=1C5CHFA_enAE820AE820&lqi=ChhTdWdhciAmIFdheCBCZWF1dHkgU2Fsb25I4ab8ouS5gIAIWjIQABABEAIQAxAEGAAYARgCGAMYBCIYc3VnYXIgJiB3YXggYmVhdXR5IHNhbG9uMgJlbpIBDGJlYXV0eV9zYWxvbpoBI0NoWkRTVWhOTUc5blMwVkpRMEZuU1VRMWQyOHlUMXBCRUFFqgFbCg0vZy8xMXR0MjV6NHcxCgkvbS8wNTY5emcQATIfEAEiG8Qe-29yMbEvFvLrjWSxk0yGKJNoCT_02R8m1TIcEAIiGHN1Z2FyICYgd2F4IGJlYXV0eSBzYWxvbvoBBAhQEEo&phdesc=5KxfX1gGpUU&vet=12ahUKEwixyYPZqMmQAxU5ExAIHYKcIpAQ1YkKegQIJhAB..i&cs=0&um=1&ie=UTF-8&fb=1&gl=ae&sa=X&geocode=KWc5mCujE18-MYBdpj0RmzXd&daddr=Marina+Warf+2+-+Dubai",
    logo: "/images/partners/wax.png",
    theme: "pink"
  },
  {
    id: "bianco-spa",
    name: "BIANCO SPA, SILICON OASIS (DSO)",
    type: "Spa & Wellness Center",
    description: "Since 2018, Bianco has been at the forefront of women's empowerment, offering a sanctuary where women can express themselves in a space of their own. Our minimalist design creates a serene and luxurious atmosphere, allowing every woman to experience true elegance and comfort.",
    location: "Cedre Villas Community Centre - Cedre Shopping Centre shop 24&26 - Dubai",
    phone: "+971 4 333 6166",
    website: "https://biancospa.ae",
    directions: "https://www.google.com/maps/dir//Cedre+Villas+Community+Centre+-+Cedre+Shopping+Centre+shop+24%2626+-+Dubai/@25.1272187,55.3142557,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3e5f65f4c055c2df:0xe96eb4d3642e0d30!2m2!1d55.3966572!2d25.1272415?entry=ttu&g_ep=EgoyMDI1MTAyNi4wIKXMDSoASAFQAw%3D%3D",
    logo: "/images/partners/bianco.png",
    theme: "emerald"
  },
  {
    id: "bianco-spa-dubai-hills",
    name: "BIANCO SPA, DUBAI HILLS MALL",
    type: "Spa & Wellness Center",
    description: "Since 2018, Bianco has been at the forefront of women's empowerment, offering a sanctuary where women can express themselves in a space of their own. Our minimalist design creates a serene and luxurious atmosphere, allowing every woman to experience true elegance and comfort.",
    location: "1st Floor, Dubai Hills Mall - Dubai",
    phone: "+971 4 458 0078",
    website: "https://biancospa.ae",
    directions: "https://www.google.com/maps/dir//Al+Khail+Rd+-+Hadaeq+Sheikh+Mohammed+Bin+Rashid+-+Dubai/@25.1027297,55.1553557,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3e5f6fddd99a5929:0xfe04d22cbdb3723b!2m2!1d55.2377572!2d25.1027525?entry=ttu&g_ep=EgoyMDI1MTAyNi4wIKXMDSoASAFQAw%3D%3D",
    logo: "/images/partners/bianco.png",
    theme: "emerald"
  },
  {
    id: "bianco-spa-layan",
    name: "BIANCO SPA, LAYAN COMMUNITY",
    type: "Spa & Wellness Center",
    description: "Since 2018, Bianco has been at the forefront of women's empowerment, offering a sanctuary where women can express themselves in a space of their own. Our minimalist design creates a serene and luxurious atmosphere, allowing every woman to experience true elegance and comfort.",
    location: "Layan Community Center - Dubai",
    phone: "+971 4 423 2216",
    website: "https://biancospa.ae",
    directions: "https://www.google.com/maps/dir/25.2161539,55.3131125/Bianco+Spa+(Layan+Branch)+-+%D0%94%D1%83%D0%B1%D0%B0%D0%B9/@25.1375185,55.2114523,12z/data=!3m2!4b1!5s0x3e5f6eb259c704c9:0x83ba7f3255ad4510!4m8!4m7!1m0!1m5!1m1!1s0x3e5f7178f7cc40af:0xdcf13164632ce82b!2m2!1d55.2830924!2d25.0321311?entry=ttu&g_ep=EgoyMDI1MTAyNi4wIKXMDSoASAFQAw%3D%3D",
    logo: "/images/partners/bianco.png",
    theme: "emerald"
  },
  {
    id: "bianco-spa-jumeirah-golf",
    name: "BIANCO SPA, JUMEIRAH GOLF ESTATES",
    type: "Spa & Wellness Center",
    description: "Since 2018, Bianco has been at the forefront of women's empowerment, offering a sanctuary where women can express themselves in a space of their own. Our minimalist design creates a serene and luxurious atmosphere, allowing every woman to experience true elegance and comfort.",
    location: "Jumeirah Golf Estates Country Club - Dubai",
    phone: "+971 4 572 7765",
    website: "https://biancospa.ae",
    directions: "https://www.google.com/maps/dir/25.2161539,55.3131125/Bianco+JGE+Ladies+Salon+-+Jumeirah+Golf+Estates+-+%D0%94%D1%83%D0%B1%D0%B0%D0%B9/@25.1337839,55.1388647,12z/data=!3m2!4b1!5s0x3e5f6eb259c704c9:0x83ba7f3255ad4510!4m8!4m7!1m0!1m5!1m1!1s0x9b0aa2102b78d27:0x2eae56fe46822572!2m2!1d55.19986!2d25.0209213?entry=ttu&g_ep=EgoyMDI1MTAyNi4wIKXMDSoASAFQAw%3D%3D",
    logo: "/images/partners/bianco.png",
    theme: "emerald"
  },
  {
    id: "lodyana-spa",
    name: "LODYana Ladies Spa - Healing and Wellness Center, ABU DHABI",
    type: "Healing and Wellness Center",
    description: "LODYana Spa is your destination to celebrate the harmony of body and soul, where through our various treatments we create a warm and relaxing place, so that you can enjoy a unique experience in our various facilities and enjoy the serenity that reflects beauty, confidence and radiance.",
    location: "Al Sahel Towers - Block A 1st Floor - Al Bateen - W12 - Abu Dhabi",
    phone: "+971 02 585 7072",
    website: "https://www.lodyanaspa.ae",
    directions: "https://www.google.com/maps?rlz=1C5CHFA_enAE820AE820&um=1&ie=UTF-8&fb=1&gl=ae&sa=X&geocode=KUfZ18p8ZV4-MTBQxZ9_9Ntv&daddr=Al+Sahel+Towers+-+Block+A+1st+Floor+-+Al+Bateen+-+W12+-+Abu+Dhabi",
    logo: "/images/partners/lodyana.png",
    theme: "purple"
  },
  {
    id: "different-aesthetic-clinic",
    name: "DIFFERENT AESTHETIC CLINIC, ABU DHABI",
    type: "Aesthetic Medical Clinic",
    description: "Professional aesthetic clinic offering advanced cosmetic treatments and medical aesthetic services in Abu Dhabi. Committed to providing exceptional care and innovative solutions for beauty and wellness.",
    location: "St Regis Residences Block 5 - Abu Dhabi",
    phone: "+971 058 519 2533",
    website: "https://n1313175.alteg.io/company/1256716/personal/menu?o=",
    directions: "https://www.google.com/maps?sca_esv=4371f740622c0d3e&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifMWP5n_iUUsRWoRNFaCtfg1PAon8A:1761746161432&uact=5&gs_lp=Egxnd3Mtd2l6LXNlcnAiJURpZmZlcmVudCBBZXN0aGV0aWMgQ2xpbmljICBhYnUgZGhhYmkyCBAAGIAEGMsBMggQABiABBjLATIEEAAYHjIFEAAY7wUyBRAAGO8FMgUQABjvBTIIEAAYgAQYogRI3wJQAFgAcAB4AZABAJgB6gGgAeoBqgEDMi0xuAEDyAEA-AEC-AEBmAIBoALxAZgDAJIHAzItMaAHxwSyBwMyLTG4B_EBwgcDMi0xyAcF&um=1&ie=UTF-8&fb=1&gl=ae&sa=X&geocode=KbuJJ11S0TdAMdOreALJ6DcS&daddr=St+Regis+Residences+Block+5+-+Abu+Dhabi",
    logo: "/images/partners/different.png",
    theme: "blue"
  },
  {
    id: "brau-jumeirah",
    name: "BRAU LADIES SALON, JUMEIRAH",
    type: "Ladies Beauty Salon",
    description: "Professional ladies salon specializing in brows, lashes, lips, eyes, and skin treatments. Express yourself with expert artistry for superior results.",
    location: "شارع الوصل - Dubai",
    phone: "+971 4 437 2600",
    website: "https://brau.ae/",
    directions: "https://www.google.com/maps/dir//%D8%B4%D8%A7%D8%B1%D8%B9+%D8%A7%D9%84%D9%88%D8%B5%D9%84+-+%D8%AF%D8%A8%D9%8A%E2%80%AD/@25.1511827,55.1303564,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3e5f6bdd74614a63:0x5070289594987312!2m2!1d55.2127665!2d25.1512?entry=ttu",
    logo: "/images/partners/brau.png",
    theme: "pink"
  },
  {
    id: "brau-springs-souk",
    name: "BRAU LADIES SALON, SPRINGS SOUK",
    type: "Ladies Beauty Salon",
    description: "Professional ladies salon specializing in brows, lashes, lips, eyes, and skin treatments. Express yourself with expert artistry for superior results.",
    location: "The Springs Souk - Dubai",
    phone: "+971 4 437 2600",
    website: "https://brau.ae/",
    directions: "https://www.google.com/maps/place/Brau/@25.0662021,55.1508382,13z/data=!4m22!1m15!4m14!1m6!1m2!1s0x3e5f6c36babd2c79:0x675853b2595d1a65!2zSnVtZWlyYWggVmlsbGFnZSBDaXJjbGUg2YLYsdmK2Kkg2KzZhdmK2LHYpyDYp9mE2K_Yp9im2LHZitip!2m2!1d55.2088007!2d25.0608609!1m6!1m2!1s0x3e5f6d9647ec5e6b:0xcc6634c38847d830!2sBrau,+The+Springs+Souk+-+Dubai!2m2!1d55.1921234!2d25.0662078!3m5!1s0x3e5f6d9647ec5e6b:0xcc6634c38847d830!8m2!3d25.0662078!4d55.1921234!16s%2Fg%2F11j1hx10km?entry=ttu",
    logo: "/images/partners/brau.png",
    theme: "pink"
  },
  {
    id: "brau-khalifa-city",
    name: "BRAU LADIES SALON, KHALIFA CITY, ABU DHABI",
    type: "Ladies Beauty Salon",
    description: "Professional ladies salon specializing in brows, lashes, lips, eyes, and skin treatments. Express yourself with expert artistry for superior results.",
    location: "Waitrose Center - Khalifa City - Abu Dhabi",
    phone: "+971 4 437 2600",
    website: "https://brau.ae/",
    directions: "https://www.google.com/maps/place/Brau/@24.7602938,54.5758733,10z/data=!4m22!1m15!4m14!1m6!1m2!1s0x3e5f6c36babd2c79:0x675853b2595d1a65!2zSnVtZWlyYWggVmlsbGFnZSBDaXJjbGUg2YLYsdmK2Kkg2KzZhdmK2LHYpyDYp9mE2K_Yp9im2LHZitip!2m2!1d55.2088007!2d25.0608609!1m6!1m2!1s0x3e5e4703c397d4b3:0xa6c998c3ddeb20a3!2sBRAU,+Waitrose+Center+-+Khalifa+City+-+Abu+Dhabi!2m2!1d54.5663204!2d24.4167725!3m5!1s0x3e5f6d9647ec5e6b:0xcc6634c38847d830!8m2!3d25.0662078!4d55.1921234!16s%2Fg%2F11j1hx10km?entry=ttu",
    logo: "/images/partners/brau.png",
    theme: "pink"
  },
  {
    id: "love-my-body",
    name: "LOVE MY BODY, BLUEWATERS ISLAND",
    type: "Body Correction Center",
    description: "Professional body correction center offering expert consultations and comprehensive body correction services.",
    location: "Bluewaters island, building 9 - Dubai",
    phone: "+971 58 578 5311",
    website: "https://lovemybody.ae/",
    directions: "https://www.google.com/maps/place/i+love+my+body+salon/data=!4m2!3m1!1s0x3e5f15d125214127:0xa6499e9c8b7cb6e6?sa=X&ved=1t:242&ictx=111",
    logo: "/images/partners/body.png",
    theme: "blue"
  },
  {
    id: "arfi-nails",
    name: "ARFI NAILS, AL BARSHA",
    type: "Nail Salon",
    description: "Professional nail salon offering comprehensive nail care services including manicures, pedicures, and nail art in Al Barsha.",
    location: "Shops 7, 8, and 9 Dawoud Building - Al Barsha - Al Barsha 1 - Dubai",
    phone: "+971 52 266 8099",
    website: "https://www.instagram.com/arfinails/",
    directions: "https://www.google.com/maps?rlz=1C5CHFA_enAE820AE820&gs_lcrp=EgZjaHJvbWUqBggAEEUYOzIGCAAQRRg7MgYIARBFGDzSAQg1MDM3ajBqN6gCALACAA&um=1&ie=UTF-8&fb=1&gl=ae&sa=X&geocode=KSFroyh7a18-MRPu5ZYIkeDd&daddr=Shops+7,+8,+and+9+Dawoud+Building+-+Al+Barsha+-+Al+Barsha+1+-+Dubai",
    logo: "/images/partners/arfi.png",
    theme: "pink"
  },
  {
    id: "fayy-health",
    name: "FAYY HEALTH, ONE CENTRAL OFFICES",
    type: "Holistic Health & Wellness Clinic",
    description: "Dubai's premier destination for holistic health and beauty, seamlessly blending cutting-edge wellness, aesthetics, and longevity treatments with personalized care. With over 18 years of expertise and 20+ medical specialists across multiple specialties including dermatology, plastic surgery, dentistry, and more.",
    location: "One Central, Office 2, 6th Floor, Unit 602, Dubai World Trade Centre - Dubai",
    phone: "+971 55 688 9909",
    website: "https://fayy.health/",
    directions: "https://www.google.com/maps/search/One+Central+Office+2+6th+Floor+Unit+602+Dubai+World+Trade+Centre",
    logo: "/images/partners/fay.png",
    theme: "emerald"
  },
  {
    id: "lavana-spa-difc",
    name: "LAVANA SPA, DIFC",
    type: "European Spa & Wellness Center",
    description: "Premier European spa in Dubai delivering unparalleled massage experiences. With 12 years of experience and professional therapists from Russia, Ukraine, Poland, Georgia, Bulgaria and Romania, offering European Aromatherapy, Swedish, Deep Tissue Massage, Moroccan Bath, and more in a tranquil ambiance.",
    location: "Residence Inn by Marriott - 115 Sheikh Zayed Road - Floor 45 - 2 - Trade Center Second - DIFC - Dubai",
    phone: "+971 56 395 8899",
    website: "https://lavanaspa.ae/",
    directions: "https://www.google.com/maps?sca_esv=3f626f5782a50780&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifPCzlwdVa9OQbPDQt0Y5-aB6CyBLA:1762786995199&gs_lp=Egxnd3Mtd2l6LXNlcnAiCmxhdmFuYSBzcGEqAggAMgoQIxiABBgnGIoFMggQABiABBjLATIOEC4YgAQYxwEYywEYrwEyDhAuGIAEGMcBGMsBGK8BMg4QLhiABBjHARjLARivATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyBRAAGIAESMUXUABY-gxwAHgAkAEAmAHxAaAB4RGqAQQyLTEwuAEDyAEA-AEBmAIKoAKeEsICChAjGPAFGCcYyQLCAgsQLhiABBjRAxjHAcICCxAuGIAEGMcBGK8BwgIQEC4YgAQYxwEYJxiKBRivAcICBRAuGIAEwgIKEC4YgAQYQxiKBcICDhAuGIAEGMcBGI4FGK8BwgIREC4YgAQYxwEYmAUYmQUYrwHCAggQLhiABBjUAsICCBAuGIAEGMsBwgIKEC4YgAQYChjLAZgDAJIHBDItMTCgB43NAbIHBDItMTC4B54SwgcFMC4xLjnIBy8&um=1&ie=UTF-8&fb=1&gl=ae&sa=X&geocode=Ka0XZqubQ18-MVl5hgZyAn4M&daddr=Residence+Inn+by+Marriott+-+115+Sheikh+Zayed+Road+-+Floor+45+-+2+-+Trade+Center+Second+-+DIFC+-+Dubai",
    logo: "/images/partners/lava.png",
    theme: "purple"
  },
  {
    id: "lips-for-kiss-difc",
    name: "LIPS for KISS CLINIC, DIFC",
    type: "Luxury Aesthetic Clinic",
    description: "Award-winning luxury aesthetic clinic specializing in Russian Lips technique, Hollywood Face, and advanced cosmetic procedures. Expert care from leading Russian specialists, ensuring precision and outstanding results.",
    location: "Al Saqr Business Tower - Trade Center Second - DIFC - Dubai, 11th floor",
    phone: "+971 54 233 6281",
    website: "https://lipsforkiss.com/dubai_clinic",
    directions: "https://www.google.com/maps/dir//Al+Saqr+Business+Tower+-+Trade+Center+Second+-+DIFC+-+Dubai/@25.2139349,55.1956632,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3e5f439c6c9f96a5:0x7ac63fa8a8735ce!2m2!1d55.2780647!2d25.2139577?entry=ttu&g_ep=EgoyMDI1MTExNy4wIKXMDSoASAFQAw%3D%3D",
    logo: "/images/partners/lips.png",
    theme: "purple"
  },
  {
    id: "body-mind-city-walk",
    name: "Body & Mind City Walk | Ladies Beauty Salon and Body Academy, Dubai City Walk",
    type: "Ladies Beauty Salon and Body Academy",
    description: "Premium class beauty academy offering comprehensive beauty services, body treatments, and professional training. A unique closed space for women only, providing conscious fitness, innovative cosmetology equipment, and expert care.",
    location: "Walk building, 16 - Dubai City Walk - Dubai",
    phone: "+971 58 584 7721",
    website: "https://luxbody.ae/",
    directions: "https://www.google.com/maps?s=web&sca_esv=d12c0c5e497b4209&lqi=ChNib2R5IGFuZCBtaW5kIGR1YmFpSMjR-5WtsoCACFo1EAAQARACEAMYABgBGAIYAyITYm9keSBhbmQgbWluZCBkdWJhaSoKCAIQABABEAIQAzICZW6SAQxiZWF1dHlfc2Fsb26aASNDaFpEU1VoTk1HOW5TMFZKUTBGblRVTlJialZIUjBabkVBRfoBBAgAEDg&vet=12ahUKEwj8pbCQwYqRAxVY8LsIHRpzIrUQ1YkKegQILBAB..i&cs=0&um=1&ie=UTF-8&fb=1&gl=ae&sa=X&geocode=KWHVBYTj6PtvMezQZ8Rms45v&daddr=Walk+building,+16+-+Dubai",
    logo: "/images/partners/bodymind.png",
    theme: "purple"
  }
];
