import { Partner } from '@/types/partner';

export const partnersData: Partner[] = [
  {
    id: "persona-marina",
    name: "UNIQUE PERSONA, DUBAI MARINA",
    type: "Beauty & Aesthetic Center",
    description: "Professional beauty salon offering comprehensive skincare and aesthetic services in Dubai Marina",
    location: "The Residences at Marina Gate 1, Dubai Marina",
    phone: "+971 52 948 1238",
    website: "https://persona-dubai.com/eng",
    directions: "https://www.google.com/maps/dir//The+Residences+at+Marina+Gate+1+-+Dubai+-+%D0%9E%D0%90%D0%AD/@25.086284,55.1398907,14.76z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3e5f6bdd6fb9a655:0x9d88db1312e9d2e3!2m2!1d55.147257!2d25.0862329?entry=ttu&g_ep=EgoyMDI1MTAyMi4wIKXMDSoASAFQAw%3D%3D",
    logo: "/images/partners/Persona.png",
    theme: "pink"
  },
  {
    id: "persona-palm",
    name: "UNIQUE PERSONA, PALM JUMEIRAH",
    type: "Beauty & Aesthetic Center",
    description: "Second location of professional beauty salon offering comprehensive skincare and aesthetic services in Palm Jumeirah",
    location: "LG floor, Nakheel Mall - Palm Jumeirah, Dubai",
    phone: "+971 52 723 6572",
    website: "https://persona-dubai.com/palm",
    directions: "https://www.google.com/maps?sca_esv=254941356981cfe9&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifNZ5hzw_WMOirnwpcghXVhwM3hBJw:1761383254480&gs_lp=Egxnd3Mtd2l6LXNlcnAiCnBlcnNvbmEgbmEqAggAMgoQIxiABBgnGIoFMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBSOURUIEBWL0IcAF4AZABAJgBhwGgAYMHqgEDMC43uAEDyAEA-AEBmAIIoAK5B8ICChAAGLADGNYEGEfCAgYQABgWGB7CAggQLhiABBjLAcICCxAuGIAEGNQCGMsBmAMAiAYBkAYIkgcDMS43oAf_O7IHAzAuN7gHuAfCBwUwLjEuN8gHKQ&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KT9ts0Vza18-MV2OH9RxvODz&daddr=LG+floor,+Nakheel+Mall+-+Nakhlat+Jumeira+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/Persona.png",
    theme: "pink"
  },
  {
    id: "persona-downtown",
    name: "UNIQUE PERSONA, DOWNTOWN",
    type: "Beauty & Aesthetic Center",
    description: "Third location of professional beauty salon offering comprehensive skincare and aesthetic services in Downtown Dubai",
    location: "Downtown Dubai - South Ridge, Dubai",
    phone: "+971 58 298 0622",
    website: "https://persona-dubai.com/downtown",
    directions: "https://www.google.com/maps?sca_esv=254941356981cfe9&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifMcvEfeB5vjDCsZXY1dxYn3F-03KA:1761385503810&uact=5&gs_lp=Egxnd3Mtd2l6LXNlcnAiIFVOSVFVRSBQRVJTT05BIHNvdXRoIHJpZGdlIHRvd2VyMgcQIRigARgKMgcQIRigARgKMgcQIRigARgKSM0lUFBY6iRwAXgBkAEAmAHbAqAB6BOqAQgwLjE2LjAuMbgBA8gBAPgBAZgCEqACxxTCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICDhAuGIAEGMcBGMsBGK8BwgIIEAAYgAQYywHCAgUQABiABMICCxAuGIAEGMcBGK8BwgIIEAAYFhgKGB7CAgYQABgWGB7CAh0QLhiABBjHARjLARivARiXBRjcBBjeBBjgBNgBAcICBxAAGIAEGA3CAg0QLhiABBjHARgNGK8BwgIFECEYoAHCAgQQIRgVwgIFECEYnwWYAwCIBgGQBgm6BgYIARABGBSSBwgxLjE2LjAuMaAHykOyBwgwLjE2LjAuMbgHxRTCBwYwLjE1LjPIBy4&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KQEgvFUnaV8-MW_iFs8DwPSX&daddr=Downtown+Dubai+-+South+Ridge+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/Persona.png",
    theme: "pink"
  },
  {
    id: "faceroom",
    name: "FACE ROOM, DUBAI MARINA",
    type: "Facial Care & Massage Studio",
    description: "Professional facial massage and cosmetology services with unique techniques for skin care and relaxation",
    location: "The Residences at Marina Gate 2, Dubai Marina",
    phone: "+971 52 829 0457",
    website: "https://face-rooms.com",
    directions: "https://www.google.com/maps/search/The+Residences+at+Marina+Gate+2+Dubai+Marina",
    logo: "/images/partners/logo-faceroom.png",
    theme: "blue"
  },
  {
    id: "evolution",
    name: "EVOLUTION AESTHETICS CLINIC, JUMEIRAH 3",
    type: "Aesthetic Medical Clinic",
    description: "Elevating aesthetics standards with comprehensive aesthetic cosmetology, gynecology, injectables, and advanced beauty treatments",
    location: "49 Umm Al Sheif Rd - Jumeira Third - Jumeirah 3 - Dubai",
    phone: "+971 4 706 5000",
    website: "https://evoclinic.ae",
    directions: "https://www.google.com/maps?rlz=1C5CHFA_enAE820AE820&gs_lcrp=EgZjaHJvbWUyCQgAEEUYORiABDIHCAEQABjvBTIKCAIQABiABBiiBDIKCAMQABiABBiiBDIHCAQQABjvBdIBCDU5NjRqMGo3qAIAsAIA&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KZmTgf_la18-MRupdQ8rSJ36&daddr=49+Umm+Al+Sheif+Rd+-+Jumeira+Third+-+Jumeirah+3+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/evo.png",
    theme: "purple"
  },
  {
    id: "shakirovna",
    name: "SHAKIROVNA LADIES BEAUTY SALOON, DUBAI MARINA",
    type: "Ladies Beauty Salon",
    description: "Professional beauty services for women with expert care and attention to detail in Jumeirah Beach Residence",
    location: "Jumeirah Beach Residence 2, Marina Wharf 1",
    phone: "+971 50 409 9407",
    website: "https://shakirovna.com",
    directions: "https://www.google.com/maps?rlz=1C5CHFA_enAE820AE820&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KS37CzxUE18-MV_-F9n4c6n1&daddr=Marina+Promenade+-+Marsa+Dubai+-+Dubai+Marina+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/Shakirovna.png",
    theme: "purple"
  },
  {
    id: "shakirovna-business-bay",
    name: "ELITE SHAKIROVNA BEAUTY CENTER, BUSINESS BAY",
    type: "Elite Beauty Center",
    description: "Premium beauty center offering comprehensive beauty services including hair, eyelashes, cosmetology, massage therapy, and specialized treatments in Business Bay",
    location: "One by Omniyat, Business Bay, Dubai",
    phone: "+971 58 875 9719",
    website: "https://shakirovna.com/bb",
    directions: "https://www.google.com/maps/search/One+by+Omniyat+Business+Bay+Dubai",
    logo: "/images/partners/Shakirovna.png",
    theme: "purple"
  },
      {
        id: "face-only",
        name: "THE FACE ONLY, BLUEWATERS ISLAND",
        type: "Specialized Facial Treatment Salon",
    description: "Professional facial treatment salon specializing in signature TFO massage, skin therapy, and advanced facial treatments with focus on natural beauty and effective results",
    location: "Blue Waves Residence - 9 A Street - Marsa Dubai, Dubai",
    phone: "+971 54 348 8117",
    website: "https://thefaceonly.com",
    directions: "https://www.google.com/maps?sca_esv=254941356981cfe9&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifPF4L5bN-vsNASbTGi2iDyOGwbNcQ:1761385666402&uact=5&gs_lp=Egxnd3Mtd2l6LXNlcnAiFWZhY2Ugb25seSBzYWxvbiBkdWJhaTIFECEYoAEyBRAhGKABMgUQIRigATIFECEYnwUyBRAhGJ8FMgUQIRifBTIFECEYnwUyBRAhGJ8FMgUQIRifBTIFECEYnwVIkB9QmghYnx1wAngBkAEAmAGYAaAB9AmqAQQwLjEwuAEDyAEA-AEBmAIMoAK4CsICChAAGLADGNYEGEfCAgQQIxgnwgIIEAAYBRgNGB7CAgUQABjvBcICCBAAGIAEGKIEwgIIEAAYCBgNGB7CAgYQABgWGB7CAgQQIRgVwgIHECEYoAEYCpgDAIgGAZAGCJIHBDIuMTCgB8gvsgcEMC4xMLgHsgrCBwUwLjQuOMgHJw&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KQG0tOpTFV8-Maa3vu0wEN-S&daddr=Blue+Waves+Residence+-+9+A+Street+-+Marsa+Dubai+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/thefaceonly.png",
    theme: "blue"
  },
  {
    id: "egoistka",
    name: "EGOISTKA BEAUTY SALON, DUBAI MARINA",
    type: "Comprehensive Beauty Salon",
    description: "Professional beauty salon offering comprehensive beauty services including manicure, pedicure, podiatry, eyebrow and eyelash services, hair treatments, cosmetology, massage, and advanced beauty treatments in Dubai Marina",
    location: "Dubai Marina Promenade, Delphine Tower, Ground Floor, Shop 2",
    phone: "+971 58 558 4002",
    website: "https://davaidubai.ae/en/my-daily-life-in-dubai/beauty-and-self-care/egoistka-beauty-salon",
    directions: "https://www.google.com/maps?sca_esv=254941356981cfe9&biw=1554&bih=862&sxsrf=AE3TifMsU4ygFJB7jBNdHE1kZZkhtC-Q7g:1761386513035&uact=5&gs_lp=Egxnd3Mtd2l6LXNlcnAiH2Vnb2lzdGthIGJlYXV0eSBzYWxvbiBkdWJhaSBtYXAyCBAhGKABGMMESOAPUPwIWOsNcAJ4AJABAJgBpQGgAbUGqgEDMC42uAEDyAEA-AEBmAIFoAK4A8ICCBAAGLADGO8FwgILEAAYgAQYsAMYogTCAgoQIRigARjDBBgKmAMAiAYBkAYFkgcDMi4zoAeuFLIHAzAuM7gHtQPCBwMwLjXIBwg&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KXdgif0DE18-MaAmDFkVt05k&daddr=Marina+Promenade,+Delphine+Tower,+Shop+No+2+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/Egoistka.png",
    theme: "purple"
  },
  {
    id: "vesna",
    name: "VESNA BEAUTY LOUNGE, DUBAI MARINA",
    type: "Beauty Lounge",
    description: "Professional beauty lounge offering comprehensive beauty services and treatments in Dubai Marina",
    location: "The Zen - Al Seba St - Marsa Dubai - Dubai Marina, Dubai",
    phone: "+971 55 341 1859",
    directions: "https://www.google.com/maps/dir//The+Zen+-+Al+Seba+St+-+Marsa+Dubai+-+Dubai+Marina+-+Dubai+-+%D0%9E%D0%90%D0%AD/@25.0675537,55.0485508,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3e5f13045e9c3d51:0x33cac3f11886f661!2m2!1d55.1309523!2d25.0675764?entry=ttu&g_ep=EgoyMDI1MTAyMi4wIKXMDSoASAFQAw%3D%3D",
    logo: "/images/partners/Vesna.png",
    theme: "pink"
  },
  {
    id: "kindcare",
    name: "KINDCARE MEDICAL CENTER, JUMEIRAH",
    type: "Multispeciality Medical Center",
    description: "Integrative multispeciality healthcare provider offering comprehensive medical services including family medicine, dermatology, plastic surgery, and specialized treatments in Jumeirah",
    location: "Villa number 794 - Jumeira St - Umm Suqeim Second - Jumeirah 3 - Dubai",
    phone: "+971 4 338 8588",
    website: "https://kindcare.ae",
    directions: "https://www.google.com/maps?rlz=1C5CHFA_enAE820AE820&gs_lcrp=EgZjaHJvbWUqCggAEAAY4wIYgAQyCggAEAAY4wIYgAQyDQgBEC4YrwEYxwEYgAQyCQgCEAAYChiABDIHCAMQABiABDIICAQQABgWGB4yCAgFEAAYFhgeMggIBhAAGBYYHjIICAcQABgWGB4yCAgIEAAYFhgeMggICRAAGBYYHtIBCDIxNzRqMGo3qAIAsAIA&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KcMzGY5QQl8-MYaoJDpzrhyP&daddr=Villa+number+794+-+Jumeira+St+-+Umm+Suqeim+Second+-+Jumeirah+3+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/KIND.png",
    theme: "emerald"
  },
  {
    id: "hortman-1",
    name: "HORTMAN CLINICS, BUSINESS BAY",
    type: "Premium Aesthetic Clinic",
    description: "Renowned aesthetic clinic specializing in cosmetic surgeries, dermatology, anti-aging treatments, and wellness services",
    location: "32 Floor - 1 Sheikh Zayed Rd - Trade Center First - Dubai",
    phone: "+971 4 566 2615",
    website: "https://hortmanclinics.com",
    directions: "https://www.google.com/maps?sca_esv=254941356981cfe9&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifPTZte0PBmw_HTgKUi-In8WvlDkGQ:1761382021983&uact=5&gs_lp=Egxnd3Mtd2l6LXNlcnAiEGhvcnRtYW4gY2xpbmljcyAyEBAuGIAEGMcBGCcYigUYrwEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMgYQABgWGB4yBRAAGO8FMgUQABjvBTIdEC4YgAQYxwEYigUYrwEYlwUY3AQY3gQY4ATYAQFI7wRQCFiEAnABeACQAQCYAW-gAcwCqgEDMC4zuAEDyAEA-AEBmAIIoAK5B8ICDRAuGLADGMcBGCcYrwHCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICBRAAGIAEmAMAiAYBkAYKugYGCAEQARgUkgcDMS4yoAe7H7IHAzAuMrgH6AHCBwUwLjEuMsgHCg&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KSEXfIP9Q18-MRkmpM9ul2lD&daddr=32+Floor+-+1+Sheikh+Zayed+Rd+-+Trade+Center+First+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/hortman.png",
    theme: "emerald"
  },
  {
    id: "hortman-2",
    name: "HORTMAN CLINICS 2, JUMEIRAH 3",
    type: "Premium Aesthetic Clinic",
    description: "Second location of renowned aesthetic clinic specializing in cosmetic surgeries, dermatology, and wellness services",
    location: "450 Jumeira St - Jumeirah - Jumeirah 3 - Dubai",
    phone: "+971 52 200 5011",
    website: "https://hortmanclinics.com/contact",
    directions: "https://www.google.com/maps?sca_esv=254941356981cfe9&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifNdK-nhSVi0UM_BIxnB3Rm8KYCyPg:1761382025361&uact=5&gs_lp=Egxnd3Mtd2l6LXNlcnAiEWhvcnRtYW4gY2xpbmljcyAyMhAQLhiABBjHARgnGIoFGK8BMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMgYQABgWGB4yBRAAGO8FMgUQABjvBTIdEC4YgAQYxwEYigUYrwEYlwUY3AQY3gQY4ATYAQFI7wRQCFiEAnABeACQAQCYAW-gAcwCqgEDMC4zuAEDyAEA-AEBmAIIoAK5B8ICDRAuGLADGMcBGCcYrwHCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICBRAAGIAEmAMAiAYBkAYKugYGCAEQARgUkgcDMS4yoAe7H7IHAzAuMrgH6AHCBwUwLjEuMsgHCg&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KWNJRzEAQ18-MZtAmPB8BfjS&daddr=450+Jumeira+St+-+Jumeirah+-+Jumeirah+3+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/hortman.png",
    theme: "emerald"
  },
  {
    id: "lfk-clinic",
    name: "LFK CLINIC, BUSINESS BAY",
    type: "Luxury Aesthetic Clinic",
    description: "Award-winning luxury aesthetic clinic specializing in Russian Lips technique, Hollywood Face, and advanced cosmetic procedures with expert care from leading Russian specialists",
    location: "Al Saqr Business Tower, 11th floor, DIFC, Dubai",
    phone: "+971 54 233 6281",
    website: "https://lipsforkiss.com/dubai_clinic",
    directions: "https://www.google.com/maps/dir//Al+Saqr+Business+Tower+-+Trade+Center+Second+-+DIFC+-+Dubai+-+%D0%9E%D0%90%D0%AD/@25.2139349,55.1956632,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3e5f439c6c9f96a5:0x7ac63fa8a8735ce!2m2!1d55.2780647!2d25.2139577?entry=ttu&g_ep=EgoyMDI1MTAyMi4wIKXMDSoASAFQAw%3D%3D",
    logo: "/images/partners/kiss.png",
    theme: "purple"
  },
  {
    id: "elaris",
    name: "ELARIS BEAUTY SALON, BUSINESS BAY",
    type: "Luxury Beauty Salon",
    description: "Dubai's newest and most ambitious Beauty City offering luxury beauty services, expert stylists, and comprehensive beauty treatments in Business Bay",
    location: "Business Bay, Maison Prive, Shop #3 & 4 - Dubai",
    phone: "+971 58 697 1090",
    website: "https://elarisalon.com",
    directions: "https://www.google.com/maps/dir/28.2295568,-16.8407006/Elaris+Beauty+Salon+-+Business+Bay,+Maison+Prive,+Shop+%233+%26+4+-+Dubai+-+%D0%9E%D0%90%D0%AD/@33.1022972,-2.0987042,4z/data=!4m9!4m8!1m1!4e1!1m5!1m1!1s0x89af6d6aa285182f:0xfb3c239d4e636169!2m2!1d55.2751612!2d25.1846245?entry=ttu&g_ep=EgoyMDI1MTAyMi4wIKXMDSoASAFQAw%3D%3D",
    logo: "/images/partners/elaris.png",
    theme: "pink"
  },
  {
    id: "milyne",
    name: "MILYNE AESTHETIC CENTER, DUBAI CREEK HARBOUR",
    type: "Aesthetic Medical Center",
    description: "Your one-stop beauty solution offering Morpheus8, Forma, Hydrafacial, Fillers, Skin Boosters, Endospheres, Body Treatments, Professional Skin Care, Mesojet and many more advanced treatments",
    location: "Dubai Creek Residences - Ground Floor - Al Kheeran First - Dubai Creek Harbour - Dubai",
    phone: "+971 52 117 9436",
    website: "https://milyne.ae",
    directions: "https://www.google.com/maps?rlz=1C5CHFA_enAE820AE820&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIJCAEQABgTGIAEMgcIAhAAGO8FMgcIAxAAGO8FMgcIBBAAGO8FMgcIBRAAGO8FMgcIBhAAGO8F0gEIMzY2NWowajmoAgawAgHxBSFPW0ktbJMd&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KQHeW0f2_02CMXP3qlhiZjlO&daddr=Dubai+Creek+Residences+-+Ground+Floor+-+Al+Kheeran+First+-+Dubai+Creek+Harbour+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/milyne.png",
    theme: "emerald"
  },
  {
    id: "hideaway",
    name: "THE HIDEAWAY FOR WOMEN SALON, JUMEIRAH 3",
    type: "Hair & Beauty Salon",
    description: "Family owned and run hair and beauty salon established in 2021",
    location: "La Plage Shop 6 - 403 jumeirah Street - Al Athar Street - Dubai",
    phone: "+971 4 591 8879",
    website: "https://thehideaway.ae",
    directions: "https://www.google.com/maps?sca_esv=408005786895665f&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifOwLEVh0KaiO4iVJsSIlFTBM1SLxw:1761426054574&uact=5&gs_lp=Egxnd3Mtd2l6LXNlcnAiIXRoZSBoaWRld2F5IGZvciB3b21lbiBzYWxvbiBkdWJhaTIGEAAYFhgeMgUQABjvBTIFEAAY7wUyBRAAGO8FMggQABiABBiiBEi2CFBqWOUGcAF4AJABAJgBkwGgAfIFqgEDMi41uAEDyAEA-AEBmAIHoAK6BcICChAAGLADGNYEGEeYAwDiAwUSATEgQIgGAZAGB5IHAzIuNaAH5ByyBwMxLjW4B7cFwgcFMC42LjHIBw8&um=1&ie=UTF-8&fb=1&gl=es&sa=X&geocode=KY-K7sUuQ18-MZ8GtMbLO0UX&daddr=La+Plage+Shop+6+-+403+jumeirah+Street+-+Al+Athar+Street+-+Dubai+-+%D0%9E%D0%90%D0%AD",
    logo: "/images/partners/hideaway.png",
    theme: "pink"
  },
  {
    id: "skinstory",
    name: "SKIN STORY DUBAI",
    type: "Korean Skincare Online Store",
    description: "Renowned Korean skincare online store offering an extensive collection of authentic Korean skincare products including GENOSYS products",
    location: "Online Store - UAE Wide Delivery",
    phone: "+971 58 509 2199",
    website: "https://skinstorydubai.com",
    logo: "/images/partners/skinstory.png",
    theme: "blue"
  },
  {
    id: "melanta",
    name: "MELANTA AESTHETIC MEDICAL CLINIC",
    type: "Medical Aesthetic Clinic",
    description: "Professional medical aesthetic clinic offering advanced cosmetic treatments and skincare solutions in Jumeirah 3",
    location: "748A Al Wasl Rd - Jumeirah - Jumeirah 3 - Dubai",
    phone: "+971 50 577 3043",
    website: "https://clinicamelanta.com",
    directions: "https://www.google.com/maps?sca_esv=5f8ad457132af750&rlz=1C5CHFA_enAE820AE820&sxsrf=AE3TifOw07ZH8BqJw7gWtf_Tq1KX9XyhAQ:1761576218126&gs_lp=Egxnd3Mtd2l6LXNlcnAiB21lbGFudGEqAggAMg4QLhiABBjHARjLARivATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyDhAuGIAEGMcBGMsBGK8BMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIdEC4YgAQYxwEYywEYrwEYlwUY3AQY3gQY4ATYAQFI3B1QxQdYlRNwAXgBkAEAmAGyAqABlQ-qAQUyLTQuM7gBA8gBAPgBAZgCCaACohnCAgoQABiwAxjWBBhHwgIEECMYJ8ICChAAGIAEGEMYigXCAgsQLhiABBjHARivAcICCxAuGIAEGNEDGMcBwgIFEAAYgATCAhAQLhiABBjHARgnGIoFGK8BwgIKECMYgAQYJxiKBcICChAAGIAEGBQYhwLCAgoQLhiABBhDGIoFwgIFEC4YgATCAhQQLhiABBjHARiYBRiZBRieBRivAcICGRAuGIAEGEMYigUYlwUY3AQY3gQY4ATYAQHCAggQLhiABBjLAcICGRAuGIAEGEMYigUYlwUY3AQY3gQY3wTYAQHCAgoQABiABBgKGMsBmAMA4gMFEgExIECIBgGQBgi6BgYIARABGBSSBwsxLjAuNC4zLjctMaAH4oQBsgcFMi00LjO4B9APwgcHMC4xLjcuMcgHMw&um=1&ie=UTF-8&fb=1&gl=ae&sa=X&geocode=KU83fM2taV8-McWNMxayfSN1&daddr=748A+Al+Wasl+Rd+-+Jumeirah+-+Jumeirah+3+-+Dubai",
    logo: "/images/partners/melanta.png",
    theme: "purple"
  },
  {
    id: "sugar-wax",
    name: "SUGAR & WAX BEAUTY SALON, DUBAI MARINA",
    type: "Beauty Salon",
    description: "Professional beauty salon offering comprehensive beauty services including waxing, skincare, and beauty treatments in Dubai Marina",
    location: "Dubai Marina, Al Sayorah Street, Marina Wharf 2, Basement 2, Shop 4, Dubai, United Arab Emirates",
    phone: "050 829 8727",
    website: "https://sugarwaxuae.com/",
    directions: "https://www.google.com/maps?s=web&rlz=1C5CHFA_enAE820AE820&lqi=ChhTdWdhciAmIFdheCBCZWF1dHkgU2Fsb25I4ab8ouS5gIAIWjIQABABEAIQAxAEGAAYARgCGAMYBCIYc3VnYXIgJiB3YXggYmVhdXR5IHNhbG9uMgJlbpIBDGJlYXV0eV9zYWxvbpoBI0NoWkRTVWhOTUc5blMwVkpRMEZuU1VRMWQyOHlUMXBCRUFFqgFbCg0vZy8xMXR0MjV6NHcxCgkvbS8wNTY5emcQATIfEAEiG8Qe-29yMbEvFvLrjWSxk0yGKJNoCT_02R8m1TIcEAIiGHN1Z2FyICYgd2F4IGJlYXV0eSBzYWxvbvoBBAhQEEo&phdesc=5KxfX1gGpUU&vet=12ahUKEwixyYPZqMmQAxU5ExAIHYKcIpAQ1YkKegQIJhAB..i&cs=0&um=1&ie=UTF-8&fb=1&gl=ae&sa=X&geocode=KWc5mCujE18-MYBdpj0RmzXd&daddr=Marina+Warf+2+-+Dubai",
    logo: "/images/partners/wax.png",
    theme: "pink"
  }
];
