import { Product } from '@/types'

export const products: Product[] = [
  {
    id: '1',
    name: 'Microneedle Roller',
    price: 230,
    description: 'Skin stimulator to promote collagen production and transdermal nutrient delivery. Professional microneedling device for effective skin regeneration. Manufactured in South Korea.',
    image: '/images/genosys-microneedling-devices.jpg',
    category: 'Microneedling',
    inStock: true,
  },
  {
    id: '2',
    name: 'Needle Pen-K',
    price: 1450,
    description: 'Skin stimulator to promote collagen production and transdermal nutrient delivery. GENOSYS NEEDLE PEN-K is an automatic device for microneedling therapy. It increases the absorption rate of active ingredients of skin care products by creating physical pathways through skin. And it promotes collagen and elastin induction through natural wound healing process of skin. Manufactured in South Korea.',
    image: '/images/Needle-pen.jpg',
    category: 'Microneedling',
    inStock: true,
  },
  {
    id: '3',
    name: 'HairGen BOOSTER',
    price: 1800,
    description: 'Auto-microneedling LED device for scalp treatment. HR³ MATRIX HAIR SOLUTION α - It is the premium anti-hair loss product supplying nutrients that fight against the factors causing hair loss. HR³ MATRIX HAIR STAMP - Patented delivery enhancer with microneedles leads to scalp regeneration and collagen production by promoting natural wound healing process of skin and increases skin permeability of nutritive ingredients. Manufactured in South Korea.',
    image: '/images/Booster.jpg',
    category: 'Device',
    inStock: true,
  },
  {
    id: '4',
    name: 'POWER SOLUTION HES',
    price: 580,
    description: '2ml x 10ea. Hydrating and firming ampoule for microneedling treatment. Dermatologically tested. Efficacy test on skin hydration. Features: It is a hydrating and firming ampoule specially formulated for microneedling treatment that provides long-lasting moisturizing and plumping effects, and relieves skin irritation with sh-polypeptide-7 (human growth hormone-like peptide), hyaluronic acid and BIOPHYTEX™. Key Ingredients: Hyaluronic Acid, Panthenol, Phytosphingosine, BIOPHYTEX™, Copper Tripeptide-1, sh-Polypeptide-7, Palmitoyl Tetrapeptide-7. Manufactured in South Korea.',
    image: '/images/HES.jpg',
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '5',
    name: 'POWER SOLUTION CVS',
    price: 580,
    description: '2ml x 10ea. Skin revitalizing ampoule for microneedling treatment. Dermatologically tested. Efficacy test on moisturizing. Features: It is a skin revitalizing ampoule specially formulated for microneedling treatment that supplies nutrients to the skin, soothes and hydrates skin with sh-polypeptide-7 (human growth hormone-like peptide), botanical stem cell extracts and panthenol. Skin-Friendly Formulation: Not containing harmful additives considering the increased skin permeability by microneedling (no-paraben, ethanol, artificial fragrance, artificial pigment, sulfate). Dermatologically tested. Key Ingredients: sh-polypeptide-7, Palmitoyl Tripeptide-1, Lactobacillus/Soymilk Ferment Filtrate, Panthenol, Allantoin, Hyaluronic Acid, Vitis Vinifera (Grape) Callus Culture Extract, Rosa Damascena Callus Culture Extract, Lactobacillus Ferment Lysate Filtrate. Manufactured in South Korea.',
    image: '/images/CVS.jpg',
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '6',
    name: 'POWER SOLUTION CTS',
    price: 580,
    description: '2ml x 10ea. Skin remodeling ampoule for microneedling treatment. Dermatologically tested. Features: It is a skin remodeling ampoule specially formulated for microneedling treatment that helps the skin retain its natural elasticity and increases the strength of skin with sh-polypeptide-7 (human growth hormone-like peptide), copper tripeptide-1, hyaluronic acid and collagen. Skin-Friendly Formulation: Not containing harmful additives considering the increased skin permeability by microneedling (no-paraben, ethanol, artificial fragrance, artificial pigment, sulfate). Dermatologically tested. Key Ingredients: sh-polypeptide-7, Collagen, Hyaluronic Acid, Palmitoyl Tripeptide-1, Vitis Vinifera (Grape) Callus Culture Extract, Rosa Damascena Callus Culture Extract, Copper Tripeptide-1, Palmitoyl Hexapeptide-12. Manufactured in South Korea.',
    image: '/images/CTS.jpg',
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '7',
    name: 'POWER SOLUTION PCS',
    price: 580,
    description: '2ml x 10ea. Anti-blemish ampoule for microneedling treatment. Dermatologically tested. Efficacy test on improving excessive sebum production. Features: It is an anti-blemish ampoule specially formulated for microneedling treatment that controls excessive oil and sebum production and helps prevent skin breakout with sh-polypeptide-7 (human growth hormone-like peptide), with hazel leaf extract and houttuynia cordata extract. Skin-Friendly Formulation: Not containing harmful additives considering the increased skin permeability by microneedling (no-paraben, ethanol, artificial fragrance, artificial pigment, sulfate). Key Ingredients: sh-Polypeptide-7, Acetyl Hexapeptide-8, Palmitoyl Hexapeptide-12, Palmitoyl Tripeptide-1, Hamamelis Virginiana (Witch Hazel) Leaf Extract, Vitis Vinifera (Grape) Callus Culture Extract, Rosa Damascena Callus Culture Extract, Pinus Radiata Bark Extract, Houttuynia Cordata Extract. Manufactured in South Korea.',
    image: '/images/PCS.jpg',
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '8',
    name: 'POWER SOLUTION SWS',
    price: 580,
    description: '2ml x 10ea. Anti-pigment ampoule for microneedling treatment. Dermatologically tested. Efficacy test on improving hyperpigmentation. Features: It is an anti-pigment ampoule specially formulated for microneedling treatment that helps improve pigmentation, even skin tone and brighten the skin surface with sh-polypeptide-7 (human growth hormone-like peptide), arbutin and kojic acid. Skin-Friendly Formulation: Not containing harmful additives considering the increased skin permeability by microneedling (no-paraben, ethanol, artificial fragrance, artificial pigment, sulfate). Key Ingredients: sh-Polypeptide-7, Arbutin, Glycyrrhiza Uralensis (Licorice) Root Extract, Kojic Acid, Vitis Vinifera (Grape) Callus Culture Extract, Rosa Damascena Callus Culture Extract, Palmitoyl Tripeptide-1, Aspergillus/Saccharomyces/Glycyrrhiza Uralensis Root Extract Ferment Filtrate. Manufactured in South Korea.',
    image: '/images/SWS.jpg',
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '9',
    name: 'POWER SOLUTION AWS',
    price: 580,
    description: '2ml x 10ea. Anti-aging ampoule for microneedling treatment. Dermatologically tested. Efficacy test on improving wrinkles. Features: It is an anti-aging ampoule specially formulated for microneedling treatment that helps reduce the appearance of wrinkles and improve skin firmness with sh-polypeptide-7 (human growth hormone-like peptide), firming peptide complex and adenosine. Skin-Friendly Formulation: Not containing harmful additives considering the increased skin permeability by microneedling (no-paraben, ethanol, artificial fragrance, artificial pigment, sulfate). Key Ingredients: sh-polypeptide-7, Acetyl Hexapeptide-8, Palmitoyl Tripeptide-1, Ceramide, Allantoin, Adenosine, Vitis Vinifera (Grape) Callus Culture Extract, Rosa Damascena Callus Culture Extract, Copper Tripeptide-1. Manufactured in South Korea.',
    image: '/images/AWS.jpg',
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '10',
    name: 'SNOW O₂',
    price: 330,
    description: '180ml (Homecare) / 500ml (Professional). All in one gentle cleanser with oxygen bubbles. It is a gentle and effective cleanser which gives an excellent treatment sensation. Naturally generated oxygen bubbles clean make-up dirts and skin impurities without excessive cleansing movement and irritation to skin. Features oxygen therapy mechanism for deep cleansing and nutrifying. Key ingredients: Phytolex SC, MultiEx Phytrogen, Methyl Perfluoroisobutyl Ether. Apply the product to a dry face, avoiding the eyes, and wait for oxygen bubbles to come up. Wet your fingers to spread the product and let bubbles form again. After they fully develop, massage gently with wet hands, then rinse with lukewarm water. Dermatologically tested.',
    image: '/images/SNOW.jpg',
    category: 'Cleanser',
    inStock: true,
  },
  {
    id: '11',
    name: 'SKIN DEFENDER LIP & EYE MAKEUP REMOVER',
    price: 290,
    description: '200ml. Fresh, non-greasy lip & eye makeup remover. It is a fresh, non-greasy lip & eye makeup remover. Biphasic layer of essence layer with vitamins, firming peptides and oil layer with a strong cleansing power turn into emulsion which cleans the delicate lip and eye area without irritation. Key ingredients: 10 Vitamin Complex, Palmitoyl Tripeptide-5, Acetyl Tetrapeptide-5, Saccharide Hydrolysate, Rosa Damascena Flower Water, Daucus Carota Sativa (Carrot) Root Extract, Brassica Oleracea Italica (Broccoli) Extract, Daucus Carota Sativa (Carrot) Seed Oil, Hippophae Rhamnoides Oil. Usage: Shake well before use. Dermatologically tested.',
    image: '/images/DEF.jpg',
    category: 'Cleanser',
    inStock: true,
  },
  {
    id: '12',
    name: 'EPI TURNOVER BOOSTING PEELING GEL',
    price: 250,
    description: '100g. Mild peeling gel combining enzymatic peeling and cellulose peeling. It is the enzyme peeling gel that removes dead skin cells without irritation. Moringa, so-called "Miracle Tree" purifies and nourishes skin and the plant complex from desert moisturizes and soothes skin. Key ingredients: Carica Papaya (Papaya) Fruit Extract, Moringa Pterygosperma Seed Extract, Hyaluronic Acid, Simmondsia Chinensis (Jojoba) Seed Oil, Desert Complex. Dermatologically tested.',
    image: '/images/EPI.jpg',
    category: 'Peeling',
    inStock: true,
  },
  {
    id: '13',
    name: 'SKIN RENEWAL PEELING SYSTEM (SRS)',
    price: 810,
    description: '2ml x 10ea. Professional peeling with naturally occurring AHA acids. It is a professional peeling system for smoother, brighter and more even skin tone. Naturally occurring acids found in fruits and other foods help remove dead cells on the surface of the skin, encouraging cell turnover and bringing new healthy cells to the surface. Key ingredients: Naturally occurring AHA complex (Glycolic Acid, Lactic Acid, Mandelic Acid, Phytic Acid), sh-Polypeptide-7, Scutellaria Baicalensis Root Extract, Houttuynia Cordata Extract, Chamaecyparis Obtusa Water. Dermatologically tested.',
    image: '/images/SRS.jpg',
    category: 'Peeling',
    inStock: true,
  },
  {
    id: '14',
    name: 'MICROBIOME ENERGY INFUSING MIST',
    price: 160,
    description: '80ml. Revitalizing mist that gives skin natural glow and radiance. It revitalizes skin and enhances skin\'s natural strength with unique blend of pre/probiotics that corrects the balance of skin microbiome and hyaluronic acid complex that replenishes the skin\'s moisture barrier. Key ingredients: CUREBIOME (Probiotics & Prebiotics), FENSEBIOME™ (Acetyl Heptapeptide-4), Hyaluronan 10 Multi-Complex, Butyrospermum Parkii (Shea) Butter. Dermatologically tested. Efficacy test on skin hydration.',
    image: '/images/mist.jpg',
    category: 'Toner/Mist',
    inStock: true,
  },
  {
    id: '15',
    name: 'INTENSIVE PROBLEM CONTROL TONER',
    price: 130,
    description: '200ml (Homecare) / 500ml (Professional). Anti-blemish toner for acne-prone skin. It helps remove excess oil and sebum for blemish-prone skin while adding quick hydration to skin with patented Anti Sebum P complex, zinc PCA, tea tree extract and panthenol. Key ingredients: Anti Sebum P, Tea Tree Extract, Tea Tree Leaf Oil, Rosmarinus Officinalis (Rosemary) Leaf Extract, Zinc PCA, Tannic Acid, Salicylic Acid (BHA), SNOW ICE. Dermatologically tested. Efficacy test on improving excessive sebum production.',
    image: '/images/PRS.jpg',
    category: 'Toner/Mist',
    inStock: true,
  },
  {
    id: '16',
    name: 'SNOW BOOSTER',
    price: 130,
    description: '200ml (Homecare) / 1000ml (Professional). Daily moisturizing and skin refining toner for all skin types. It is a daily toner used for all skin types that contains various botanical extracts to moisturize and soothe skin. It helps refining the skin with balancing pH level after cleansing. Key ingredients: Phytolex SC, Nelumbo Nucifera Flower Extract, Lactobacillus/Pumpkin Ferment Extract, Betaine. Dermatologically tested. Efficacy test on skin hydration.',
    image: '/images/BOOS.jpg',
    category: 'Toner/Mist',
    inStock: true,
  },
  {
    id: '17',
    name: 'EyeCell EYE CONTOUR SERUM',
    price: 370,
    description: '10ml. Highly enriched all-in-one eye serum. It is a highly enriched all-in-one eye serum that helps improve wrinkles, dark circles and diminish the appearance of eye puffs with peptide complex, botanical callus culture extracts and anti-dark circle complex. Key ingredients: Palmitoyl Hexapeptide-12, Copper Tripeptide-1, Acetyl Hexapeptide-8, Anti-Dark Circle Complex (Haloxyl™), Vitis Vinifera (Grape) Callus Culture Extract, Rosa Damascena Callus Culture Extract, Adenosine, Arbutin. Dermatologically tested. Efficacy test on improving wrinkles.',
    image: '/images/EYS.jpg',
    category: 'Eye care',
    inStock: true,
  },
  {
    id: '18',
    name: 'MOISTURE REPLENISHING HYALURON SERUM',
    price: 330,
    description: '30ml. Coconut water-based hydrating serum with hyaluronic complex and various mushrooms. It is a coconut water-based serum that quickly replenishes moisture from the deep inside and infuses skin with multi depth hydration with hyaluronic acid complex and various mushrooms. 4 STEP Skin Hydration: 1) Electrolytes in coconut water lead moisture into the skin and balance the water content. 2) By stimulating the formation of aqua-porin, it opens water-transport channel, and attracts moisture to the skin with moisture magnet ingredient. 3) Low/middle molecular weight hyaluronic acids replenish moisture layer by layer from the inside of the skin. 4) High molecular weight hyaluronic acid prevents moisture evaporation by forming moisture barrier on the skin surface. Mushrooms nourish and protect skin with powerful anti-inflammatory and antioxidant properties. Key ingredients: Cocos Nucifera (Coconut) Water Complex (78%), Hyaluronan 11 Multi-Complex, Glyceryl Glucoside (aquaporin), PENTAVITIN™ (moisture magnet), Tremella Fuciformis, Mushroom Complex, Solanum Melongena (Eggplant) Fruit Extract. Dermatologically tested. Efficacy test on inner hydration.',
    image: '/images/HRS.jpg',
    category: 'Serum',
    inStock: true,
  },
  {
    id: '19',
    name: 'ALL FOR SENSITIVE SERUM',
    price: 330,
    description: '30ml. Skin repairing serum for sensitive skin. It is a skin repairing serum that provides moisture barrier to skin and relieves the sensitized skin with its anti-inflammatory and soothing properties. Key ingredients: MultiEx BSASM® Plus, Phytolex SC, Hyaluronic Acid, Phytosphingosine, Aloe Barbadensis Leaf Extract, Hamamelis Virginiana (Witch Hazel) Extract, Beta-Glucan. Dermatologically tested.',
    image: '/images/ASE.jpg',
    category: 'Serum',
    inStock: true,
  },
  {
    id: '20',
    name: 'PROBLEM CONTROL SERUM',
    price: 330,
    description: '30ml. Anti-blemish serum for combination, oily acne-prone skin. It helps fight skin breakouts by regulating excessive oil and sebum and refines skin texture for a healthier-looking clear skin with a sebum regulating ingredient – zinc PCA and willow bark extract. Key ingredients: Zinc PCA, Salix Nigra (Willow) Bark Extract, Trehalose, Panthenol, Phytolex SC, Allantoin, Beta-Glucan. Dermatologically tested. Efficacy test on improving excessive sebum production.',
    image: '/images/PRSS.jpg',
    category: 'Serum',
    inStock: true,
  },
  {
    id: '21',
    name: 'MULTI VITA RADIANCE SERUM',
    price: 330,
    description: '30ml. Skin brightening serum with multi vitamins and patented melanin care complex, MELAZERO®. It helps even skin tone, revive skin\'s natural brightness and radiance with multi vitamins and patented melanin care complex, MELAZERO®. It gives skin a natural glow by forming a moisturizing barrier thanks to panthenol-rich formula. Key ingredients: 3-O-Ethyl Ascorbic Acid (derivative of pure vitamin C), VITA 12 Complex, MELAZERO®, Panthenol, Niacinamide, Glutathione, Gluconolactone (PHA), Anti-inflammatory Herb Complex. Dermatologically tested. Efficacy test on improving skin surface melanin.',
    image: '/images/RADS.jpg',
    category: 'Serum',
    inStock: true,
  },
  {
    id: '22',
    name: 'MULTI FUNCTIONAL ANTI-WRINKLE SERUM',
    price: 330,
    description: '30ml. Anti-aging serum with bakuchiol, a natural alternative to retinol and anti-wrinkle peptide complex. It is an anti-aging serum that helps visibly smooth the signs of wrinkles and reinforces skin firmness with a nourishing ingredient – bakuchiol, a natural alternative to retinol and anti-wrinkle peptide complex. Clinical study on improvement of skin age index, P&K Skin Research Center, Feb. 22 to May 13, 2024, 24 adult women aged 30~59 years. Key ingredients: Bakuchiol, Anti-aging Peptide 6, Lipid Barrier Liposome (Ceramide NP, Cholesterol, Phytosphingosine), Collagen, Elastin, Propolis Extract, Adenosine, Niacinamide. Dermatologically tested. Efficacy test on improving wrinkles and skin tone balance.',
    image: '/images/MSSS.jpg',
    category: 'Serum',
    inStock: true,
  },
  {
    id: '23',
    name: 'ND Cell ANTI-WRINKLE CREAM',
    price: 370,
    description: '50g. Anti-aging cream for neck and decollete area. It targets the special needs of the delicate skin around the neck and decollete area. It lifts and firms skin and refine the skin texture. It also has an excellent effect of depigmentation. Key ingredients: Copper Tripeptide-1, sh-polypeptide 7, Acetyl Hexapeptide-8, Palmitoyl Hexapeptide-12, Palmitoyl Tripeptide-1, Vitamin Complex (vitamin A, B5, C, E) Hyaluronic Acid, Ceramide, Squalane. Dermatologically tested. Efficacy test on improving wrinkles.',
    image: '/images/ND.jpg',
    category: 'Cream',
    inStock: true,
  },
  {
    id: '24',
    name: 'EyeCell EYE CONTOUR CREAM',
    price: 370,
    description: '20g. Daily eye cream that brings younger-looking eye contour. It is a daily cream for eye contour area that brings younger-looking eye contour by helping reduce wrinkles and dark circles and depuff the under eye with peptide complex, botanical callus culture extracts and anti-dark circle complex. Key ingredients: Palmitoyl Hexapeptide-12, Copper Tripeptide-1, Acetyl Hexapeptide-8, Anti-Dark Circle Complex (Haloxyl™), Vitis Vinifera (Grape) Callus Culture Extract, Rosa Damascena Callus Culture Extract, Adenosine, Arbutin. Dermatologically tested. Efficacy test on improving wrinkles.',
    image: '/images/EC.jpg',
    category: 'Eye care',
    inStock: true,
  },
  {
    id: '25',
    name: 'SOOTHING REPAIR POSTCREAM',
    price: 210,
    description: '20g (Homecare) / 100g (Professional). Regenerating cream for healthy skin recovery after professional treatment. It is a regenerating cream that promotes skin recovery after professional treatment. It helps irritated skin rapidly recover from redness, erythema and edema after the dermatological operations or any other irritations and promotes healthy rejuvenation. Key ingredients: sh-Polypeptide-7, Centella Complex (Asiaticoside, Madecassic Acid, Asiatic Acid), Dipotassium Glycyrrhizate, Panthenol, Vitis Vinifera (Grape) Callus Culture Extract, Rosa Damascena Callus Culture Extract, Scutellaria Baicalensis Root Extract. Dermatologically tested. Efficacy test on protection of the skin against damage induced by physical stimuli.',
    image: '/images/SRC.jpg',
    category: 'Cream',
    inStock: true,
  },
  {
    id: '26',
    name: 'EGF REPAIR OXYMASK CREAM',
    price: 290,
    description: '50g. Oxygen bubbling mask cream with skin regenerating ingredients – EGF and madecassoside. It is a unique oxygen bubbling mask cream which makes dull & stressed skin healthy with skin regenerating ingredients such as EGF and madecassoside. It is a "S.O.S" cream that can be effectively used for damaged skin by various causes. Key ingredients: sh-Oligopeptide-1 (EGF), Madecassoside, Copper Tripeptide-1, SEPITONIC M3 (Mineral Complex), Salmon Oil, Adenosine. Dermatologically tested. Efficacy test on skin soothing effect against external stimulus.',
    image: '/images/EGF.jpg',
    category: 'Cream',
    inStock: true,
  },
  {
    id: '27',
    name: 'SKIN BARRIER PROTECTING CREAM',
    price: 450,
    description: '100g. Skin barrier strengthening cream with enriched ceramide and amino acid complex. It encourages healthy and soft skin by promoting water retention and protecting skin barrier with enriched ceramide, botanical extracts and amino acid complex. Clinical Study: Skin Restorative Force Improvement. Key ingredients: Ceramide, MultiEx BSASM® Plus, Amino Acid Complex, Butyrospermum Parkii (Shea) Butter, Macadamia Integrifolia Seed Oil. Dermatologically tested. Efficacy test on improving skin restorative force.',
    image: '/images/BRR.jpg',
    category: 'Cream',
    inStock: true,
  },
  {
    id: '28',
    name: 'INTENSIVE HYDRO SOOTHING CREAM',
    price: 290,
    description: '50g (Homecare) / 250g (Professional). Soothing and moisturizing gel with aloe vera, snail secretion filtrate. It calms down skin irritation and provides long-lasting hydration to the skin with aloe vera, snail secretion filtrate and hyaluronic acid. Key ingredients: Aloe Barbadensis Leaf Extract, Snail Secretion Filtrate, Hyaluronic Acid, Lactobacillus/Pumpkin Ferment Extract, Beta-Glucan, Phytolex SC. Dermatologically tested. Efficacy test on skin hydration.',
    image: '/images/HSC.jpg',
    category: 'Cream',
    inStock: true,
  },
  {
    id: '29',
    name: 'MOISTURE REPLENISHING HYALURON CREAM',
    price: 290,
    description: '50g (Homecare) / 250g (Professional). Long-lasting moisturizer with hyaluronic complex and various mushrooms. It is a refreshing moisturizer that strengthens moisture barrier and provides long-lasting hydration to skin with hyaluronic acid complex and various mushrooms. 4 STEP Skin Hydration: 1) When it touches the skin, natural-origin cooling agents help lower the skin temperature and make skin refreshed. 2) By stimulating the formation of aqua-porin, it opens water-transport channel, and attracts moisture to the skin with moisture magnet ingredient. 3) Low/middle molecular weight hyaluronic acids replenish moisture layer by layer form the inside of the skin. 4) High molecular weight hyaluronic acid prevents moisture evaporation by forming moisture barrier on the skin surface. Mushrooms nourish and protect skin with powerful anti-inflammatory and antioxidant properties. Clinical Study: 72-Hour Hydration Persistence. Key ingredients: Hyaluronan 11 Multi-Complex, Glyceryl Glucoside (aquaporin), PENTAVITIN™ (moisture magnet), Tremella Fuciformis, Mushroom Complex, Solanum Melongena (Eggplant) Fruit Extract, Aloe Barbadensis Flower Extract, Natural-Origin Cooling Agent (Xylitol, Erythritol). Dermatologically tested. Efficacy test on 72-hour hydration persistence.',
    image: '/images/HER.jpg',
    category: 'Cream',
    inStock: true,
  },
  {
    id: '30',
    name: 'INTENSIVE PROBLEM CONTROL CREAM',
    price: 290,
    description: '50g (Homecare) / 250g (Professional). Anti-blemish cream for combination, oily acne-prone skin. It helps control blemish-prone skin by regulating excessive oil and sebum while keeping the skin hydrated with zinc PCA, xylitol and panthenol. Key ingredients: Zinc PCA, Xylitol, Trehalose, Panthenol, Phytolex SC, Allantoin, Beta-Glucan. Dermatologically tested. Efficacy test on improving excessive sebum production.',
    image: '/images/PRB.jpg',
    category: 'Cream',
    inStock: true,
  },
  {
    id: '31',
    name: 'MULTI VITA RADIANCE CREAM',
    price: 290,
    description: '50g. Skin brightening cream with multi vitamins and patented melanin care complex, MELAZERO®. It helps even skin tone, revive skin\'s natural brightness and radiance with multi vitamins and patented melanin care complex, MELAZERO®. It gives skin a natural glow by forming a moisturizing barrier thanks to panthenol-rich formula. Key ingredients: 3-O-Ethyl Ascorbic Acid (derivative of pure vitamin C), VITA 12 Complex, MELAZERO®, Panthenol, Niacinamide, Glutathione, Gluconolactone (PHA), Anti-inflammatory Herb Complex. Dermatologically tested. Efficacy test on improving skin surface melanin.',
    image: '/images/RAA.jpg',
    category: 'Cream',
    inStock: true,
  },
  {
    id: '32',
    name: 'MULTI FUNCTIONAL ANTI-WRINKLE CREAM',
    price: 290,
    description: '50g (Homecare) / 250g (Professional). Anti-aging cream with bakuchiol, a natural alternative to retinol and anti-wrinkle peptide complex. It is an anti-aging cream that helps visibly smooth the signs of wrinkles and reinforces skin firmness with a nourishing ingredient – bakuchiol, a natural alternative to retinol and anti-wrinkle peptide complex. Clinical study on improvement of skin age index, P&K Skin Research Center, Feb. 22 to May 13, 2024, 24 adult women aged 30~59 years. Key ingredients: Bakuchiol, Anti-aging Peptide 6, Lipid Barrier Liposome (Ceramide NP, Cholesterol, Phytosphingosine), Collagen, Elastin, Propolis Extract, Adenosine, Niacinamide. Dermatologically tested. Efficacy test on improving wrinkles and skin tone balance.',
    image: '/images/ANT.jpg',
    category: 'Cream',
    inStock: true,
  },
  {
    id: '33',
    name: 'EyeCell EYE PEPTIDE GEL PATCH',
    price: 380,
    description: '101g (60ea). Patented thermo-sensitive hydro gel mask for eye contour area for soothing and moisturizing. It is a patented thermo-sensitive hydrogel mask for eye contour area that soothes and moisturizes the skin that went through dermatologic procedures or natural aging. And it improves eye bags. Mechanism: It is made of temperature-sensitive hydro gel. When the patch is applied to the skin, the temperature rises due to body temperature and the hydrogel composition is changed into a fluid state, so that the adhesion to the skin is improved and the effective ingredients are rapidly delivered into the skin (transdermal cosmetic delivery system). And as skin heat is displaced by moisture from the patch, skin feels a cooling effect. Key ingredients: Acetyl Hexapeptide-8, Hydrolyzed Collagen, Made White™, Calcium Lactate, Centella Asiatica Extract, Multi 12 Complex, Adenosine, Niacinamide. Dermatologically tested. Efficacy test on moisturizing.',
    image: '/images/Patch.jpg',
    category: 'Eye care',
    inStock: true,
  },
  {
    id: '34',
    name: 'SKIN RESCUE OVERNIGHT CREAM MASK',
    price: 340,
    description: '100g. Revitalizing overnight mask that provides intensive care to the fatigued skin. It revitalizes skin and provides intensive care to the fatigued skin with oxygen capsules and a unique skin protecting complex - pink ceramide. Dual Formula: Oxygen capsule in Pink ceramide cream - It has dual formula where oxygen capsule (which contains Italian oxygenated water) bursts smoothly when touching the skin and melts together with pink ceramide cream. Key ingredients: Pink Ceramide Complex, Oxygen, Growth Factor Complex (EGF, aFGF, bFGF, PIGF, IGF), Swelling Controller, Cucurbita Pepo (Pumpkin) Fruit Extract, Phytosphingosine. Dermatologically tested. With efficacy test on improving erythema and transepidermal water loss.',
    image: '/images/SKIN.jpg',
    category: 'Mask',
    inStock: true,
  },
  {
    id: '35',
    name: 'HYDRO COOL MODELING MASK',
    price: 300,
    description: '1kg. Professional modeling mask that provides immediate cooling and soothing effect. It helps soothe skin after professional skin treatment and makes skin feel refreshed by providing sufficient moisture and immediate cooling sensation to the skin. Key ingredients: Hyaluronic Acid, Ceramide, Allantoin, Mentha Piperita (Peppermint) Extract, Chamaecyparis Obtusa Water, Centella Asiatica Extract. Dermatologically tested.',
    image: '/images/HYDR.jpg',
    category: 'Mask',
    inStock: true,
  },
  {
    id: '36',
    name: 'SOOTHING BOMB SEA ALGAE MASK',
    price: 36,
    description: '25g x 10ea. Eucalace® sheet mask inspired by the healing power of the ocean. It is a Eucalace® sheet mask inspired by the healing power of the ocean. It provides intensive relief to the skin and moisturizes skin with sea algae complex and centella asiatica extract. Key ingredients: Jania Rubens Extract, Undaria Pinnatifida Extract, Bambusa Vulgaris Extract, Centella Asiatica Extract, Hamamelis Virginiana (Witch Hazel) Extract, Custanea Crenata Shell Extract, Panthenol, Allantoin. Dermatologically tested. Efficacy test on skin hydration.',
    image: '/images/SEA.jpg',
    category: 'Mask',
    inStock: true,
  },
  {
    id: '37',
    name: 'PEPTIDE GEL MASK',
    price: 380,
    description: '38g x 5ea. Patented thermo-sensitive hydro gel mask that cools down skin heat and moisturizes skin. It is a patented thermo-sensitive hydro gel mask that instantly cools down skin and moisturizes skin. Specially recommended after the dermatological operations such laser or microneedling. Mechanism: It is made of temperature-sensitive hydro gel. When the mask is applied to the skin, the temperature rises due to body temperature and the hydrogel composition is changed into a fluid state, so that the adhesion to the skin is improved and the effective ingredients are rapidly delivered into the skin (transdermal cosmetic delivery system). And as skin heat is displaced by moisture from the mask, skin feels a cooling effect. Key ingredients: Chondrus Crispus (Carrageenan) Extract, Acetyl Hexapeptide-8, Dipotassium Glycyrrhizate, Hydrolyzed Collagen, Hyaluronic Acid, Arnica Montana Flower Extract, Chamomilla Recutita (Matricaria) Flower Extract. Dermatologically tested. Efficacy test on skin hydration.',
    image: '/images/PEP.jpg',
    category: 'Mask',
    inStock: true,
  },
  {
    id: '38',
    name: 'EZ CO₂ MASK KIT',
    price: 460,
    description: 'Gel 20g x 5ea, Mask 12g x 5ea. Professional carboxy mask for oxygen supply to skin. It is a professional carboxy mask applying \'bohr effect\' – mechanism of carboxy therapy to the cosmetic to give skin firming, brightening and anti-blemish effects. It also acts as a catalytic mask for the best microneedling effect by activating skin so that the skin can absorb effective ingredients which will be penetrated with rolling. Mechanism: Fine particles of CO₂ which are generated by contacting the gel and the sheet mask of GENOSYS EZ CO₂ MASK KIT accelerate the delivery of more oxygen to skin tissues. EZ CO₂ GEL Key ingredients: Lactic Acid, Portulaca Oleracea Extract, Rosmarinus Officinalis (Rosemary) Leaf Extract, Chamomilla Recutita (Matricaria) Flower Extract, Glycyrrhiza Glabra (Licorice) Root Extract, Scutellaria Baicalensis Root Extract, Centella Asiatica Extract, Camellia Sinensis Leaf Extract. EZ CO₂ MASK Key ingredients: Sodium Bicarbonate, Portulaca Oleracea Extract, Rosmarinus Officinalis (Rosemary) Leaf Extract, Chamomilla Recutita (Matricaria) Flower Extract, Glycyrrhiza Glabra (Licorice) Root Extract, Scutellaria Baicalensis Root Extract, Centella Asiatica Extract, Camellia Sinensis Leaf Extract. Dermatologically tested. Efficacy test on improving skin roughness and hyperpigmentation.',
    image: '/images/EZE.jpg',
    category: 'Mask',
    inStock: true,
  },
  {
    id: '39',
    name: 'ULTRA SHIELD SUN CREAM [SPF 50+ PA++++]',
    price: 250,
    description: '50g. Non-greasy and silky sunscreen with powerful UV protection and sun burn care effect. It is a non-greasy silky sunscreen that strongly defends skin against UV rays, and promotes skin recovery from the damage caused by sun exposure with sunburn care complex, hyaluronic acid and lactobacillus ferment. It is a reef-safe product. Key ingredients: Sunburn Care Complex, MicroHA™ (ultra-low molecular weight hyaluronic acid), ProbioMETA™ (Lactobacillus Ferment), Tropical Antioxidant Complex. Dermatologically tested. Reef-safe.',
    image: '/images/SPF50.jpg',
    category: 'Sun',
    inStock: true,
  },
  {
    id: '40',
    name: 'MULTI SUN CREAM [SPF 40 PA++]',
    price: 210,
    description: '40g. Non-greasy mild sunscreen with a skin glowing effect for daily sun protection. It is a non-greasy mild sunscreen that protects skin from UV A&B rays, and helps soothe the irritated skin from sun rays with palmitoyl pentapeptide-4, centella asiatica extract and botanical callus cultures extracts. Key ingredients: Palmitoyl Pentapeptide-4, Sodium Hyaluronate, Rosa Damascena Callus Culture Extract, Vitis Vinifera (Grape) Callus Culture Extract, Centella Asiatica Extract, Scutellaria Baicalensis Root Extract, Lactobacillus/Soymilk Ferment Filtrate. Dermatologically tested.',
    image: '/images/SSUN.jpg',
    category: 'Sun',
    inStock: true,
  },
  {
    id: '41',
    name: 'SKIN CARING BLEMISH BALM CUSHION [SPF 50+ PA++++]',
    price: 300,
    description: 'Cushion 15g, Refill 15g. BB cushion that enables a natural and healthy glow. Dermatologically tested. Key ingredients: Repairing Pep9 Complex, Volufiline™, Glutathione, Adenosine, Niacinamide.',
    image: '/images/BBC.jpg',
    category: 'Cushion BB',
    inStock: true,
  },
  {
    id: '42',
    name: 'INTENSIVE BLEMISH BALM CREAM [SPF 30 PA++]',
    price: 250,
    description: '50g. Natural coverage cream that helps cover redness and express natural skin tone. It is a natural coverage cream that protects skin from the harmful environmental factors. It covers redness and blemishes after the dermatological treatment and helps express natural skin tone. Key ingredients: Adenosine, Allantoin, Origanum Vulgare Leaf Extract, Phytolex SC. Dermatologically tested.',
    image: '/images/BLEM.jpg',
    category: 'Cushion BB',
    inStock: true,
  },
  {
    id: '43',
    name: 'HR³ MATRIX HAIR TONIC α',
    price: 290,
    description: '70ml. Functional tonic that improves the conditions of hair loss. It is a functional tonic approved as a \'functional product that improves the symptoms of hair loss\' by KFDA. It improves the scalp environment that causes hair loss and cools down the scalp heat, giving the sense of freshness to the scalp. Key ingredients: Copper Tripeptide-1, Ascorbic Acid (Vitamin C), Sophora Japonica Extract, Caffeine, Panthenol, Menthol, Acorus Calamus Root Extract, MultiEx BSASM™. Dermatologically tested. KFDA approved as a functional product for improving hair loss symptoms. Efficacy test on improving hair loss.',
    image: '/images/HT.jpg',
    category: 'Scalp/Hair',
    inStock: true,
  },
  {
    id: '44',
    name: 'HR³ MATRIX SCALP SHAMPOO α',
    price: 340,
    description: '300ml. Functional shampoo that improves the conditions of hair loss. It is a functional shampoo approved as a \'functional product that improves the symptoms of hair loss\' by KFDA. It cools down scalp heat and helps control excess sebum on the scalp, making scalp and hair healthy. Key ingredients: Patented Viscum Album Extract, Patented HP-DCC Complex, Saccharomyces Cerevisiae Extract, Acorus Calamus Root Extract, Piroctone Olamine, Biotin, Salicylic Acid, Menthol. Dermatologically tested. KFDA approved as a functional product for improving hair loss symptoms.',
    image: '/images/Sham.jpg',
    category: 'Scalp/Hair',
    inStock: true,
  },
  {
    id: '45',
    name: 'HR³ MATRIX HAIR SOLUTION α',
    price: 740,
    description: '4ml. Premium anti-hair loss ampoule for microneedling treatment. It is the premium anti-hair loss product supplying nutrients that fight against the factors causing hair loss. Special applicator with microneedles promotes nutrition delivery into scalp and helps build the right environment for healthy scalp. Components: Professional Kit - HAIR SOLUTION α 4ml(8ea), Dropper(2ea). Homecare Kit - HAIR SOLUTION α 4ml(8ea), microneedle applicator(1ea), Cleansing Brush(1ea), Disinfecting(1ea). Key ingredients: sh-Polypeptide-9 (VEGF), sh-Polypeptide-7 (HGH), sh-Oligopeptide-1 (EGF), sh-Polypeptide-71 (VIP), Copper Tripeptide-1, Serenoa Serrulata Fruit Extract (Saw Palmetto), Biosaccharide Gum-4, Panthenol, Menthol, Black Complex, Brassica Oleracea Italica (Broccoli) Extract. Dermatologically tested. Research papers on the improvement of hair loss.',
    image: '/images/HHR.jpg',
    category: 'Scalp/Hair',
    inStock: true,
  },
  {
    id: '46',
    name: 'HR³ MATRIX SCALP PEELING α',
    price: 290,
    description: '100ml. Scalp peeling product with deep cleansing and heat cooling effects. It is a scalp peeling product which gives the deep cleansing effect for the scalp and refreshes the scalp with cooling effect. Key ingredients: Copper Tripeptide-1, Serenoa Serrulata Fruit Extract (Saw Palmetto), Salicylic Acid, Menthol, Black Complex, Camellia Sinensis Leaf Extract. Dermatologically tested.',
    image: '/images/scal.jpg',
    category: 'Scalp/Hair',
    inStock: true,
  },
  {
    id: '47',
    name: 'HR³ MATRIX MESOPECIA KIT',
    price: 1100,
    description: 'Professional kit to allows a systematic hair loss treatment. It is a professional kit that allows a systematic hair loss treatment by combining microneedling with high performing cosmeceuticals. Components: SCALP PEELING α (100ml) - It is a light scalp peeling product which gives the deep cleansing effect for the scalp and refreshes the scalp with cooling effect. HAIR SOLUTION α (4ml x 6ea) + STAMP (ROLLER) - It is a premium anti-hair loss product supplying nutrients that fight against the factors causing hair loss. It is specially formulated for microneedling to build the right environment for healthy scalp. Key ingredients SCALP PEELING α: Copper Tripeptide-1, Serenoa Serrulata Fruit Extract (Saw Palmetto), Salicylic Acid, Menthol, Black Complex, Camellia Sinensis Leaf Extract. Key ingredients HAIR SOLUTION α: sh-Polypeptide-9 (VEGF), sh-Polypeptide-7 (HGH), sh-Oligopeptide-1 (EGF), sh-Polypeptide-71 (VIP), Copper Tripeptide-1, Serenoa Serrulata Fruit Extract (Saw Palmetto), Biosaccharide Gum-4, Panthenol, Menthol, Black Complex, Brassica Oleracea Italica (Broccoli) Extract. Dermatologically tested. Research papers on the improvement of hair loss.',
    image: '/images/meso.jpg',
    category: 'Scalp/Hair',
    inStock: true,
  },
  {
    id: '48',
    name: 'Hair-GENTRON',
    price: 3300,
    description: 'LED helmet with massaging and heating functions to treat hair loss. Patent No. 10-2151442. Bronze medal winner of 2020 Korea invention patent competition. It is a LED helmet with massaging and heating functions patented as a scalp massager for promoting hair growth using air pressure and LED lights. Features: Infrared light + Red light + Blue light + Massaging + Heating function. Advantages: Non-invasive light therapy, Safe & painless therapy, Available for both professional & home care, Infrared light, red light and blue light can be irradiated at the same time, Proper distance from the source of the light energy and scalp is guaranteed which leads to the optimal emission effect, Massaging function can be done while lights are irradiated, Music mode helps the user feel relaxed, Heating function can be added during treatment. Effects: Improve blood circulation in scalp → Provide more nutrients & oxygen to hair follicles, Relieve stress and tension.',
    image: '/images/gen.jpg',
    category: 'Device',
    inStock: true,
  },
  {
    id: '49',
    name: 'GENO-LED IR II',
    price: 5500,
    description: 'LED device that resolves complicated skin problems. It is a LLLT device which resolves complicated skin problems by irradiating lights with various wave lengths - 640nm (red), 423nm (blue), 532nm (green), 583nm (yellow) and 830nm (infrared). Features: Dome shape for less light loss, Excellent and powerful high-brightness and special near-infrared light SMD LED element, Light of different lengths (423nm~830nm) - Blue light, Green light, Yellow light, Red light + Infrared light, Available for the treatment of whole body – total care device, Effective for various types of skin problems, Gentle and safe treatment without pain, side effects and downtime. LED Specifications: Red (640nm) - 380ea, Blue (423nm) - 380ea, Green (532nm) - 380ea, Yellow (583nm) - 380ea, Infrared (830nm) - 190ea. Total: 1,710 LED and IR lamps. Effects: Cell regeneration, Anti-aging, Brightening, Soothing, Acne treatment, Improvement in edema/erythema, Hair loss care, Improvement in blood circulation. Face, Scalp, Body Total Care device.',
    image: '/images/LEDD.jpg',
    category: 'Device',
    inStock: true,
  },
  {
    id: '50',
    name: 'EyeCell EYE ZONE CARE KIT',
    price: 980,
    description: 'Professional kit to treat various skin problems around eyes. It is a professional kit designed to treat various skin problems around eyes from dehydration, dark circle, eye bag to crow\'s feet. It combines cosmeceuticals with a roller specially designed for eye area to activate collagen production and increase the absorption of ingredients into skin. Components: EYE CONTOUR SERUM (10ml) + EYE ROLLER - It is a highly enriched all-in-one eye serum that helps improve wrinkles, dark circles and diminish the appearance of eye puffs. It can be used together with EYE ROLLER developed to enable delicate and detailed care even for the curved area of face as well as eye contour area. EYE CONTOUR CREAM (20g) - It is a daily cream for eye contour area that brings younger-looking eyes by helping reduce wrinkles and dark circles and depuff the under eye with peptide complex, botanical callus culture extracts and anti-dark circle complex. EYE PEPTIDE GEL PATCH (101g / 60ea) - It is a patented thermo-sensitive for eye contour area that soothes and moisturizes the skin that went through dermatologic procedures or natural aging. And it improves eye bags. Dermatologically tested. Efficacy test on improving wrinkles and moisturizing.',
    image: '/images/EYEZ.jpg',
    category: 'Eye care',
    inStock: true,
    size: '1 box',
  },
]
