import { Product } from '@/types'

export const products: Product[] = [
  {
    id: '1',
    name: 'Microneedle Roller',
    price: 230,
    description: 'Professional-grade microneedling device with patented Diskneedle Therapy System (DTS) for enhanced skin rejuvenation. Features 450 ultra-thin needles (25% thinner than competitors) for superior product absorption and minimal skin trauma. Stimulates natural collagen production and improves skin texture. Manufactured in South Korea.',
    image: '/images/genosys-microneedling-devices.jpg',
    images: JSON.stringify(['/images/genosys-microneedling-devices.jpg', '/images/Second/roller1.jpg', '/images/Second/roller_stamp2.jpg']),
    category: 'Microneedling',
    inStock: true,
    size: '0.25mm',
  },
  {
    id: '2',
    name: 'Needle Pen-K',
    price: 1450,
    description: 'Skin stimulator to promote collagen production and transdermal nutrient delivery. GENOSYS NEEDLE PEN-K is an automatic device for microneedling therapy. It increases the absorption rate of active ingredients of skin care products by creating physical pathways through skin. And it promotes collagen and elastin induction through natural wound healing process of skin. Manufactured in South Korea.',
    image: '/images/Needle-pen.jpg',
    images: null,
    category: 'Microneedling',
    inStock: true,
    size: '1 Device',
  },
  {
    id: '3',
    name: 'HairGen BOOSTER',
    price: 1800,
    description: 'Auto-microneedling LED device for scalp treatment. HR³ MATRIX HAIR SOLUTION α - It is the premium anti-hair loss product supplying nutrients that fight against the factors causing hair loss. HR³ MATRIX HAIR STAMP - Patented delivery enhancer with microneedles leads to scalp regeneration and collagen production by promoting natural wound healing process of skin and increases skin permeability of nutritive ingredients. Manufactured in South Korea.',
    image: '/images/Booster.jpg',
    images: null,
    category: 'Device',
    inStock: true,
  },
  {
    id: '4',
    name: 'POWER SOLUTION HES',
    price: 580,
    description: '2ml x 10ea. Hydrating and firming ampoule for microneedling treatment. Dermatologically tested. Efficacy test on skin hydration. Features: It is a hydrating and firming ampoule specially formulated for microneedling treatment that provides long-lasting moisturizing and plumping effects, and relieves skin irritation with sh-polypeptide-7 (recombinant human peptide), hyaluronic acid and BIOPHYTEX™. Key Ingredients: Hyaluronic Acid, Panthenol, Phytosphingosine, BIOPHYTEX™, Copper Tripeptide-1, sh-Polypeptide-7, Palmitoyl Tetrapeptide-7. Manufactured in South Korea.',
    image: '/images/hes_power/main.jpeg',
    images: JSON.stringify([
      '/images/hes_power/s1new.jpeg',
      '/images/hes_power/s2.jpeg',
      '/images/hes_power/s3.jpeg',
      '/images/hes_power/s4.jpeg',
      '/images/hes_power/s5.jpeg',
      '/images/hes_power/s6.jpeg',
      '/images/hes_power/s7.jpeg',
    ]),
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '5',
    name: 'POWER SOLUTION CVS',
    price: 580,
    description: '2ml x 10ea. Skin revitalizing ampoule for microneedling treatment. Dermatologically tested. Efficacy test on moisturizing. Features: It is a skin revitalizing ampoule specially formulated for microneedling treatment that supplies nutrients to the skin, soothes and hydrates skin with sh-polypeptide-7 (recombinant human peptide), botanical stem cell extracts and panthenol. Skin-Friendly Formulation: Not containing harmful additives considering the increased skin permeability by microneedling (no-paraben, ethanol, artificial fragrance, artificial pigment, sulfate). Dermatologically tested. Key Ingredients: sh-polypeptide-7, Palmitoyl Tripeptide-1, Lactobacillus/Soymilk Ferment Filtrate, Panthenol, Allantoin, Hyaluronic Acid, Vitis Vinifera (Grape) Callus Culture Extract, Rosa Damascena Callus Culture Extract, Lactobacillus Ferment Lysate Filtrate. Manufactured in South Korea.',
    // The squared hero, matching the database. CVS.jpg is the same shot at 956x662
    // and leaves a hard-cornered band above and below it in the square gallery
    // stage. The main image is deliberately not repeated in `images`: web and
    // mobile both prepend it.
    image: '/images/cvs-hero.jpg',
    images: JSON.stringify(['/images/Second/cvs_big1.jpg', '/images/Second/cvs_big2.jpg']),
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '6',
    name: 'POWER SOLUTION CTS',
    price: 580,
    description: 'CTS is Cytokine Concentrate Solution. The carton function is improvement of skin texture: it helps the skin retain its natural elasticity and increases the strength of skin. 2 ml × 10 sealed glass vials. 5-Free. Dermatologically tested. Made in Korea by DTS MG.',
    // The squared hero, matching the database. CTS.jpg is the same shot at 956x662
    // and leaves a hard-cornered band above and below it in the square gallery
    // stage. The main image is deliberately not repeated in `images`: web and
    // mobile both prepend it.
    image: '/images/cts-hero.jpg',
    images: JSON.stringify(['/images/Second/cts_big.jpg', '/images/Second/cts_big2.jpg']),
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '7',
    name: 'POWER SOLUTION PCS',
    price: 580,
    description: 'PCS is Problem Control Solution. The carton function is oil and sebum control: it controls excessive oil production and helps reduce the appearance of blemishes. 2 ml × 10 sealed glass vials. 5-Free. Dermatologically tested. Made in Korea by DTS MG.',
    // The squared hero, matching the database. PCS.jpg is the same shot at 956x662
    // and leaves a hard-cornered band above and below it in the square gallery
    // stage. The main image is deliberately not repeated in `images`: web and
    // mobile both prepend it.
    image: '/images/pcs-hero.jpg',
    images: JSON.stringify(['/images/Second/pcs_big1.jpg', '/images/Second/pcs_big2.jpg']),
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '8',
    name: 'POWER SOLUTION SWS',
    price: 580,
    description: 'SWS is Skin Depigmenting & Whitening Solution. Korea registers it as a whitening functional cosmetic with arbutin 2% as the principal ingredient. Helps improve pigmentation, even skin tone and brighten the skin surface. 2 ml × 10 sealed glass vials. 5-Free. Dermatologically tested. Made in Korea by DTS MG.',
    // The squared hero, matching the database. SWS.jpg is the same shot at 956x662
    // and leaves a hard-cornered band above and below it in the square gallery
    // stage. The main image is deliberately not repeated in `images`: web and
    // mobile both prepend it.
    image: '/images/sws-hero.jpg',
    images: JSON.stringify(['/images/Second/sws_big1.jpg', '/images/Second/sws_big2.jpg']),
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '9',
    name: 'POWER SOLUTION AWS',
    price: 580,
    description: 'AWS is Anti-Wrinkle Solution. Korea registers it as a wrinkle-improving functional cosmetic with adenosine 0.04% as the principal ingredient. Reduces the appearance of wrinkles and improves skin firmness. 2 ml × 10 sealed glass vials. 5-Free. Dermatologically tested. Made in Korea by DTS MG.',
    // The squared hero, matching the database. AWS.jpg is the same shot at 956x662
    // and leaves a hard-cornered band above and below it in the square gallery
    // stage. The main image is deliberately not repeated in `images`: web and
    // mobile both prepend it.
    image: '/images/aws-hero.jpg',
    images: JSON.stringify(['/images/Second/aws1.jpg', '/images/Second/aws2.jpg']),
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '10',
    name: 'SNOW O₂ CLEANSER',
    price: 330,
    description: '180 ml / 500 ml. Facial cleanser. Apply on a dry face, away from the eyes. Naturally generated oxygen bubbles lift make-up dirt and skin impurities; circular massage, then rinse with tepid water. The bubbles come from Methyl Perfluoroisobutyl Ether at 8%. Morning and evening. Dermatologically tested.',
    image: '/images/cleanser/main_clean.jpeg',
    images: JSON.stringify([
      '/images/cleanser/S1.jpg',
      '/images/cleanser/S2.jpg',
      '/images/cleanser/S3.jpg',
      '/images/cleanser/S4.jpg',
      '/images/cleanser/S5.jpg',
      '/images/cleanser/S6.jpg',
    ]),
    category: 'Cleanser',
    inStock: true,
    size: '180ml',
    videoUrl: '/videos/cleanser.mp4',
  },
  {
    id: '11',
    name: 'SKIN DEFENDER LIP & EYE MAKEUP REMOVER',
    price: 290,
    description: '200ml. Fresh, non-greasy lip and eye makeup remover. Shake the yellow oil into the water, soak a cotton pad, hold a few seconds on the lips and the eye area, then wipe. Cetyl ethylhexanoate 27.8%, disiloxane 13%, isohexadecane 9%. The vitamins and peptides sit at cosmetic trace. Not a face wash. Dermatologically tested.',
    image: '/images/remover/main4.jpeg',
    images: JSON.stringify([
      '/images/remover/S1b.jpg',
      '/images/remover/S2b.jpg',
      '/images/remover/S3b.jpg',
      '/images/remover/S4b.jpg',
      '/images/remover/S5b.jpg',
      '/images/remover/S6b.jpg',
    ]),
    category: 'Cleanser',
    inStock: true,
    size: '200ml',
    videoUrl: '/videos/remover.mp4',
  },
  {
    id: '12',
    name: 'EPI TURNOVER BOOSTING PEELING GEL',
    price: 250,
    description: '100g. Enzyme + cellulose peeling gel. On clean, dry skin, massage for up to one minute; the dead cells clump and rinse away with tepid water. Cellulose 3% is the roll you feel. Once or twice a week. Dermatologically tested.',
    image: '/images/epi/main.jpeg',
    images: JSON.stringify([
      '/images/epi/s1.jpeg',
      '/images/epi/s2.jpeg',
      '/images/epi/s3.jpeg',
      '/images/epi/s4.jpeg',
      '/images/epi/s5.jpeg',
      '/images/epi/s6.jpeg',
    ]),
    category: 'Peeling',
    inStock: true,
    videoUrl: '/videos/epi.mp4',
  },
  {
    id: '13',
    name: 'SKIN RENEWAL PEELING SYSTEM (SRS)',
    price: 810,
    description: '2ml × 10. Professional AHA peel. Glycolic acid 15%, lactic acid 13.5%, mandelic acid 2%. Apply evenly, keep off the lips and the eye area, sit 15-20 minutes, rinse with cold water. Soft peeling. The peptide sits at 0.1 ppb. Not the home cellulose roll. Dermatologically tested.',
    image: '/images/srs_2_new/main.jpeg',
    images: JSON.stringify([
      '/images/srs_2_new/s1.jpg',
      '/images/srs_2_new/s2.jpg',
      '/images/srs_2_new/s3.jpg',
      '/images/srs_2_new/s4.jpg',
      '/images/srs_2_new/s5.jpg',
      '/images/srs_2_new/s6.jpg',
      '/images/srs_2_new/s7.jpg',
      '/images/srs_2_new/s8.jpg',
    ]),
    category: 'Peeling, PRO Solution',
    inStock: true,
  },
  {
    id: '14',
    name: 'MICROBIOME ENERGY INFUSING MIST',
    price: 160,
    description: '80ml. Sprayable emulsion mist. Shea butter 1.2% with glycerin and four seed oils. Shake well, spray at 10-20 cm with eyes closed, through the day. Moisturizing and nourishing. Can go over makeup. The peptide sits at 0.000001%. Not a water toner.',
    image: '/images/mist/main2.jpeg',
    images: JSON.stringify([
      '/images/mist/S1.jpeg',
      '/images/mist/S2.jpeg',
      '/images/mist/S3.jpeg',
      '/images/mist/S4.jpeg',
      '/images/mist/S5.jpeg',
      '/images/mist/S6.jpeg',
    ]),
    category: 'Toner/Mist',
    inStock: true,
    size: '80ml',
    videoUrl: '/videos/mist.mp4',
  },
  {
    id: '15',
    name: 'INTENSIVE PROBLEM CONTROL TONER',
    price: 260,
    description: '200ml / 500ml. Oil-control toner for blemish-prone skin. Apply or spray morning and evening. Takes excess oil and sebum, then puts water back. Zinc PCA 0.5% is the named active. The 200 ml bottle turns upside down for the back. Salicylic acid is 0.001%. Copper peptide is not in the formula. Dermatologically tested.',
    image: '/images/problem/Main.jpg',
    images: JSON.stringify([
      '/images/problem/S1.jpg',
      '/images/problem/S2.jpg',
      '/images/problem/S3.jpg',
      '/images/problem/S4.jpg',
      '/images/problem/S5.jpg',
      '/images/problem/S6.jpg',
    ]),
    category: 'Toner/Mist',
    inStock: true,
    size: '200ml',
    videoUrl: '/videos/problem.mp4',
  },
  {
    id: '16',
    name: 'SNOW BOOSTER',
    price: 260,
    description: '200ml / 1000ml. Daily toner for all skin types. Apply or spray morning and evening to give moisture. Can go over makeup. Moisturizes and soothes, then refines after the cleanse. Betaine 3% is the named active. Phytolex is a 0.5% premix. Not the oil-control toner. Dermatologically tested.',
    image: '/images/Second/main_booster.jpg',
    images: JSON.stringify([
      '/images/Second/main_booster2.png',
    ]),
    category: 'Toner/Mist',
    inStock: true,
    size: '200ml',
    videoUrl: '/videos/booster.mp4',
  },
  {
    id: '17',
    name: 'EyeCell EYE CONTOUR SERUM',
    price: 370,
    description: '10ml. Intensive all-in-one eye serum for deep wrinkles, dark circles and eye puffs. Arbutin 2% and Adenosine 0.04% are the Korean functional pair. Morning and evening, pat and leave on. Dermatologically tested. Avoid during pregnancy and lactation.',
    image: '/images/eye_serum/main.jpeg',
    images: JSON.stringify([
      '/images/eye_serum/s1.jpeg',
      '/images/eye_serum/s2.jpeg',
      '/images/eye_serum/s3.jpeg',
      '/images/eye_serum/s4.jpeg',
      '/images/eye_serum/s5.jpeg',
      '/images/eye_serum/s6.jpeg',
      '/images/eye_serum/s7.jpeg',
    ]),
    category: 'Eye care',
    inStock: true,
  },
  {
    id: '18',
    name: 'MOISTURE REPLENISHING HYALURON SERUM',
    price: 330,
    description: '30ml. Moisturizing serum. Hydrolyzed hyaluronic acid 2,000 ppm. Apply on the face and gently pat, morning and evening. Coconut-water serum with an HA complex and mushrooms. Coconut water is 0.80%. PENTAVITIN is 0.615%. Not the cream. Not a 4-step electrolyte story. Dermatologically tested.',
    image: '/images/hyaluron_serum/main.jpeg',
    images: JSON.stringify([
      '/images/hyaluron_serum/s1.jpeg',
      '/images/hyaluron_serum/s2.jpeg',
      '/images/hyaluron_serum/s3.jpeg',
      '/images/hyaluron_serum/s4.jpeg',
      '/images/hyaluron_serum/s5.jpeg',
      '/images/hyaluron_serum/s6.jpeg',
    ]),
    category: 'Serum',
    inStock: true,
    videoUrl: '/videos/hs_cream_serum.mp4',
  },
  {
    id: '19',
    name: 'ALL FOR SENSITIVE SERUM',
    price: 330,
    description: '30ml. Serum for sensitive, reactive skin. Relieves, protects and moisturizes — MultiEx BSASM® Plus at 1%, with betaine, allantoin and hyaluronic acid. Morning and night. Dermatologically tested.',
    image: '/images/sensitive_serum/main.jpeg',
    images: JSON.stringify([
      '/images/sensitive_serum/s1.jpeg',
      '/images/sensitive_serum/s2.jpeg',
      '/images/sensitive_serum/s3.jpeg',
      '/images/sensitive_serum/s4.jpeg',
      '/images/sensitive_serum/s5.jpeg',
      '/images/sensitive_serum/s6.jpeg',
    ]),
    category: 'Serum',
    inStock: true,
    videoUrl: '/videos/all_serum.mp4',
  },
  {
    id: '20',
    name: 'PROBLEM CONTROL SERUM',
    price: 330,
    description: '30ml leave-on serum for oily and combination skin. Korea registers it for anti-blemishes, oil and sebum control, and zinc PCA at a full 0.05% is the ingredient carrying that. Nine tenths of the bottle is water, so it sinks in and leaves nothing sitting on the surface. Two or three drops after your toner, patted in, morning and night. No perfume of any kind. Dermatologically tested.',
    image: '/images/problems_serum/main.jpeg',
    images: JSON.stringify([
      '/images/problems_serum/s1.jpeg',
      '/images/problems_serum/s2.jpeg',
      '/images/problems_serum/s3.jpeg',
      '/images/problems_serum/s4.jpeg',
      '/images/problems_serum/s5.jpeg',
      '/images/problems_serum/s6.jpeg',
    ]),
    category: 'Serum',
    inStock: true,
    size: '30ml',
    videoUrl: '/videos/problem_serum.mp4',
  },
  {
    id: '21',
    name: 'MULTI VITA RADIANCE SERUM',
    price: 330,
    description: 'Twelve vitamins, and the carton prints the dose beside every one of them. Niacinamide at 20,000 ppm, panthenol at 10,000, stable vitamin C at 1,000, vitamin E at 300, and then eleven more measured in parts per billion. Korea registers this as a whitening functional cosmetic with niacinamide named as the active. MELAZERO, the patented complex, is loquat leaf and spearmint. In the maker\'s two-week trial, surface melanin fell 28.0%. Pat it in morning and night, and wear sunscreen over it by day. Not for use during pregnancy.',
    image: '/images/radiance_serum/main.jpeg',
    images: null,
    category: 'Serum',
    inStock: true,
    size: '30ml',
    videoUrl: '/videos/radiance_serum.mp4',
  },
  {
    id: '22',
    name: 'MULTI FUNCTIONAL ANTI-WRINKLE SERUM',
    price: 330,
    description: '30ml. Anti-aging serum with bakuchiol, a natural alternative to retinol and anti-wrinkle peptide complex. It is an anti-aging serum that helps visibly smooth the signs of wrinkles and reinforces skin firmness with a nourishing ingredient – bakuchiol, a natural alternative to retinol and anti-wrinkle peptide complex. Clinical study on improvement of skin age index, P&K Skin Research Center, Feb. 22 to May 13, 2024, 24 adult women aged 30~59 years. Key ingredients: Bakuchiol, Anti-aging Peptide 6, Lipid Barrier Liposome (Ceramide NP, Cholesterol, Phytosphingosine), Collagen, Elastin, Propolis Extract, Adenosine, Niacinamide. Dermatologically tested. Efficacy test on improving wrinkles and skin tone balance.',
    image: '/images/multif_serum/main.jpeg',
    images: JSON.stringify([
      '/images/multif_serum/main.jpeg',
      '/images/multif_serum/s1.jpeg',
      '/images/multif_serum/s2.jpeg',
      '/images/multif_serum/s3.jpeg',
      '/images/multif_serum/s4.jpeg',
      '/images/multif_serum/s5.jpeg',
      '/images/multif_serum/s6.jpeg',
    ]),
    category: 'Serum',
    inStock: true,
    videoUrl: '/videos/multif_serum.mp4',
  },
  {
    id: '23',
    name: 'ND Cell ANTI-WRINKLE CREAM',
    price: 370,
    description: '50g. Anti-aging cream for neck and decollete area. It targets the special needs of the delicate skin around the neck and decollete area. It lifts and firms skin and refine the skin texture. It also has an excellent effect of depigmentation. Key ingredients: Copper Tripeptide-1, sh-polypeptide 7, Acetyl Hexapeptide-8, Palmitoyl Hexapeptide-12, Palmitoyl Tripeptide-1, Vitamin Complex (vitamin A, B5, C, E) Hyaluronic Acid, Ceramide, Squalane. Dermatologically tested. Efficacy test on improving wrinkles.',
    image: '/images/ND.jpg',
    images: JSON.stringify(['/images/ND.jpg', '/images/Second/nd_big1.jpg']),
    category: 'Cream',
    inStock: true,
    size: '50g',
  },
  {
    id: '24',
    name: 'EyeCell EYE CONTOUR CREAM',
    price: 370,
    description: '20g. Daily all-in-one eye cream for wrinkles, dark circles and puffiness. Arbutin 2% and Adenosine 0.04% are the Korean functional pair. Morning and evening, tap and leave on. Dermatologically tested. Avoid during pregnancy and lactation. Contains peanut oil.',
    image: '/images/eye_cream/main.jpeg',
    images: JSON.stringify([
      '/images/eye_cream/s1.jpeg',
      '/images/eye_cream/s2.jpeg',
      '/images/eye_cream/s3.jpeg',
      '/images/eye_cream/s4.jpeg',
      '/images/eye_cream/s5.jpeg',
      '/images/eye_cream/s6.jpeg',
    ]),
    category: 'Eye care',
    inStock: true,
  },
  {
    id: '25',
    name: 'SOOTHING REPAIR POSTCREAM',
    price: 204,
    description: '20g (Homecare) / 100g (Professional). Regenerating cream for healthy skin recovery after professional treatment. It is a regenerating cream that promotes skin recovery after professional treatment. It helps irritated skin rapidly recover from redness, erythema and edema after the dermatological operations or any other irritations and promotes healthy rejuvenation. Key ingredients: sh-Polypeptide-7, Centella Complex (Asiaticoside, Madecassic Acid, Asiatic Acid), Dipotassium Glycyrrhizate, Panthenol, Vitis Vinifera (Grape) Callus Culture Extract, Rosa Damascena Callus Culture Extract, Scutellaria Baicalensis Root Extract. Dermatologically tested. Efficacy test on protection of the skin against damage induced by physical stimuli.',
    image: '/images/SRC.jpg',
    images: null,
    category: 'Cream',
    inStock: true,
    size: '20g',
    videoUrl: '/videos/soothing-repair-postcream-20260806.mp4',
  },
  {
    id: '26',
    name: 'EGF REPAIR OXYMASK CREAM',
    price: 290,
    description: '50g. Oxygen bubbling mask cream with skin regenerating ingredients – EGF and madecassoside. It is a unique oxygen bubbling mask cream which makes dull & stressed skin healthy with skin regenerating ingredients such as EGF and madecassoside. It is a "S.O.S" cream that can be effectively used for damaged skin by various causes. Key ingredients: sh-Oligopeptide-1 (EGF), Madecassoside, Copper Tripeptide-1, SEPITONIC M3 (Mineral Complex), Salmon Oil, Adenosine. Dermatologically tested. Efficacy test on skin soothing effect against external stimulus.',
    image: '/images/EGF.jpg',
    images: null,
    category: 'Cream',
    inStock: false,
    // Discontinued Jul 2026; the bespoke page was retired Aug 2026. The row itself
    // stays so past orders can still resolve this product's name and image.
    isHidden: true,
  },
  {
    id: '27',
    name: 'SKIN BARRIER PROTECTING CREAM',
    price: 450,
    description: 'Ceramide NP at 0.5%, and the Korean panel on the carton prints the number in brackets: 5,000 ppm. Most creams that put ceramide on the front use it one or two orders of magnitude lower. Behind it, glycerin at 17.49% and shea butter at 3%, which makes this the richest of the three GENOSYS face creams and the one for skin that is sensitive and dry. The carton asks you to pat it in, not rub it. 100g, morning and night. Dermatologically tested.',
    image: '/images/skin_barr/main.jpeg',
    images: JSON.stringify([
      '/images/skin_barr/s1.jpeg',
      '/images/skin_barr/s2.jpeg',
      '/images/skin_barr/s3.jpeg',
      '/images/skin_barr/s4.jpeg',
      '/images/skin_barr/s5.jpeg',
      '/images/skin_barr/s6.jpeg',
    ]),
    category: 'Cream',
    inStock: true,
    size: '100g',
    videoUrl: '/videos/barrier2.mp4',
  },
  {
    id: '28',
    name: 'INTENSIVE HYDRO SOOTHING CREAM',
    price: 290,
    description: '50g (Homecare) / 250g (Professional). Soothing and moisturizing gel with aloe vera, snail secretion filtrate. It calms down skin irritation and provides long-lasting hydration to the skin with aloe vera, snail secretion filtrate and hyaluronic acid. Key ingredients: Aloe Barbadensis Leaf Extract, Snail Secretion Filtrate, Hyaluronic Acid, Lactobacillus/Pumpkin Ferment Extract, Beta-Glucan, Phytolex SC. Dermatologically tested. Efficacy test on skin hydration.',
    image: '/images/HSC.jpg',
    images: null,
    category: 'Cream',
    inStock: true,
  },
  {
    id: '29',
    name: 'MOISTURE REPLENISHING HYALURON CREAM',
    price: 290,
    description: 'The carton prints the dose of every hyaluronate beside its name, which almost nobody does. Sodium hyaluronate at 1,000.9 ppm, then seven more at 30 parts per billion. The one carrying the cream is the high molecular weight grade, the heavy form that stays on the surface and stops water leaving, and glycerin at 9% sits right behind it. Hydration measured 82% higher immediately after a single use and was still significantly up at 72 hours. Massage it in morning and night, after the serum. 50g and 250g.',
    image: '/images/hyaluron/main.jpeg',
    images: null,
    category: 'Cream',
    inStock: true,
    videoUrl: '/videos/hyaluron.mp4',
  },
  {
    id: '30',
    name: 'INTENSIVE PROBLEM CONTROL CREAM',
    price: 290,
    description: 'A cream with no oil in it. No plant oil, no butter, no wax, no emulsifier: what makes it feel like a cream is 1.3% of thickener holding 86.6% water in a gel. Zinc PCA sits at 0.05%, the same dose as the Problem Control Serum, and Korea registers the cream for anti-blemishes and oil control. Massage it in as the last step, morning and night. 50g and 250g. No perfume of any kind. Dermatologically tested.',
    image: '/images/problem_cream/main.jpeg',
    images: null,
    category: 'Cream',
    inStock: true,
    videoUrl: '/videos/problem_cream.mp4',
  },
  {
    id: '31',
    name: 'MULTI VITA RADIANCE CREAM',
    price: 290,
    description: 'A full 2% of niacinamide, and this is the one product in the range whose certificate actually tests for it rather than taking the recipe\'s word: the batch on file came back at 2.04%. Same active and same dose as the Multi Vita serum, carried here in 13% macadamia oil instead of water. The orange colour is the astaxanthin itself, with no pigment added. In the maker\'s two-week trial surface melanin fell 29.7%. 50g and 230g. Morning and night, with sunscreen over it by day.',
    image: '/images/radiance/main.jpeg',
    images: null,
    category: 'Cream',
    inStock: true,
    size: '50g',
    videoUrl: '/videos/radiance.mp4',
  },
  {
    id: '32',
    name: 'MULTI FUNCTIONAL ANTI-WRINKLE CREAM',
    price: 290,
    description: '50g (Homecare) / 250g (Professional). Multi-functional anti-wrinkle and brightening cream with bakuchiol, a natural alternative to retinol. Helps visibly smooth wrinkles, reinforce skin firmness, and even skin tone with propolis, collagen, adenosine, niacinamide, mango seed butter, and a lipid barrier liposome. Gently massage morning and evening. Clinical study on improvement of skin age index, P&K Skin Research Center, Feb. 22 to May 13, 2024, 24 adult women aged 30~59 years. Key ingredients: Bakuchiol, Propolis Extract, Hydrolyzed Collagen & Elastin, Adenosine, Niacinamide, Mango Seed Butter, Lipid Barrier Liposome (Ceramide NP, Cholesterol, Phytosphingosine). Dermatologically tested. Efficacy test on improving wrinkles and skin tone balance.',
    image: '/images/multifunc_cream/main.jpeg',
    images: JSON.stringify([
      '/images/multifunc_cream/s1.jpeg',
      '/images/multifunc_cream/s2.jpeg',
      '/images/multifunc_cream/s3.jpeg',
      '/images/multifunc_cream/s4.jpeg',
      '/images/multifunc_cream/s5.jpeg',
      '/images/multifunc_cream/s6.jpeg',
    ]),
    category: 'Cream',
    inStock: true,
    size: '50g',
    videoUrl: '/videos/multif_cream.mp4',
  },
  {
    id: '33',
    name: 'EyeCell EYE PEPTIDE GEL PATCH',
    price: 380,
    description: '101g (60 patches / 30 applications). Take-off hydrogel eye mask for calming and moisturizing the contour. Niacinamide 2% and Adenosine 0.04% are the Korean functional pair. Under the eyes and/or eyebrow bones for 20 to 40 minutes, then remove. Dermatologically tested.',
    image: '/images/patch/main.jpeg',
    images: null,
    category: 'Eye care',
    inStock: true,
    videoUrl: '/videos/eyecell-eye-peptide-gel-patch-20260806.mp4',
  },
  {
    id: '34',
    name: 'SKIN RESCUE OVERNIGHT CREAM MASK',
    price: 340,
    description: '100g. Leave-on overnight cream mask for soothing and revitalizing tired-looking skin. Niacinamide 2% and Adenosine 0.04% are the Korean functional pair. Last step of the evening. Do not wash off. Dermatologically tested.',
    image: '/images/overnight/main.jpeg',
    images: null,
    category: 'Mask',
    inStock: true,
    size: '100g',
  },
  {
    id: '35',
    name: 'HYDRO COOL MODELING MASK',
    price: 300,
    description: '1kg. Professional cooling modeling mask. Mix 30g of powder with water at 1 : 0.8, leave 15-20 minutes, peel. Diatomaceous earth 65% is the pouch. Peppermint cool until it comes off. Dermatologically tested.',
    image: '/images/HYDR.jpg',
    images: null,
    category: 'Mask',
    inStock: true,
    videoUrl: '/videos/hydro.mp4',
  },
  {
    id: '36',
    name: 'SOOTHING BOMB SEA ALGAE MASK',
    price: 36,
    description: '25g x 10ea. Eucalace® sheet mask inspired by the healing power of the ocean. It is a Eucalace® sheet mask inspired by the healing power of the ocean. It provides intensive relief to the skin and moisturizes skin with sea algae complex and centella asiatica extract. Key ingredients: Jania Rubens Extract, Undaria Pinnatifida Extract, Bambusa Vulgaris Extract, Centella Asiatica Extract, Hamamelis Virginiana (Witch Hazel) Extract, Custanea Crenata Shell Extract, Panthenol, Allantoin. Dermatologically tested. Efficacy test on skin hydration.',
    image: '/images/sea_algae/Main.jpeg',
    images: null,
    category: 'Mask',
    inStock: true,
    size: '1 sheet (25g)',
  },
  {
    id: '37',
    name: 'PEPTIDE GEL MASK',
    price: 380,
    description: '38g × 5. Face hydrogel sheet. After a dermatological procedure, sit 20-40 minutes, take the sheet off, massage the leftover in. Glycerin 20% is the pouch. The peptide sits at 0.05 ppm. Dermatologically tested.',
    image: '/images/peptide_mask/main.jpeg',
    images: JSON.stringify([
      '/images/peptide_mask/s1c.jpeg',
      '/images/peptide_mask/s2c.jpeg',
      '/images/peptide_mask/s3c.jpeg',
      '/images/peptide_mask/s4c.jpeg',
      '/images/peptide_mask/s5c.jpeg',
    ]),
    category: 'Mask',
    inStock: true,
    videoUrl: '/videos/peptide.mp4',
  },
  {
    id: '38',
    name: 'EZ CO₂ MASK KIT',
    price: 460,
    description: 'Gel 20g ×5, mask 12g ×5, spatula ×1. An acidic gel and a bicarbonate sheet meet on dry skin. CO₂ forms, you wait ten minutes, you rinse. Five treatments. Dermatologically tested.',
    image: '/images/ez_mask/main.jpeg',
    images: JSON.stringify([
      '/images/ez_mask/s1.jpeg',
      '/images/ez_mask/s2.jpeg',
      '/images/ez_mask/s3.jpeg',
      '/images/ez_mask/s4.jpeg',
      '/images/ez_mask/s5.jpeg',
      '/images/ez_mask/s6.jpeg',
      '/images/ez_mask/s7.jpeg',
      '/images/ez_mask/s8.jpeg',
    ]),
    category: 'Mask',
    inStock: true,
  },
  {
    id: '39',
    name: 'ULTRA SHIELD SUN CREAM [SPF 50+ PA++++]',
    price: 250,
    description: '50g. Non-greasy and silky sunscreen with powerful UV protection. It is a non-greasy silky sunscreen that strongly defends skin against UV rays with a 7-filter broad-spectrum UV system, and supports skin recovery with hydrolyzed hyaluronic acid and lactobacillus ferment lysate. Niacinamide 2% and Ceramide NP brighten and strengthen the barrier. Free from oxybenzone and octinoxate. Key ingredients: 7-Filter UV System, Niacinamide 2%, Ceramide NP, Hydrolyzed Sodium Hyaluronate, Lactobacillus Ferment Lysate, Tropical Fruit Extracts (Pineapple, Papaya, Litchi, Guava). Dermatologically tested.',
    image: '/images/ultra/main.jpeg',
    images: JSON.stringify([
      '/images/ultra/s1.jpeg',
      '/images/ultra/s2.jpeg',
      '/images/ultra/s3.jpeg',
      '/images/ultra/s4.jpeg',
      '/images/ultra/s5.jpeg',
      '/images/ultra/s6.jpeg',
    ]),
    videoUrl: '/videos/ultra.mp4',
    category: 'Sun',
    inStock: true,
  },
  {
    id: '40',
    name: 'MULTI SUN CREAM [SPF 40 PA++]',
    price: 210,
    description: '40g. Non-greasy mild sunscreen with a skin glowing effect for daily sun protection. It is a non-greasy mild sunscreen that protects skin from UV A&B rays, and helps soothe the irritated skin from sun rays with palmitoyl pentapeptide-4, centella asiatica extract and botanical callus cultures extracts. Key ingredients: Palmitoyl Pentapeptide-4, Mannan, Glycerin, Rosa Damascena Callus Culture Extract, Vitis Vinifera (Grape) Callus Culture Extract, Centella Asiatica Extract, Scutellaria Baicalensis Root Extract, Lactobacillus/Soymilk Ferment Filtrate. Dermatologically tested.',
    image: '/images/sun/main.jpeg',
    images: JSON.stringify([
      '/images/sun/s1.jpeg',
      '/images/sun/s2.jpeg',
      '/images/sun/s3.jpeg',
      '/images/sun/s4.jpeg',
      '/images/sun/s5.jpeg',
      '/images/sun/s6.jpeg',
    ]),
    category: 'Sun',
    inStock: true,
  },
  {
    id: '41',
    name: 'SKIN CARING BLEMISH BALM CUSHION [SPF 50+ PA++++]',
    price: 300,
    description: 'Coverage, sun protection and skincare in one press of the puff, and Korea licenses it for all three at once. Five UV filters to SPF50+ PA++++, niacinamide 2% and adenosine 0.04%, with a 15 g refill already in the box.',
    image: '/images/cushion_2/main.jpeg',
    images: JSON.stringify([
      '/images/cushion_2/s1.jpeg',
      '/images/cushion_2/s2.jpeg',
      '/images/cushion_2/s3.jpeg',
      '/images/cushion_2/s4.jpeg',
      '/images/cushion_2/s5.jpeg',
      '/images/cushion_2/s6.jpeg',
    ]),
    videoUrl: '/videos/cushion.mp4',
    category: 'Cushion BB',
    inStock: true,
  },
  {
    id: '42',
    name: 'INTENSIVE BLEMISH BALM CREAM [SPF 30 PA++]',
    price: 250,
    description: '50g. Natural coverage cream that helps cover redness and express natural skin tone. It is a natural coverage cream that protects skin from the harmful environmental factors. It covers redness and blemishes after the dermatological treatment and helps express natural skin tone. Key ingredients: Arbutin 2%, Adenosine, Allantoin, Eucalyptus Globulus Leaf Oil, Perilla Ocymoides Seed Oil, Rumex Crispus Root Extract. Dermatologically tested.',
    image: '/images/BLEM.jpg',
    images: JSON.stringify(['/images/Second/bbbig.jpg']),
    category: 'Cushion BB',
    inStock: true,
  },
  {
    id: '43',
    name: 'HR³ MATRIX HAIR TONIC α',
    price: 290,
    description: '70ml. Functional tonic that improves the conditions of hair loss. It is a functional tonic approved as a \'functional product that improves the symptoms of hair loss\' by KFDA. It improves the scalp environment that causes hair loss and cools down the scalp heat, giving the sense of freshness to the scalp. Key ingredients: Copper Tripeptide-1, Sophora Japonica Extract, Caffeine, Menthol, Salicylic Acid, Allantoin, Centella Asiatica Extract, Scutellaria Baicalensis Root Extract, Licorice Root Extract. Dermatologically tested. KFDA approved as a functional product for improving hair loss symptoms. Efficacy test on improving hair loss.',
    image: '/images/hair_tonic/main-v2.jpeg',
    images: JSON.stringify([
      '/images/hair_tonic/s1.jpeg',
      '/images/hair_tonic/s2.jpeg',
      '/images/hair_tonic/s3.jpeg',
      '/images/hair_tonic/s4.jpeg',
      '/images/hair_tonic/s5.jpeg',
      '/images/hair_tonic/s6.jpeg',
    ]),
    category: 'Scalp/Hair',
    inStock: true,
    videoUrl: '/videos/hairt.mp4',
  },
  {
    id: '44',
    name: 'HR³ MATRIX MEDI SCALP SHAMPOO α',
    price: 340,
    description: '300ml. Functional shampoo that improves the conditions of hair loss. It is a functional shampoo approved as a \'functional product that improves the symptoms of hair loss\' by KFDA. It cools down scalp heat and helps control excess sebum on the scalp, making scalp and hair healthy. Key ingredients: Menthol, Caffeine, Copper Tripeptide-1, Biotin, Panthenol, Viscum Album (Mistletoe) Extract, Saccharomyces Cerevisiae Extract, Malt Extract, Acorus Calamus Root Extract, Serenoa Serrulata Fruit Extract, Piroctone Olamine. Dermatologically tested. KFDA approved as a functional product for improving hair loss symptoms.',
    image: '/images/shampoo/Main.jpg',
    images: '["/images/shampoo/S1.jpg","/images/shampoo/S2.jpg","/images/shampoo/S3.jpg","/images/shampoo/S4.jpg","/images/shampoo/S5.jpg","/images/shampoo/S6.jpg"]',
    category: 'Scalp/Hair',
    inStock: true,
    videoUrl: '/videos/shamp.mp4',
  },
  {
    id: '45',
    name: 'HR³ MATRIX HAIR SOLUTION α',
    price: 740,
    description: '4ml. Premium anti-hair loss ampoule for microneedling treatment. It is the premium anti-hair loss product supplying nutrients that fight against the factors causing hair loss. Special applicator with microneedles promotes nutrition delivery into scalp and helps build the right environment for healthy scalp. Components: Professional Kit - HAIR SOLUTION α 4ml(8ea), Dropper(2ea). Homecare Kit - HAIR SOLUTION α 4ml(8ea), microneedle applicator(1ea), Cleansing Brush(1ea), Disinfecting(1ea). Key ingredients: sh-Polypeptide-9 (VEGF), sh-Polypeptide-7 (somatotropin sequence), sh-Oligopeptide-1 (EGF), sh-Polypeptide-71 (VIP), Copper Tripeptide-1, Serenoa Serrulata Fruit Extract (Saw Palmetto), Biosaccharide Gum-4, Panthenol, Menthol, Black Complex, Brassica Oleracea Italica (Broccoli) Extract. Dermatologically tested. Research papers on the improvement of hair loss.',
    image: '/images/HHR.jpg',
    images: '["/images/Second/hs.jpg"]',
    category: 'Scalp/Hair',
    inStock: true,
    videoUrl: '/videos/hairs.mp4',
  },
  {
    id: '46',
    name: 'HR³ MATRIX SCALP PEELING α',
    price: 290,
    description: '100ml. Scalp peeling product with deep cleansing and heat cooling effects. It is a scalp peeling product which gives the deep cleansing effect for the scalp and refreshes the scalp with cooling effect. Key ingredients: Copper Tripeptide-1, Serenoa Serrulata Fruit Extract (Saw Palmetto), Salicylic Acid, Menthol, Black Complex, Camellia Sinensis Leaf Extract. Dermatologically tested.',
    image: '/images/scal.jpg',
    images: '["/images/Second/pp.jpg"]',
    category: 'Scalp/Hair',
    inStock: true,
  },
  {
    id: '47',
    name: 'HR³ MATRIX MESOPECIA KIT',
    price: 1100,
    description: 'Professional kit to allows a systematic hair loss treatment. It is a professional kit that allows a systematic hair loss treatment by combining microneedling with high performing cosmeceuticals. Components: SCALP PEELING α (100ml) - It is a light scalp peeling product which gives the deep cleansing effect for the scalp and refreshes the scalp with cooling effect. HAIR SOLUTION α (4ml x 6ea) + STAMP (ROLLER) - It is a premium anti-hair loss product supplying nutrients that fight against the factors causing hair loss. It is specially formulated for microneedling to build the right environment for healthy scalp. Key ingredients SCALP PEELING α: Copper Tripeptide-1, Serenoa Serrulata Fruit Extract (Saw Palmetto), Salicylic Acid, Menthol, Black Complex, Camellia Sinensis Leaf Extract. Key ingredients HAIR SOLUTION α: sh-Polypeptide-9 (VEGF), sh-Polypeptide-7 (somatotropin sequence), sh-Oligopeptide-1 (EGF), sh-Polypeptide-71 (VIP), Copper Tripeptide-1, Serenoa Serrulata Fruit Extract (Saw Palmetto), Biosaccharide Gum-4, Panthenol, Menthol, Black Complex, Brassica Oleracea Italica (Broccoli) Extract. Dermatologically tested. Research papers on the improvement of hair loss.',
    image: '/images/meso.jpg',
    images: null,
    category: 'Scalp/Hair',
    inStock: true,
  },
  {
    id: '48',
    name: 'Hair-GENTRON',
    price: 3300,
    description: 'An LED helmet for the scalp with air-pressure massage and a heating function, on a separate controller. Four light modes — red with infrared, blue, off, or all three together — and a timer set to ten, twenty or thirty minutes; the helmet switches itself off at the end. It weighs 1.0 kg and runs from the USB-C adaptor in the box or from four AA batteries, which are not included. Korea and the EU certify it as a household massage appliance under IEC/EN 60335-2-32; it is not a medical or phototherapy device, and it is not registered to treat hair loss. No efficacy study for this device is held, and the sales brochure\'s claims about the hair cycle are not carried. Model HGHY01, DTS MG Co., Ltd., made in Korea.',
    image: '/images/gen.jpg',
    images: null,
    videoUrl: '/videos/gentron.mp4',
    category: 'Device',
    inStock: true,
  },
  {
    id: '49',
    name: 'GENO-LED IR II',
    price: 5500,
    description: 'LED device that resolves complicated skin problems. It is a LLLT device which resolves complicated skin problems by irradiating lights with various wave lengths - 640nm (red), 423nm (blue), 532nm (green), 583nm (yellow) and 830nm (infrared). Features: Dome shape for less light loss, Excellent and powerful high-brightness and special near-infrared light SMD LED element, Light of different lengths (423nm~830nm) - Blue light, Green light, Yellow light, Red light + Infrared light, Available for the treatment of whole body – total care device, Effective for various types of skin problems, Gentle and safe treatment without pain, side effects and downtime. LED Specifications: Red (640nm) - 380ea, Blue (423nm) - 380ea, Green (532nm) - 380ea, Yellow (583nm) - 380ea, Infrared (830nm) - 190ea. Total: 1,710 LED and IR lamps. Effects: Cell regeneration, Anti-aging, Brightening, Soothing, Acne treatment, Improvement in edema/erythema, Hair loss care, Improvement in blood circulation. Face, Scalp, Body Total Care device.',
    image: '/images/LEDD.jpg',
    images: null,
    videoUrl: '/videos/led.mp4',
    category: 'Device',
    inStock: true,
  },
  {
    id: '50',
    name: 'EyeCell EYE ZONE CARE KIT',
    price: 980,
    description: '1 box. Registered four-piece EyeCell kit: Eye Contour Serum 10ml, GENOSYS Eye Roller 0.25mm, Eye Peptide Gel Patch 101g / 60 ea, Eye Contour Cream 20g. Cleanse, serum then a gentle roll, patches 20-40 minutes, then cream. Arbutin 2% and adenosine 0.04% on the serum and the cream. Niacinamide 2% and adenosine 0.04% on the patches. The eye roller is kit-only, not the 450-needle face roller. Dermatologically tested.',
    image: '/images/eye_kit/main.jpeg',
    images: null,
    category: 'Eye care',
    inStock: true,
    size: '1 box',
    videoUrl: '/videos/kit.mp4',
  },
  {
    id: '51',
    name: 'BIO-FERMENT AGE DEFYING POWDER MASK',
    price: 250,
    description: '300g. Professional modeling mask. Mix 40g of powder with water at 1 : 1.5, leave 15–20 minutes, peel. Diatomaceous earth base that holds moisture instead of drying out. Skin moisture nearly tripled in the DTS MG clinical trial, from 17.27 to 48.513. Dermatologically tested.',
    image: '/images/bio_ferment2/main.jpeg',
    images: JSON.stringify([
      '/images/bio_ferment2/s1.jpeg',
      '/images/bio_ferment2/s2.jpeg',
      '/images/bio_ferment2/s3.jpeg',
      '/images/bio_ferment2/s4.jpeg',
      '/images/bio_ferment2/s5.jpeg',
      '/images/bio_ferment2/s6.jpeg',
      '/images/bio_ferment2/s7.jpeg',
      '/images/bio_ferment2/Closing.jpeg',
    ]),
    category: 'Mask',
    inStock: true,
    size: '300g',
  },
  {
    id: '52',
    productNumber: '52',
    name: 'SKIN REBOOT PDRN MASK PACK',
    price: 400,
    description: 'Professional PDRN mask pack with salmon DNA technology for skin regeneration and repair. Ultra-slim fit sheets with 30 masks per container.',
    image: '/images/pdrn_mask/main.jpeg',
    images: null,
    category: 'Mask',
    inStock: true,
    size: '30 sheets',
  },
  {
    id: '53',
    productNumber: '53',
    name: 'INTENSIVE REPAIR COLLAGEN MASK',
    price: 36,
    description:
      'One 23g single-use non-woven sheet with a moisture-focused essence. Glycerin 10.052% and butylene glycol 8.010% form an 18.062% humectant base, supported by betaine 0.8%, sodium hyaluronate 0.5% and allantoin 0.2%. Apply for 15–20 minutes. Dermatologically tested. Contains Alcohol 0.1%, Parfum (Fragrance) 0.01% and soybean extract.',
    image: '/images/collagen_mask/Main.jpeg',
    images: null,
    category: 'Mask',
    inStock: true,
    size: '23 g / 1 sheet',
  },
  {
    id: '54',
    productNumber: '54',
    name: 'HOLIDAY KIT',
    price: 650,
    description:
      'Discontinued seasonal GENOSYS gift box with Snow O₂ Cleanser 180 ml, Multi Vita Radiance Serum 30 ml, Multi Vita Radiance Cream 50 g and a GENOSYS mirror. Use cleanser, then serum, then cream; the mirror is an accessory. The three skincare products are individually dermatologically tested. Currently out of stock.',
    image: '/images/Hol_kit_v2.jpg',
    images: null,
    category: 'kits',
    inStock: false,
    size: '1 box',
  },
  {
    id: '61',
    productNumber: '61',
    name: 'HR³ MATRIX SCALP BRUSH',
    price: 50,
    description: '1 pc. Specialized scalp care brush for daily massage and treatment preparation. It is a gentle, non-invasive scalp brush designed primarily for scalp care, stimulation, and supporting hair health. The Scalp Brush promotes better circulation, exfoliation, and product absorption on the scalp. Features: Ergonomic design with soft, flexible silicone bristles optimized for scalp use without causing irritation. Dual Use - Wet use: Apply shampoo, then gently massage in circular motions to deeply cleanse, remove buildup, and stimulate blood flow. Dry use: On clean, dry hair/scalp for invigorating massage to boost circulation and relax the scalp. Integration with HR³ MATRIX Line: Pairs excellently with HR³ MATRIX Clinical Hair Tonic, Scalp Peeling, and Hair Solution α to enhance nutrient delivery and overall scalp health. Benefits: Improves blood circulation to nourish follicles, helps reduce dandruff and excess sebum, stimulates scalp for healthier hair growth environment, prepares scalp for microneedling treatments. Manufactured in South Korea.',
    image: '/images/brush_o/Main2.jpeg',
    images: JSON.stringify([
      '/images/brush_o/s1.jpeg',
      '/images/brush_o/s2.jpeg',
      '/images/brush_o/s3.jpeg',
      '/images/brush_o/s4.jpeg',
      '/images/brush_o/s5.jpeg',
      '/images/brush_o/s6.jpeg',
      '/images/brush_o/s7.jpeg',
    ]),
    category: 'Scalp/Hair',
    inStock: true,
    size: '1 pc',
    videoUrl: '/videos/brush.mp4',
  },
  {
    id: '63',
    name: 'REVITA GLOW BLEMISH BALM CREAM [SPF 38 PA+++]',
    price: 250,
    description: 'Genosys REVITA GLOW BLEMISH BALM CREAM [SPF 38 PA+++]. 50g. An instantly revitalizing complexion formula that enhances the skin\'s natural luminosity for a clear, glass-like glow. A regenerative BB cream infused with a complex of 10 vitamins and 7 herbal extracts, instantly energizing the skin while naturally covering skin imperfections. Available in two shades: #01 Bright for an illuminating glow with a clear, radiant complexion, and #02 Natural for a refined glow with a natural, healthy-looking complexion. UV protection (SPF 38 PA+++). Long-lasting, transfer-resistant radiant wear. Key ingredients: 10 Vitamin Complex (Vitamins A, B1, B2, B3, B4, B5, B7, B9, C, E), Herb Complex (Camellia Sinensis Leaf Extract, Rosmarinus Officinalis Leaf Extract, Centella Asiatica Extract, Tremella Fuciformis Extract, Chamomilla Recutita Flower Extract, Polygonum Cuspidatum Root Extract, Scutellaria Baicalensis Root Extract, Glycyrrhiza Uralensis Root Extract), Niacinamide 2%, Adenosine, Erythritol. Effects: Revitalizing, Hydrating, Soothing & Barrier Protecting, Coverage. Dermatologically tested.',
    image: '/images/revita/main.jpg',
    images: JSON.stringify(['/images/revita/s1.jpg', '/images/revita/s2.jpg', '/images/revita/s3.jpg', '/images/revita/s4.jpg']),
    category: 'Cream, Sun, Cushion BB',
    inStock: true,
    size: '50g',
    videoUrl: '/videos/revita.mp4',
  },
  {
    id: '60',
    productNumber: '60',
    name: 'Bio Meso PDRN Ampoule 60000',
    price: 600,
    description:
      `The Genosys Bio Meso PDRN Expert Ampoule 60000 is a specialized skincare treatment ampoule designed for bio-meso therapy, a no-needle microneedling approach. It utilizes microscopic spicules (needle-like components extracted from freshwater sponges) to create temporary microchannels in the skin, enhancing the absorption of active ingredients without the need for actual needles. This product is enriched with the uniquely formulated BIO-MESO™ PDRN (Polydeoxyribonucleotide), panthenol, and an anti-aging complex to regenerate skin and strengthen the skin barrier.

It features a 2-way system for customizable care:
• Professional Use (Expert Ampoule 60000): Higher concentration for clinic-based treatments.
• Home-Use (Homecare Ampoule 5000): Lower concentration for ongoing maintenance.

The ampoule functions as a spicule peeling or bio-meso peeling treatment, inducing a peel-off effect on the skin. It contains a significantly higher concentration of spicules compared to other products, delivering intensive results.`,
    image: '/images/6000/main.jpg',
    images: null,
    category: 'Bio Meso',
    inStock: true,
    size: '3ml x 4 ampoules',
    isPriceOnRequest: false,
    disclaimer: 'For Professional/Clinic Use Only. This product requires proper training and should only be used by licensed aestheticians or dermatologists.',
    videoUrl: '/videos/60000.mp4',
  },
  {
    id: '64',
    productNumber: '64',
    name: 'Hair Stamp For HAIRGEN BOOSTER',
    price: 600,
    description: `The applicator the GENOSYS HairGen Booster runs on. Each stamp head carries 52 ultra-fine microneedles that open temporary micro-channels in the scalp, and it screws onto a sealed HR³ MATRIX HAIR SOLUTION α vial so the solution feeds through the head while the device works — the liquid goes in as the needles open the way, rather than being rubbed on afterwards.

Mounted on the Booster it stamps automatically, at a rate you set rather than one your hand drifts into, which is the practical difference between a powered handpiece and a hand roller.

Eight stamps per box. One stamp and one fresh ampoule per treatment — it is single use, it is not a cleanable part, and it is personal. Made in South Korea.`,
    image: '/images/needles2/Main.jpeg',
    images: JSON.stringify([
      '/images/needles2/s1b.jpeg',
      '/images/needles2/s2.jpeg',
      '/images/needles2/s3.jpeg',
      '/images/needles2/s4.jpeg',
      '/images/needles2/s5.jpeg',
      '/images/needles2/closing.jpeg',
    ]),
    category: 'Scalp/Hair',
    inStock: true,
    size: '1 box - 8 pcs of hair stamp',
    isPriceOnRequest: false,
  },
  {
    id: '65',
    productNumber: '65',
    name: 'Bio-Meso PDRN Homecare Ampoule 5000',
    price: 300,
    description: `A specialized homecare treatment ampoule, enriched with the uniquely formulated BIO-MESO™ PDRN, panthenol, and an anti-aging complex to regenerate skin and strengthen the skin barrier.

BIO-MESO™ PDRN coated spicules have a needle-shaped structure that enables direct skin penetration, providing a bio-peeling effect that promotes skin turnover and delivers excellent skin regeneration benefits — all without classic needles. Designed for ongoing, gentle home care to maintain and reinforce results between professional treatments.`,
    image: '/images/pdrn_5000_new/Main.jpeg',
    images: null,
    category: 'Bio Meso',
    inStock: true,
    size: '50ml',
    isPriceOnRequest: false,
    videoUrl: '/videos/5000.mp4',
  },
]
