import { Product } from '@/types'

export const products: Product[] = [
  {
    id: '1',
    name: 'Microneedle Roller',
    price: 230,
    description: 'Professional-grade microneedling device with patented Diskneedle Therapy System (DTS) for enhanced skin rejuvenation. Features 450 ultra-thin needles (25% thinner than competitors) for superior product absorption and minimal skin trauma. Stimulates natural collagen production and improves skin texture. Manufactured in South Korea.',
    image: '/images/genosys-microneedling-devices.jpg',
    images: JSON.stringify(['/images/genosys-microneedling-devices.jpg', '/images/Second/roller1.jpg', '/images/Second/roller_stamp2.jpg']),
    category: 'Microneedling',
    inStock: true,
    size: '0.25mm',
  },
  {
    id: '2',
    name: 'Needle Pen-K',
    price: 1450,
    description: 'Skin stimulator to promote collagen production and transdermal nutrient delivery. GENOSYS NEEDLE PEN-K is an automatic device for microneedling therapy. It increases the absorption rate of active ingredients of skin care products by creating physical pathways through skin. And it promotes collagen and elastin induction through natural wound healing process of skin. Manufactured in South Korea.',
    image: '/images/Needle-pen.jpg',
    images: null,
    category: 'Microneedling',
    inStock: true,
    size: '1 Device',
  },
  {
    id: '3',
    name: 'HairGen BOOSTER',
    price: 1800,
    description: 'Auto-microneedling LED device for scalp treatment. HR³ MATRIX HAIR SOLUTION α - It is the premium anti-hair loss product supplying nutrients that fight against the factors causing hair loss. HR³ MATRIX HAIR STAMP - Patented delivery enhancer with microneedles leads to scalp regeneration and collagen production by promoting natural wound healing process of skin and increases skin permeability of nutritive ingredients. Manufactured in South Korea.',
    image: '/images/Booster.jpg',
    images: null,
    category: 'Device',
    inStock: true,
  },
  {
    id: '4',
    name: 'POWER SOLUTION HES',
    price: 580,
    description: '2ml x 10ea. Hydrating and firming ampoule for microneedling treatment. Dermatologically tested. Efficacy test on skin hydration. Features: It is a hydrating and firming ampoule specially formulated for microneedling treatment that provides long-lasting moisturizing and plumping effects, and relieves skin irritation with sh-polypeptide-7 (recombinant human peptide), hyaluronic acid and BIOPHYTEX™. Key Ingredients: Hyaluronic Acid, Panthenol, Phytosphingosine, BIOPHYTEX™, Copper Tripeptide-1, sh-Polypeptide-7, Palmitoyl Tetrapeptide-7. Manufactured in South Korea.',
    image: '/images/hes_power/main.jpeg',
    images: JSON.stringify([
      '/images/hes_power/s1new.jpeg',
      '/images/hes_power/s2.jpeg',
      '/images/hes_power/s3.jpeg',
      '/images/hes_power/s4.jpeg',
      '/images/hes_power/s5.jpeg',
      '/images/hes_power/s6.jpeg',
      '/images/hes_power/s7.jpeg',
    ]),
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '5',
    name: 'POWER SOLUTION CVS',
    price: 580,
    description: '2ml x 10ea. Skin revitalizing ampoule for microneedling treatment. Dermatologically tested. Efficacy test on moisturizing. Features: It is a skin revitalizing ampoule specially formulated for microneedling treatment that supplies nutrients to the skin, soothes and hydrates skin with sh-polypeptide-7 (recombinant human peptide), botanical stem cell extracts and panthenol. Skin-Friendly Formulation: Not containing harmful additives considering the increased skin permeability by microneedling (no-paraben, ethanol, artificial fragrance, artificial pigment, sulfate). Dermatologically tested. Key Ingredients: sh-polypeptide-7, Palmitoyl Tripeptide-1, Lactobacillus/Soymilk Ferment Filtrate, Panthenol, Allantoin, Hyaluronic Acid, Vitis Vinifera (Grape) Callus Culture Extract, Rosa Damascena Callus Culture Extract, Lactobacillus Ferment Lysate Filtrate. Manufactured in South Korea.',
    // The squared hero, matching the database. CVS.jpg is the same shot at 956x662
    // and leaves a hard-cornered band above and below it in the square gallery
    // stage. The main image is deliberately not repeated in `images`: web and
    // mobile both prepend it.
    image: '/images/cvs-hero.jpg',
    images: JSON.stringify(['/images/Second/cvs_big1.jpg', '/images/Second/cvs_big2.jpg']),
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '6',
    name: 'POWER SOLUTION CTS',
    price: 580,
    description: 'CTS is Cytokine Concentrate Solution. The carton function is improvement of skin texture: it helps the skin retain its natural elasticity and increases the strength of skin. 2 ml × 10 sealed glass vials. 5-Free. Dermatologically tested. Made in Korea by DTS MG.',
    // The squared hero, matching the database. CTS.jpg is the same shot at 956x662
    // and leaves a hard-cornered band above and below it in the square gallery
    // stage. The main image is deliberately not repeated in `images`: web and
    // mobile both prepend it.
    image: '/images/cts-hero.jpg',
    images: JSON.stringify(['/images/Second/cts_big.jpg', '/images/Second/cts_big2.jpg']),
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '7',
    name: 'POWER SOLUTION PCS',
    price: 580,
    description: '2ml x 10ea. Anti-blemish ampoule for microneedling treatment. Dermatologically tested. Efficacy test on improving excessive sebum production. Features: It is an anti-blemish ampoule specially formulated for microneedling treatment that controls excessive oil and sebum production and helps prevent skin breakout with sh-polypeptide-7 (recombinant human peptide), with hazel leaf extract and houttuynia cordata extract. Skin-Friendly Formulation: Not containing harmful additives considering the increased skin permeability by microneedling (no-paraben, ethanol, artificial fragrance, artificial pigment, sulfate). Key Ingredients: sh-Polypeptide-7, Acetyl Hexapeptide-8, Palmitoyl Hexapeptide-12, Palmitoyl Tripeptide-1, Hamamelis Virginiana (Witch Hazel) Leaf Extract, Vitis Vinifera (Grape) Callus Culture Extract, Rosa Damascena Callus Culture Extract, Pinus Radiata Bark Extract, Houttuynia Cordata Extract. Manufactured in South Korea.',
    image: '/images/PCS.jpg',
    images: JSON.stringify(['/images/PCS.jpg', '/images/Second/pcs_big1.jpg', '/images/Second/pcs_big2.jpg']),
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '8',
    name: 'POWER SOLUTION SWS',
    price: 580,
    description: 'SWS is Skin Depigmenting & Whitening Solution. Korea registers it as a whitening functional cosmetic with arbutin 2% as the principal ingredient. Helps improve pigmentation, even skin tone and brighten the skin surface. 2 ml × 10 sealed glass vials. 5-Free. Dermatologically tested. Made in Korea by DTS MG.',
    // The squared hero, matching the database. SWS.jpg is the same shot at 956x662
    // and leaves a hard-cornered band above and below it in the square gallery
    // stage. The main image is deliberately not repeated in `images`: web and
    // mobile both prepend it.
    image: '/images/sws-hero.jpg',
    images: JSON.stringify(['/images/Second/sws_big1.jpg', '/images/Second/sws_big2.jpg']),
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '9',
    name: 'POWER SOLUTION AWS',
    price: 580,
    description: 'AWS is Anti-Wrinkle Solution. Korea registers it as a wrinkle-improving functional cosmetic with adenosine 0.04% as the principal ingredient. Reduces the appearance of wrinkles and improves skin firmness. 2 ml × 10 sealed glass vials. 5-Free. Dermatologically tested. Made in Korea by DTS MG.',
    // The squared hero, matching the database. AWS.jpg is the same shot at 956x662
    // and leaves a hard-cornered band above and below it in the square gallery
    // stage. The main image is deliberately not repeated in `images`: web and
    // mobile both prepend it.
    image: '/images/aws-hero.jpg',
    images: JSON.stringify(['/images/Second/aws1.jpg', '/images/Second/aws2.jpg']),
    category: 'PRO Solution',
    inStock: true,
  },
  {
    id: '10',
    name: 'SNOW O₂ CLEANSER',
    price: 330,
    description: '180ml (Homecare) / 500ml (Professional). All in one gentle cleanser with oxygen bubbles. It is a gentle and effective cleanser which gives an excellent treatment sensation. Naturally generated oxygen bubbles clean make-up dirts and skin impurities without excessive cleansing movement and irritation to skin. Features oxygen therapy mechanism for deep cleansing and nutrifying. Key ingredients: Phytolex SC, MultiEx Phytrogen, Methyl Perfluoroisobutyl Ether. Apply the product to a dry face, avoiding the eyes, and wait for oxygen bubbles to come up. Wet your fingers to spread the product and let bubbles form again. After they fully develop, massage gently with wet hands, then rinse with lukewarm water. Dermatologically tested.',
    image: '/images/cleanser/main_clean.jpeg',
    images: JSON.stringify([
      '/images/cleanser/S1.jpg',
      '/images/cleanser/S2.jpg',
      '/images/cleanser/S3.jpg',
      '/images/cleanser/S4.jpg',
      '/images/cleanser/S5.jpg',
      '/images/cleanser/S6.jpg',
    ]),
    category: 'Cleanser',
    inStock: true,
    size: '180ml',
    videoUrl: '/videos/cleanser.mp4',
  },
  {
    id: '11',
    name: 'SKIN DEFENDER LIP & EYE MAKEUP REMOVER',
    price: 290,
    description: '200ml. Fresh, non-greasy lip & eye makeup remover. It is a fresh, non-greasy lip & eye makeup remover. Biphasic layer of essence layer with vitamins, firming peptides and oil layer with a strong cleansing power turn into emulsion which cleans the delicate lip and eye area without irritation. Key ingredients: 10 Vitamin Complex, Palmitoyl Tripeptide-5, Acetyl Tetrapeptide-5, Saccharide Hydrolysate, Rosa Damascena Flower Water, Daucus Carota Sativa (Carrot) Root Extract, Brassica Oleracea Italica (Broccoli) Extract, Daucus Carota Sativa (Carrot) Seed Oil, Hippophae Rhamnoides Oil. Usage: Shake well before use. Dermatologically tested.',
    image: '/images/remover/Main2.jpg',
    images: JSON.stringify([
      '/images/remover/S1b.jpg',
      '/images/remover/S2b.jpg',
      '/images/remover/S3b.jpg',
      '/images/remover/S4b.jpg',
      '/images/remover/S5b.jpg',
      '/images/remover/S6b.jpg',
    ]),
    category: 'Cleanser',
    inStock: true,
    size: '200ml',
    videoUrl: '/videos/remover.mp4',
  },
  {
    id: '12',
    name: 'EPI TURNOVER BOOSTING PEELING GEL',
    price: 250,
    description: '100g. Enzyme + cellulose peeling gel. On clean, dry skin, massage for up to one minute; the dead cells clump and rinse away with tepid water. Cellulose 3% is the roll you feel. Once or twice a week. Dermatologically tested.',
    image: '/images/epi/main.jpeg',
    images: JSON.stringify([
      '/images/epi/s1.jpeg',
      '/images/epi/s2.jpeg',
      '/images/epi/s3.jpeg',
      '/images/epi/s4.jpeg',
      '/images/epi/s5.jpeg',
      '/images/epi/s6.jpeg',
    ]),
    category: 'Peeling',
    inStock: true,
    videoUrl: '/videos/epi.mp4',
  },
  {
    id: '13',
    name: 'SKIN RENEWAL PEELING SYSTEM (SRS)',
    price: 810,
    description: '2ml x 10ea. Professional peeling with naturally occurring AHA acids. It is a professional peeling system for smoother, brighter and more even skin tone. Naturally occurring acids found in fruits and other foods help remove dead cells on the surface of the skin, encouraging cell turnover and bringing new healthy cells to the surface. Key ingredients: Naturally occurring AHA complex (Glycolic Acid, Lactic Acid, Mandelic Acid, Phytic Acid), sh-Polypeptide-7, Scutellaria Baicalensis Root Extract, Houttuynia Cordata Extract, Chamaecyparis Obtusa Water. Dermatologically tested.',
    image: '/images/SRS.jpg',
    images: null,
    category: 'Peeling, PRO Solution',
    inStock: true,
  },
  {
    id: '14',
    name: 'MICROBIOME ENERGY INFUSING MIST',
    price: 160,
    description: '80ml. Revitalizing mist that gives skin natural glow and radiance. It revitalizes skin and enhances skin\'s natural strength with unique blend of pre/probiotics that corrects the balance of skin microbiome and hyaluronic acid complex that replenishes the skin\'s moisture barrier. Key ingredients: CUREBIOME (Probiotics & Prebiotics), FENSEBIOME™ (Acetyl Heptapeptide-4), Hyaluronan Multi-Complex, Butyrospermum Parkii (Shea) Butter. Dermatologically tested. Efficacy test on skin hydration.',
    image: '/images/mist/main2.jpeg',
    images: null,
    category: 'Toner/Mist',
    inStock: true,
  },
  {
    id: '15',
    name: 'INTENSIVE PROBLEM CONTROL TONER',
    price: 260,
    description: '200ml (Homecare) / 500ml (Professional). Anti-blemish toner for acne-prone skin. It helps remove excess oil and sebum for blemish-prone skin while adding quick hydration to skin with patented Anti Sebum P complex, zinc PCA, tea tree extract and panthenol. Key ingredients: Anti Sebum P, Tea Tree Extract, Tea Tree Leaf Oil, Rosmarinus Officinalis (Rosemary) Leaf Extract, Zinc PCA, Tannic Acid, Salicylic Acid (BHA), SNOW ICE. Dermatologically tested. Efficacy test on improving excessive sebum production.',
    image: '/images/problem/Main.jpg',
    images: JSON.stringify([
      '/images/problem/S1.jpg',
      '/images/problem/S2.jpg',
      '/images/problem/S3.jpg',
      '/images/problem/S4.jpg',
      '/images/problem/S5.jpg',
      '/images/problem/S6.jpg',
    ]),
    category: 'Toner/Mist',
    inStock: true,
    size: '200ml',
  },
  {
    id: '16',
    name: 'SNOW BOOSTER',
    price: 260,
    description: '200ml (Homecare) / 1000ml (Professional). Daily moisturizing and skin refining toner for all skin types. It is a daily toner used for all skin types that contains various botanical extracts to moisturize and soothe skin. It helps refining the skin with balancing pH level after cleansing. Key ingredients: Phytolex SC, Nelumbo Nucifera Flower Extract, Lactobacillus/Pumpkin Ferment Extract, Betaine. Dermatologically tested. Efficacy test on skin hydration.',
    image: '/images/Second/main_booster.jpg',
    images: JSON.stringify(['/images/Second/main_booster.jpg', '/images/Second/main_booster2.png']),
    category: 'Toner/Mist',
    inStock: true,
    size: '200ml',
    videoUrl: '/videos/booster.mp4',
  },
  {
    id: '17',
    name: 'EyeCell EYE CONTOUR SERUM',
    price: 370,
    description: '10ml. Intensive all-in-one eye serum for deep wrinkles, dark circles and eye puffs. Arbutin 2% and Adenosine 0.04% are the Korean functional pair. Morning and evening, pat and leave on. Dermatologically tested. Avoid during pregnancy and lactation.',
    image: '/images/eye_serum/main.jpeg',
    images: JSON.stringify([
      '/images/eye_serum/s1.jpeg',
      '/images/eye_serum/s2.jpeg',
      '/images/eye_serum/s3.jpeg',
      '/images/eye_serum/s4.jpeg',
      '/images/eye_serum/s5.jpeg',
      '/images/eye_serum/s6.jpeg',
      '/images/eye_serum/s7.jpeg',
    ]),
    category: 'Eye care',
    inStock: true,
  },
  {
    id: '18',
    name: 'MOISTURE REPLENISHING HYALURON SERUM',
    price: 330,
    description: '30ml. Coconut water-based hydrating serum with hyaluronic complex and various mushrooms. It is a coconut water-based serum that quickly replenishes moisture from the deep inside and infuses skin with multi depth hydration with hyaluronic acid complex and various mushrooms. 4 STEP Skin Hydration: 1) Electrolytes in coconut water lead moisture into the skin and balance the water content. 2) By stimulating the formation of aqua-porin, it opens water-transport channel, and attracts moisture to the skin with moisture magnet ingredient. 3) Low/middle molecular weight hyaluronic acids replenish moisture layer by layer from the inside of the skin. 4) High molecular weight hyaluronic acid prevents moisture evaporation by forming moisture barrier on the skin surface. Mushrooms nourish and protect skin with powerful anti-inflammatory and antioxidant properties. Key ingredients: Cocos Nucifera (Coconut) Water, Hyaluronan Multi-Complex, Glyceryl Glucoside (aquaporin), PENTAVITIN™ (moisture magnet), Tremella Fuciformis, Mushroom Complex, Solanum Melongena (Eggplant) Fruit Extract. Dermatologically tested. Efficacy test on inner hydration.',
    image: '/images/hyaluron_serum/main.jpeg',
    images: JSON.stringify([
      '/images/hyaluron_serum/s1.jpeg',
      '/images/hyaluron_serum/s2.jpeg',
      '/images/hyaluron_serum/s3.jpeg',
      '/images/hyaluron_serum/s4.jpeg',
      '/images/hyaluron_serum/s5.jpeg',
      '/images/hyaluron_serum/s6.jpeg',
    ]),
    category: 'Serum',
    inStock: true,
    videoUrl: '/videos/hs_cream_serum.mp4',
  },
  {
    id: '19',
    name: 'ALL FOR SENSITIVE SERUM',
    price: 330,
    description: '30ml. Serum for sensitive, reactive skin. Relieves, protects and moisturizes — MultiEx BSASM® Plus at 1%, with betaine, allantoin and hyaluronic acid. Morning and night. Dermatologically tested.',
    image: '/images/sensitive_serum/main.jpeg',
    images: JSON.stringify([
      '/images/sensitive_serum/s1.jpeg',
      '/images/sensitive_serum/s2.jpeg',
      '/images/sensitive_serum/s3.jpeg',
      '/images/sensitive_serum/s4.jpeg',
      '/images/sensitive_serum/s5.jpeg',
      '/images/sensitive_serum/s6.jpeg',
    ]),
    category: 'Serum',
    inStock: true,
    videoUrl: '/videos/all_serum.mp4',
  },
  {
    id: '20',
    name: 'PROBLEM CONTROL SERUM',
    price: 330,
    description: '30ml. Anti-blemish serum for combination, oily acne-prone skin. It helps fight skin breakouts by regulating excessive oil and sebum and refines skin texture for a healthier-looking clear skin with a sebum regulating ingredient – zinc PCA and willow bark extract. Key ingredients: Zinc PCA, Salix Nigra (Willow) Bark Extract, Trehalose, Panthenol, Phytolex SC, Allantoin, Beta-Glucan. Dermatologically tested. Efficacy test on improving excessive sebum production.',
    image: '/images/problems_serum/main.jpeg',
    images: JSON.stringify([
      '/images/problems_serum/s1.jpeg',
      '/images/problems_serum/s2.jpeg',
      '/images/problems_serum/s3.jpeg',
      '/images/problems_serum/s4.jpeg',
      '/images/problems_serum/s5.jpeg',
      '/images/problems_serum/s6.jpeg',
    ]),
    category: 'Serum',
    inStock: true,
    size: '30ml',
    videoUrl: '/videos/problem_serum.mp4',
  },
  {
    id: '21',
    name: 'MULTI VITA RADIANCE SERUM',
    price: 330,
    description: '30ml. Skin brightening serum with multi vitamins and patented melanin care complex, MELAZERO®. It helps even skin tone, revive skin\'s natural brightness and radiance with multi vitamins and patented melanin care complex, MELAZERO®. It gives skin a natural glow by forming a moisturizing barrier thanks to panthenol-rich formula. Key ingredients: 3-O-Ethyl Ascorbic Acid (derivative of pure vitamin C), VITA 12 Complex, MELAZERO®, Panthenol, Niacinamide, Glutathione, Gluconolactone (PHA), Anti-inflammatory Herb Complex. Dermatologically tested. Efficacy test on improving skin surface melanin.',
    image: '/images/radiance_serum/main.jpeg',
    images: null,
    category: 'Serum',
    inStock: true,
    size: '30ml',
    videoUrl: '/videos/radiance_serum.mp4',
  },
  {
    id: '22',
    name: 'MULTI FUNCTIONAL ANTI-WRINKLE SERUM',
    price: 330,
    description: '30ml. Anti-aging serum with bakuchiol, a natural alternative to retinol and anti-wrinkle peptide complex. It is an anti-aging serum that helps visibly smooth the signs of wrinkles and reinforces skin firmness with a nourishing ingredient – bakuchiol, a natural alternative to retinol and anti-wrinkle peptide complex. Clinical study on improvement of skin age index, P&K Skin Research Center, Feb. 22 to May 13, 2024, 24 adult women aged 30~59 years. Key ingredients: Bakuchiol, Anti-aging Peptide 6, Lipid Barrier Liposome (Ceramide NP, Cholesterol, Phytosphingosine), Collagen, Elastin, Propolis Extract, Adenosine, Niacinamide. Dermatologically tested. Efficacy test on improving wrinkles and skin tone balance.',
    image: '/images/multif_serum/main.jpeg',
    images: JSON.stringify([
      '/images/multif_serum/main.jpeg',
      '/images/multif_serum/s1.jpeg',
      '/images/multif_serum/s2.jpeg',
      '/images/multif_serum/s3.jpeg',
      '/images/multif_serum/s4.jpeg',
      '/images/multif_serum/s5.jpeg',
      '/images/multif_serum/s6.jpeg',
    ]),
    category: 'Serum',
    inStock: true,
    videoUrl: '/videos/multif_serum.mp4',
  },
  {
    id: '23',
    name: 'ND Cell ANTI-WRINKLE CREAM',
    price: 370,
    description: '50g. Anti-aging cream for neck and decollete area. It targets the special needs of the delicate skin around the neck and decollete area. It lifts and firms skin and refine the skin texture. It also has an excellent effect of depigmentation. Key ingredients: Copper Tripeptide-1, sh-polypeptide 7, Acetyl Hexapeptide-8, Palmitoyl Hexapeptide-12, Palmitoyl Tripeptide-1, Vitamin Complex (vitamin A, B5, C, E) Hyaluronic Acid, Ceramide, Squalane. Dermatologically tested. Efficacy test on improving wrinkles.',
    image: '/images/ND.jpg',
    images: JSON.stringify(['/images/ND.jpg', '/images/Second/nd_big1.jpg']),
    category: 'Cream',
    inStock: true,
    size: '50g',
  },
  {
    id: '24',
    name: 'EyeCell EYE CONTOUR CREAM',
    price: 370,
    description: '20g. Daily all-in-one eye cream for wrinkles, dark circles and puffiness. Arbutin 2% and Adenosine 0.04% are the Korean functional pair. Morning and evening, tap and leave on. Dermatologically tested. Avoid during pregnancy and lactation. Contains peanut oil.',
    image: '/images/eye_cream/main.jpeg',
    images: JSON.stringify([
      '/images/eye_cream/s1.jpeg',
      '/images/eye_cream/s2.jpeg',
      '/images/eye_cream/s3.jpeg',
      '/images/eye_cream/s4.jpeg',
      '/images/eye_cream/s5.jpeg',
      '/images/eye_cream/s6.jpeg',
    ]),
    category: 'Eye care',
    inStock: true,
  },
  {
    id: '25',
    name: 'SOOTHING REPAIR POSTCREAM',
    price: 204,
    description: '20g (Homecare) / 100g (Professional). Regenerating cream for healthy skin recovery after professional treatment. It is a regenerating cream that promotes skin recovery after professional treatment. It helps irritated skin rapidly recover from redness, erythema and edema after the dermatological operations or any other irritations and promotes healthy rejuvenation. Key ingredients: sh-Polypeptide-7, Centella Complex (Asiaticoside, Madecassic Acid, Asiatic Acid), Dipotassium Glycyrrhizate, Panthenol, Vitis Vinifera (Grape) Callus Culture Extract, Rosa Damascena Callus Culture Extract, Scutellaria Baicalensis Root Extract. Dermatologically tested. Efficacy test on protection of the skin against damage induced by physical stimuli.',
    image: '/images/SRC.jpg',
    images: null,
    category: 'Cream',
    inStock: true,
    size: '20g',
    videoUrl: '/videos/soothing-repair-postcream-20260806.mp4',
  },
  {
    id: '26',
    name: 'EGF REPAIR OXYMASK CREAM',
    price: 290,
    description: '50g. Oxygen bubbling mask cream with skin regenerating ingredients – EGF and madecassoside. It is a unique oxygen bubbling mask cream which makes dull & stressed skin healthy with skin regenerating ingredients such as EGF and madecassoside. It is a "S.O.S" cream that can be effectively used for damaged skin by various causes. Key ingredients: sh-Oligopeptide-1 (EGF), Madecassoside, Copper Tripeptide-1, SEPITONIC M3 (Mineral Complex), Salmon Oil, Adenosine. Dermatologically tested. Efficacy test on skin soothing effect against external stimulus.',
    image: '/images/EGF.jpg',
    images: null,
    category: 'Cream',
    inStock: false,
    isHidden: true, // Discontinued Jul 2026
  },
  {
    id: '27',
    name: 'SKIN BARRIER PROTECTING CREAM',
    price: 450,
    description: '100g. Skin barrier strengthening cream with enriched ceramide and amino acid complex. It encourages healthy and soft skin by promoting water retention and protecting skin barrier with ceramide NP, botanical extracts and amino acid (NMF) complex. Key ingredients: Ceramide NP, Amino Acid (NMF) Complex, Butyrospermum Parkii (Shea) Butter, Macadamia Integrifolia Seed Oil. Dermatologically tested. Efficacy test on improving skin restorative force.',
    image: '/images/skin_barr/main.jpeg',
    images: JSON.stringify([
      '/images/skin_barr/s1.jpeg',
      '/images/skin_barr/s2.jpeg',
      '/images/skin_barr/s3.jpeg',
      '/images/skin_barr/s4.jpeg',
      '/images/skin_barr/s5.jpeg',
      '/images/skin_barr/s6.jpeg',
    ]),
    category: 'Cream',
    inStock: true,
    size: '100g',
    videoUrl: '/videos/barrier2.mp4',
  },
  {
    id: '28',
    name: 'INTENSIVE HYDRO SOOTHING CREAM',
    price: 290,
    description: '50g (Homecare) / 250g (Professional). Soothing and moisturizing gel with aloe vera, snail secretion filtrate. It calms down skin irritation and provides long-lasting hydration to the skin with aloe vera, snail secretion filtrate and hyaluronic acid. Key ingredients: Aloe Barbadensis Leaf Extract, Snail Secretion Filtrate, Hyaluronic Acid, Lactobacillus/Pumpkin Ferment Extract, Beta-Glucan, Phytolex SC. Dermatologically tested. Efficacy test on skin hydration.',
    image: '/images/HSC.jpg',
    images: null,
    category: 'Cream',
    inStock: true,
  },
  {
    id: '29',
    name: 'MOISTURE REPLENISHING HYALURON CREAM',
    price: 290,
    description: '50g (Homecare) / 250g (Professional). Long-lasting moisturizer with hyaluronic complex and various mushrooms. It is a refreshing moisturizer that strengthens moisture barrier and provides long-lasting hydration to skin with hyaluronic acid complex and various mushrooms. 4 STEP Skin Hydration: 1) When it touches the skin, natural-origin cooling agents help lower the skin temperature and make skin refreshed. 2) By stimulating the formation of aqua-porin, it opens water-transport channel, and attracts moisture to the skin with moisture magnet ingredient. 3) Low/middle molecular weight hyaluronic acids replenish moisture layer by layer form the inside of the skin. 4) High molecular weight hyaluronic acid prevents moisture evaporation by forming moisture barrier on the skin surface. Mushrooms nourish and protect skin with powerful anti-inflammatory and antioxidant properties. Key ingredients: Hyaluronan Multi-Complex, Glyceryl Glucoside (aquaporin), PENTAVITIN™ (moisture magnet), Tremella Fuciformis, Mushroom Complex, Solanum Melongena (Eggplant) Fruit Extract, Aloe Barbadensis Flower Extract, Natural-Origin Cooling Agent (Xylitol, Erythritol). Dermatologically tested.',
    image: '/images/hyaluron/main.jpeg',
    images: null,
    category: 'Cream',
    inStock: true,
    videoUrl: '/videos/hyaluron.mp4',
  },
  {
    id: '30',
    name: 'INTENSIVE PROBLEM CONTROL CREAM',
    price: 290,
    description: '50g (Homecare) / 250g (Professional). Anti-blemish cream for combination, oily acne-prone skin. It helps control blemish-prone skin by regulating excessive oil and sebum while keeping the skin hydrated with zinc PCA, xylitol and panthenol. Key ingredients: Zinc PCA, Xylitol, Trehalose, Panthenol, Phytolex SC, Allantoin, Beta-Glucan. Dermatologically tested. Efficacy test on improving excessive sebum production.',
    image: '/images/problem_cream/main.jpeg',
    images: null,
    category: 'Cream',
    inStock: true,
    videoUrl: '/videos/problem_cream.mp4',
  },
  {
    id: '31',
    name: 'MULTI VITA RADIANCE CREAM',
    price: 290,
    description: '50g (Homecare) / 230g (Professional). GENOSYS MULTI VITA RADIANCE CREAM combines a complex of 12 vitamins with potent antioxidants like Astaxanthin to help protect against free radicals and support a more even, luminous look. This formula deeply nourishes and moisturizes the skin, helps even skin tone, and imparts noticeable radiance while supporting collagen feel and defending against everyday environmental stressors. Key ingredients: Astaxanthin, Ascorbic Acid, Multi Vita 12 Complex, Niacinamide, Gluconolactone (PHA), Licorice Root Extract, Ceramide NP, Squalane, Panthenol. Dermatologically tested. Efficacy test on improving skin surface melanin. Astaxanthin assists UV defense but does not replace sunscreen.',
    image: '/images/radiance/main.jpeg',
    images: null,
    category: 'Cream',
    inStock: true,
    size: '50g',
    videoUrl: '/videos/radiance.mp4',
  },
  {
    id: '32',
    name: 'MULTI FUNCTIONAL ANTI-WRINKLE CREAM',
    price: 290,
    description: '50g (Homecare) / 250g (Professional). Multi-functional anti-wrinkle and brightening cream with bakuchiol, a natural alternative to retinol. Helps visibly smooth wrinkles, reinforce skin firmness, and even skin tone with propolis, collagen, adenosine, niacinamide, mango seed butter, and a lipid barrier liposome. Gently massage morning and evening. Clinical study on improvement of skin age index, P&K Skin Research Center, Feb. 22 to May 13, 2024, 24 adult women aged 30~59 years. Key ingredients: Bakuchiol, Propolis Extract, Hydrolyzed Collagen & Elastin, Adenosine, Niacinamide, Mango Seed Butter, Lipid Barrier Liposome (Ceramide NP, Cholesterol, Phytosphingosine). Dermatologically tested. Efficacy test on improving wrinkles and skin tone balance.',
    image: '/images/multifunc_cream/main.jpeg',
    images: JSON.stringify([
      '/images/multifunc_cream/s1.jpeg',
      '/images/multifunc_cream/s2.jpeg',
      '/images/multifunc_cream/s3.jpeg',
      '/images/multifunc_cream/s4.jpeg',
      '/images/multifunc_cream/s5.jpeg',
      '/images/multifunc_cream/s6.jpeg',
    ]),
    category: 'Cream',
    inStock: true,
    size: '50g',
    videoUrl: '/videos/multif_cream.mp4',
  },
  {
    id: '33',
    name: 'EyeCell EYE PEPTIDE GEL PATCH',
    price: 380,
    description: '101g (60 patches / 30 applications). Take-off hydrogel eye mask for calming and moisturizing the contour. Niacinamide 2% and Adenosine 0.04% are the Korean functional pair. Under the eyes and/or eyebrow bones for 20 to 40 minutes, then remove. Dermatologically tested.',
    image: '/images/patch/main.jpeg',
    images: null,
    category: 'Eye care',
    inStock: true,
    videoUrl: '/videos/eyecell-eye-peptide-gel-patch-20260806.mp4',
  },
  {
    id: '34',
    name: 'SKIN RESCUE OVERNIGHT CREAM MASK',
    price: 340,
    description: '100g. Leave-on overnight cream mask for soothing and revitalizing tired-looking skin. Niacinamide 2% and Adenosine 0.04% are the Korean functional pair. Last step of the evening. Do not wash off. Dermatologically tested.',
    image: '/images/overnight/main.jpeg',
    images: null,
    category: 'Mask',
    inStock: true,
    size: '100g',
  },
  {
    id: '35',
    name: 'HYDRO COOL MODELING MASK',
    price: 300,
    description: '1kg. Professional cooling modeling mask. Mix 30g of powder with water at 1 : 0.8, leave 15-20 minutes, peel. Diatomaceous earth 65% is the pouch. Peppermint cool until it comes off. Dermatologically tested.',
    image: '/images/HYDR.jpg',
    images: null,
    category: 'Mask',
    inStock: true,
    videoUrl: '/videos/hydro.mp4',
  },
  {
    id: '36',
    name: 'SOOTHING BOMB SEA ALGAE MASK',
    price: 36,
    description: '25g x 10ea. Eucalace® sheet mask inspired by the healing power of the ocean. It is a Eucalace® sheet mask inspired by the healing power of the ocean. It provides intensive relief to the skin and moisturizes skin with sea algae complex and centella asiatica extract. Key ingredients: Jania Rubens Extract, Undaria Pinnatifida Extract, Bambusa Vulgaris Extract, Centella Asiatica Extract, Hamamelis Virginiana (Witch Hazel) Extract, Custanea Crenata Shell Extract, Panthenol, Allantoin. Dermatologically tested. Efficacy test on skin hydration.',
    image: '/images/sea_algae/Main.jpeg',
    images: null,
    category: 'Mask',
    inStock: true,
    size: '1 sheet (25g)',
  },
  {
    id: '37',
    name: 'PEPTIDE GEL MASK',
    price: 380,
    description: '38g × 5. Face hydrogel sheet. After a dermatological procedure, sit 20-40 minutes, take the sheet off, massage the leftover in. Glycerin 20% is the pouch. The peptide sits at 0.05 ppm. Dermatologically tested.',
    image: '/images/peptide_mask/main.jpeg',
    images: JSON.stringify([
      '/images/peptide_mask/s1c.jpeg',
      '/images/peptide_mask/s2c.jpeg',
      '/images/peptide_mask/s3c.jpeg',
      '/images/peptide_mask/s4c.jpeg',
      '/images/peptide_mask/s5c.jpeg',
    ]),
    category: 'Mask',
    inStock: true,
    videoUrl: '/videos/peptide.mp4',
  },
  {
    id: '38',
    name: 'EZ CO₂ MASK KIT',
    price: 460,
    description: 'Gel 20g ×5, mask 12g ×5, spatula ×1. An acidic gel and a bicarbonate sheet meet on dry skin. CO₂ forms, you wait ten minutes, you rinse. Five treatments. Dermatologically tested.',
    image: '/images/ez_mask/main.jpeg',
    images: JSON.stringify([
      '/images/ez_mask/s1.jpeg',
      '/images/ez_mask/s2.jpeg',
      '/images/ez_mask/s3.jpeg',
      '/images/ez_mask/s4.jpeg',
      '/images/ez_mask/s5.jpeg',
      '/images/ez_mask/s6.jpeg',
      '/images/ez_mask/s7.jpeg',
      '/images/ez_mask/s8.jpeg',
    ]),
    category: 'Mask',
    inStock: true,
  },
  {
    id: '39',
    name: 'ULTRA SHIELD SUN CREAM [SPF 50+ PA++++]',
    price: 250,
    description: '50g. Non-greasy and silky sunscreen with powerful UV protection. It is a non-greasy silky sunscreen that strongly defends skin against UV rays with a 7-filter broad-spectrum UV system, and supports skin recovery with hydrolyzed hyaluronic acid and lactobacillus ferment lysate. Niacinamide 2% and Ceramide NP brighten and strengthen the barrier. Free from oxybenzone and octinoxate. Key ingredients: 7-Filter UV System, Niacinamide 2%, Ceramide NP, Hydrolyzed Sodium Hyaluronate, Lactobacillus Ferment Lysate, Tropical Fruit Extracts (Pineapple, Papaya, Litchi, Guava). Dermatologically tested.',
    image: '/images/ultra/main.jpeg',
    images: JSON.stringify([
      '/images/ultra/s1.jpeg',
      '/images/ultra/s2.jpeg',
      '/images/ultra/s3.jpeg',
      '/images/ultra/s4.jpeg',
      '/images/ultra/s5.jpeg',
      '/images/ultra/s6.jpeg',
    ]),
    videoUrl: '/videos/ultra.mp4',
    category: 'Sun',
    inStock: true,
  },
  {
    id: '40',
    name: 'MULTI SUN CREAM [SPF 40 PA++]',
    price: 210,
    description: '40g. Non-greasy mild sunscreen with a skin glowing effect for daily sun protection. It is a non-greasy mild sunscreen that protects skin from UV A&B rays, and helps soothe the irritated skin from sun rays with palmitoyl pentapeptide-4, centella asiatica extract and botanical callus cultures extracts. Key ingredients: Palmitoyl Pentapeptide-4, Mannan, Glycerin, Rosa Damascena Callus Culture Extract, Vitis Vinifera (Grape) Callus Culture Extract, Centella Asiatica Extract, Scutellaria Baicalensis Root Extract, Lactobacillus/Soymilk Ferment Filtrate. Dermatologically tested.',
    image: '/images/sun/main.jpeg',
    images: JSON.stringify([
      '/images/sun/s1.jpeg',
      '/images/sun/s2.jpeg',
      '/images/sun/s3.jpeg',
      '/images/sun/s4.jpeg',
      '/images/sun/s5.jpeg',
      '/images/sun/s6.jpeg',
    ]),
    category: 'Sun',
    inStock: true,
  },
  {
    id: '41',
    name: 'SKIN CARING BLEMISH BALM CUSHION [SPF 50+ PA++++]',
    price: 300,
    description: 'Professional BB cushion for post-treatment use with natural coverage and skin protection.',
    image: '/images/cushion_2/main.jpeg',
    images: JSON.stringify([
      '/images/cushion_2/s1.jpeg',
      '/images/cushion_2/s2.jpeg',
      '/images/cushion_2/s3.jpeg',
      '/images/cushion_2/s4.jpeg',
      '/images/cushion_2/s5.jpeg',
      '/images/cushion_2/s6.jpeg',
    ]),
    videoUrl: '/videos/cushion.mp4',
    category: 'Cushion BB',
    inStock: true,
  },
  {
    id: '42',
    name: 'INTENSIVE BLEMISH BALM CREAM [SPF 30 PA++]',
    price: 250,
    description: '50g. Natural coverage cream that helps cover redness and express natural skin tone. It is a natural coverage cream that protects skin from the harmful environmental factors. It covers redness and blemishes after the dermatological treatment and helps express natural skin tone. Key ingredients: Arbutin 2%, Adenosine, Allantoin, Eucalyptus Globulus Leaf Oil, Perilla Ocymoides Seed Oil, Rumex Crispus Root Extract. Dermatologically tested.',
    image: '/images/BLEM.jpg',
    images: JSON.stringify(['/images/BLEM.jpg', '/images/Second/bbbig.jpg']),
    category: 'Cushion BB',
    inStock: true,
  },
  {
    id: '43',
    name: 'HR³ MATRIX HAIR TONIC α',
    price: 290,
    description: '70ml. Functional tonic that improves the conditions of hair loss. It is a functional tonic approved as a \'functional product that improves the symptoms of hair loss\' by KFDA. It improves the scalp environment that causes hair loss and cools down the scalp heat, giving the sense of freshness to the scalp. Key ingredients: Copper Tripeptide-1, Sophora Japonica Extract, Caffeine, Menthol, Salicylic Acid, Allantoin, Centella Asiatica Extract, Scutellaria Baicalensis Root Extract, Licorice Root Extract. Dermatologically tested. KFDA approved as a functional product for improving hair loss symptoms. Efficacy test on improving hair loss.',
    image: '/images/hair_tonic/main-v2.jpeg',
    images: JSON.stringify([
      '/images/hair_tonic/s1.jpeg',
      '/images/hair_tonic/s2.jpeg',
      '/images/hair_tonic/s3.jpeg',
      '/images/hair_tonic/s4.jpeg',
      '/images/hair_tonic/s5.jpeg',
      '/images/hair_tonic/s6.jpeg',
    ]),
    category: 'Scalp/Hair',
    inStock: true,
    videoUrl: '/videos/hairt.mp4',
  },
  {
    id: '44',
    name: 'HR³ MATRIX MEDI SCALP SHAMPOO α',
    price: 340,
    description: '300ml. Functional shampoo that improves the conditions of hair loss. It is a functional shampoo approved as a \'functional product that improves the symptoms of hair loss\' by KFDA. It cools down scalp heat and helps control excess sebum on the scalp, making scalp and hair healthy. Key ingredients: Menthol, Caffeine, Copper Tripeptide-1, Biotin, Panthenol, Viscum Album (Mistletoe) Extract, Saccharomyces Cerevisiae Extract, Malt Extract, Acorus Calamus Root Extract, Serenoa Serrulata Fruit Extract, Piroctone Olamine. Dermatologically tested. KFDA approved as a functional product for improving hair loss symptoms.',
    image: '/images/shampoo/Main.jpg',
    images: '["/images/shampoo/S1.jpg","/images/shampoo/S2.jpg","/images/shampoo/S3.jpg","/images/shampoo/S4.jpg","/images/shampoo/S5.jpg","/images/shampoo/S6.jpg"]',
    category: 'Scalp/Hair',
    inStock: true,
    videoUrl: '/videos/shamp.mp4',
  },
  {
    id: '45',
    name: 'HR³ MATRIX HAIR SOLUTION α',
    price: 740,
    description: '4ml. Premium anti-hair loss ampoule for microneedling treatment. It is the premium anti-hair loss product supplying nutrients that fight against the factors causing hair loss. Special applicator with microneedles promotes nutrition delivery into scalp and helps build the right environment for healthy scalp. Components: Professional Kit - HAIR SOLUTION α 4ml(8ea), Dropper(2ea). Homecare Kit - HAIR SOLUTION α 4ml(8ea), microneedle applicator(1ea), Cleansing Brush(1ea), Disinfecting(1ea). Key ingredients: sh-Polypeptide-9 (VEGF), sh-Polypeptide-7 (somatotropin sequence), sh-Oligopeptide-1 (EGF), sh-Polypeptide-71 (VIP), Copper Tripeptide-1, Serenoa Serrulata Fruit Extract (Saw Palmetto), Biosaccharide Gum-4, Panthenol, Menthol, Black Complex, Brassica Oleracea Italica (Broccoli) Extract. Dermatologically tested. Research papers on the improvement of hair loss.',
    image: '/images/HHR.jpg',
    images: '["/images/Second/hs.jpg"]',
    category: 'Scalp/Hair',
    inStock: true,
    videoUrl: '/videos/hairs.mp4',
  },
  {
    id: '46',
    name: 'HR³ MATRIX SCALP PEELING α',
    price: 290,
    description: '100ml. Scalp peeling product with deep cleansing and heat cooling effects. It is a scalp peeling product which gives the deep cleansing effect for the scalp and refreshes the scalp with cooling effect. Key ingredients: Copper Tripeptide-1, Serenoa Serrulata Fruit Extract (Saw Palmetto), Salicylic Acid, Menthol, Black Complex, Camellia Sinensis Leaf Extract. Dermatologically tested.',
    image: '/images/scal.jpg',
    images: '["/images/Second/pp.jpg"]',
    category: 'Scalp/Hair',
    inStock: true,
  },
  {
    id: '47',
    name: 'HR³ MATRIX MESOPECIA KIT',
    price: 1100,
    description: 'Professional kit to allows a systematic hair loss treatment. It is a professional kit that allows a systematic hair loss treatment by combining microneedling with high performing cosmeceuticals. Components: SCALP PEELING α (100ml) - It is a light scalp peeling product which gives the deep cleansing effect for the scalp and refreshes the scalp with cooling effect. HAIR SOLUTION α (4ml x 6ea) + STAMP (ROLLER) - It is a premium anti-hair loss product supplying nutrients that fight against the factors causing hair loss. It is specially formulated for microneedling to build the right environment for healthy scalp. Key ingredients SCALP PEELING α: Copper Tripeptide-1, Serenoa Serrulata Fruit Extract (Saw Palmetto), Salicylic Acid, Menthol, Black Complex, Camellia Sinensis Leaf Extract. Key ingredients HAIR SOLUTION α: sh-Polypeptide-9 (VEGF), sh-Polypeptide-7 (somatotropin sequence), sh-Oligopeptide-1 (EGF), sh-Polypeptide-71 (VIP), Copper Tripeptide-1, Serenoa Serrulata Fruit Extract (Saw Palmetto), Biosaccharide Gum-4, Panthenol, Menthol, Black Complex, Brassica Oleracea Italica (Broccoli) Extract. Dermatologically tested. Research papers on the improvement of hair loss.',
    image: '/images/meso.jpg',
    images: null,
    category: 'Scalp/Hair',
    inStock: true,
  },
  {
    id: '48',
    name: 'Hair-GENTRON',
    price: 3300,
    description: 'LED helmet with massaging and heating functions to treat hair loss. Patent No. 10-2151442. Bronze medal winner of 2020 Korea invention patent competition. It is a LED helmet with massaging and heating functions patented as a scalp massager for promoting hair growth using air pressure and LED lights. Features: Infrared light + Red light + Blue light + Massaging + Heating function. Advantages: Non-invasive light therapy, Safe & painless therapy, Available for both professional & home care, Infrared light, red light and blue light can be irradiated at the same time, Proper distance from the source of the light energy and scalp is guaranteed which leads to the optimal emission effect, Massaging function can be done while lights are irradiated, Music mode helps the user feel relaxed, Heating function can be added during treatment. Effects: Improve blood circulation in scalp → Provide more nutrients & oxygen to hair follicles, Relieve stress and tension.',
    image: '/images/gen.jpg',
    images: null,
    videoUrl: '/videos/gentron.mp4',
    category: 'Device',
    inStock: true,
  },
  {
    id: '49',
    name: 'GENO-LED IR II',
    price: 5500,
    description: 'LED device that resolves complicated skin problems. It is a LLLT device which resolves complicated skin problems by irradiating lights with various wave lengths - 640nm (red), 423nm (blue), 532nm (green), 583nm (yellow) and 830nm (infrared). Features: Dome shape for less light loss, Excellent and powerful high-brightness and special near-infrared light SMD LED element, Light of different lengths (423nm~830nm) - Blue light, Green light, Yellow light, Red light + Infrared light, Available for the treatment of whole body – total care device, Effective for various types of skin problems, Gentle and safe treatment without pain, side effects and downtime. LED Specifications: Red (640nm) - 380ea, Blue (423nm) - 380ea, Green (532nm) - 380ea, Yellow (583nm) - 380ea, Infrared (830nm) - 190ea. Total: 1,710 LED and IR lamps. Effects: Cell regeneration, Anti-aging, Brightening, Soothing, Acne treatment, Improvement in edema/erythema, Hair loss care, Improvement in blood circulation. Face, Scalp, Body Total Care device.',
    image: '/images/LEDD.jpg',
    images: null,
    videoUrl: '/videos/led.mp4',
    category: 'Device',
    inStock: true,
  },
  {
    id: '50',
    name: 'EyeCell EYE ZONE CARE KIT',
    price: 980,
    description: 'Professional kit to treat various skin problems around eyes. It is a professional kit designed to treat various skin problems around eyes from dehydration, dark circle, eye bag to crow\'s feet. It combines cosmeceuticals with a roller specially designed for eye area to activate collagen production and increase the absorption of ingredients into skin. Components: EYE CONTOUR SERUM (10ml) + EYE ROLLER - It is a highly enriched all-in-one eye serum that helps improve wrinkles, dark circles and diminish the appearance of eye puffs. It can be used together with EYE ROLLER developed to enable delicate and detailed care even for the curved area of face as well as eye contour area. EYE CONTOUR CREAM (20g) - It is a daily cream for eye contour area that brings younger-looking eyes by helping reduce wrinkles and dark circles and depuff the under eye with peptide complex, botanical callus culture extracts and anti-dark circle complex. EYE PEPTIDE GEL PATCH (101g / 60ea) - It is a patented thermo-sensitive for eye contour area that soothes and moisturizes the skin that went through dermatologic procedures or natural aging. And it improves eye bags. Dermatologically tested. Efficacy test on improving wrinkles and moisturizing.',
    image: '/images/eye_kit/main.jpeg',
    images: null,
    category: 'Eye care',
    inStock: true,
    size: '1 box',
    videoUrl: '/videos/kit.mp4',
  },
  {
    id: '51',
    name: 'BIO-FERMENT AGE DEFYING POWDER MASK',
    price: 250,
    description: '300g. Professional modeling mask. Mix 40g of powder with water at 1 : 1.5, leave 15–20 minutes, peel. Diatomaceous earth base that holds moisture instead of drying out. Hydration rose 218% in the DTS MG clinical trial. Dermatologically tested.',
    image: '/images/bio_ferment/bferment_main.jpg',
    images: null,
    category: 'Mask',
    inStock: true,
    size: '300g',
  },
  {
    id: '52',
    name: 'SKIN REBOOT PDRN MASK PACK',
    price: 400,
    description: 'Professional PDRN mask pack with salmon DNA technology for skin regeneration and repair. Ultra-slim fit sheets with 30 masks per container.',
    image: '/images/pdrn_mask/main.jpeg',
    images: null,
    category: 'Mask',
    inStock: true,
    size: '30 sheets',
  },
  {
    id: '61',
    name: 'HR³ MATRIX SCALP BRUSH',
    price: 50,
    description: '1 pc. Specialized scalp care brush for daily massage and treatment preparation. It is a gentle, non-invasive scalp brush designed primarily for scalp care, stimulation, and supporting hair health. The Scalp Brush promotes better circulation, exfoliation, and product absorption on the scalp. Features: Ergonomic design with soft, flexible silicone bristles optimized for scalp use without causing irritation. Dual Use - Wet use: Apply shampoo, then gently massage in circular motions to deeply cleanse, remove buildup, and stimulate blood flow. Dry use: On clean, dry hair/scalp for invigorating massage to boost circulation and relax the scalp. Integration with HR³ MATRIX Line: Pairs excellently with HR³ MATRIX Clinical Hair Tonic, Scalp Peeling, and Hair Solution α to enhance nutrient delivery and overall scalp health. Benefits: Improves blood circulation to nourish follicles, helps reduce dandruff and excess sebum, stimulates scalp for healthier hair growth environment, prepares scalp for microneedling treatments. Manufactured in South Korea.',
    image: '/images/brush/main.jpg',
    images: JSON.stringify(['/images/brush/s1.jpg', '/images/brush/s2.jpg', '/images/brush/s3.jpg', '/images/brush/s4.jpg']),
    category: 'Scalp/Hair',
    inStock: true,
  },
  {
    id: '63',
    name: 'REVITA GLOW BLEMISH BALM CREAM [SPF 38 PA+++]',
    price: 250,
    description: 'Genosys REVITA GLOW BLEMISH BALM CREAM [SPF 38 PA+++]. 50g. An instantly revitalizing complexion formula that enhances the skin\'s natural luminosity for a clear, glass-like glow. A regenerative BB cream infused with a complex of 10 vitamins and 7 herbal extracts, instantly energizing the skin while naturally covering skin imperfections. Available in two shades: #01 Bright for an illuminating glow with a clear, radiant complexion, and #02 Natural for a refined glow with a natural, healthy-looking complexion. UV protection (SPF 38 PA+++). Long-lasting, transfer-resistant radiant wear. Key ingredients: 10 Vitamin Complex (Vitamins A, B1, B2, B3, B4, B5, B7, B9, C, E), Herb Complex (Camellia Sinensis Leaf Extract, Rosmarinus Officinalis Leaf Extract, Centella Asiatica Extract, Tremella Fuciformis Extract, Chamomilla Recutita Flower Extract, Polygonum Cuspidatum Root Extract, Scutellaria Baicalensis Root Extract, Glycyrrhiza Uralensis Root Extract), Niacinamide 2%, Adenosine, Erythritol. Effects: Revitalizing, Hydrating, Soothing & Barrier Protecting, Coverage. Dermatologically tested.',
    image: '/images/revita/main.jpg',
    images: JSON.stringify(['/images/revita/main.jpg', '/images/revita/s1.jpg', '/images/revita/s2.jpg', '/images/revita/s3.jpg', '/images/revita/s4.jpg']),
    category: 'Cream, Sun, Cushion BB',
    inStock: true,
    size: '50g',
    videoUrl: '/videos/revita.mp4',
  },
  {
    id: '60',
    productNumber: '60',
    name: 'Bio Meso PDRN Ampoule 60000',
    price: 600,
    description: `The Genosys Bio Meso PDRN Expert Ampoule 60000 is a specialized skincare treatment ampoule designed for bio-meso therapy, a no-needle microneedling approach. It utilizes microscopic spicules (needle-like components extracted from freshwater sponges) to create temporary microchannels in the skin, enhancing the absorption of active ingredients without the need for actual needles. This product is enriched with the uniquely formulated BIO-MESO™ PDRN (Polydeoxyribonucleotide), panthenol, and an anti-aging complex to regenerate skin and strengthen the skin barrier.

It features a 2-way system for customizable care:
• Professional Use (Expert Ampoule 60000): Higher concentration for clinic-based treatments.
• Home-Use (Homecare Ampoule 5000): Lower concentration for ongoing maintenance.

The ampoule functions as a spicule peeling or bio-meso peeling treatment, inducing a peel-off effect on the skin. It contains a significantly higher concentration of spicules compared to other products, delivering intensive results.`,
    image: '/images/6000/main.jpg',
    images: null,
    category: 'Bio Meso',
    inStock: true,
    size: '3ml x 4 ampoules',
    isPriceOnRequest: false,
    disclaimer: 'For Professional/Clinic Use Only. This product requires proper training and should only be used by licensed aestheticians or dermatologists.',
    videoUrl: '/videos/60000.mp4',
  },
  {
    id: '64',
    productNumber: '64',
    name: 'Hair Stamp For HAIRGEN BOOSTER',
    price: 600,
    description: `The GENOSYS HR³ MATRIX HAIR STAMP is a precision microneedle applicator developed for the GENOSYS HairGen Booster scalp treatment system. Each stamp head is fitted with an array of ultra-fine microneedles that create temporary microchannels in the scalp, dramatically increasing skin permeability so the active ingredients of HR³ MATRIX HAIR SOLUTION α are delivered directly to the hair follicles and surrounding tissue.

When mounted on the HairGen Booster, the stamp performs automatic microneedling — a gentle, massaging action that creates far more microchannels than manual stamping or rolling while minimizing discomfort. The micro-injuries also trigger the skin's natural wound-healing response, supporting scalp regeneration, improved blood circulation and a healthier environment for hair growth.

Supplied as 1 box containing 8 hair stamps. A fresh stamp is used together with a new dose of HR³ MATRIX HAIR SOLUTION α for every treatment to ensure hygienic, contamination-free application. Manufactured in South Korea.`,
    image: '/images/needles/main.jpeg',
    images: JSON.stringify(['/images/needles/s1.jpg', '/images/needles/s2.jpg', '/images/needles/s3.jpg', '/images/needles/s4.jpg']),
    category: 'Scalp/Hair',
    inStock: true,
    size: '1 box - 8 pcs of hair stamp',
    isPriceOnRequest: false,
  },
  {
    id: '65',
    productNumber: '65',
    name: 'Bio-Meso PDRN Homecare Ampoule 5000',
    price: 300,
    description: `A specialized homecare treatment ampoule, enriched with the uniquely formulated BIO-MESO™ PDRN, panthenol, and an anti-aging complex to regenerate skin and strengthen the skin barrier.

BIO-MESO™ PDRN coated spicules have a needle-shaped structure that enables direct skin penetration, providing a bio-peeling effect that promotes skin turnover and delivers excellent skin regeneration benefits — all without classic needles. Designed for ongoing, gentle home care to maintain and reinforce results between professional treatments.`,
    image: '/images/meso_5000/main.jpg',
    images: null,
    category: 'Bio Meso',
    inStock: true,
    size: '50ml',
    isPriceOnRequest: false,
    videoUrl: '/videos/5000.mp4',
  },
]
