// Auto-generated by scripts/generate-sw-version.js
// Do not edit manually - this file is regenerated on each build

export const SW_VERSION = 'v0.1.0-270b57a2'
export const APP_VERSION = '0.1.0'
export const BUILD_HASH = '270b57a2'
export const BUILD_DATE = '2026-01-24T19:54:54.531Z'
