// Auto-generated by scripts/generate-sw-version.js
// Do not edit manually - this file is regenerated on each build

export const SW_VERSION = 'v0.1.0-988759d8'
export const APP_VERSION = '0.1.0'
export const BUILD_HASH = '988759d8'
export const BUILD_DATE = '2026-01-14T16:18:56.859Z'
