import { NextRequest, NextResponse, after } from 'next/server'
import * as Sentry from '@sentry/nextjs'
import { sendEmail, sendAdminNewOrderNotification, generateCODOrderHTML, OrderHTMLData, OrderHTMLItem } from '@/lib/email'
import { debugLog, errorLog } from '@/lib/logger'
import { addOrder, OrderData, OrderItemData } from '@/lib/orderStorageDb'
import { requireCsrfToken } from '@/lib/csrf'
import { rateLimitSimple, getClientIdentifierFromNextRequest } from '@/lib/rateLimitSimple'
import { enhanceOrderItemWithDefaultSize } from '@/lib/orderSizeDefaults'
import { getPreferredEmail } from '@/lib/emailHelpers'
import { findUserByEmail } from '@/lib/userStorageDb'
import { isUserDiscountExcludedProduct } from '@/lib/mobileDiscountRules'
import { getProductById } from '@/lib/productsDb'
import { getCartLinePricing } from '@/lib/cartPricing'
import { calculateMobileShipping, calculateVatIncluded } from '@/lib/mobileCheckoutConfig'
import { CartItem, Product } from '@/types'
import {
  getValidatedBundleDiscountPercent,
  isAllowedFreeGiftProduct,
  isSubmittedBundleLine,
  allowedFreeGiftUnits,
  freeGiftKind,
} from '@/lib/checkoutPricingGuards'

interface SubmittedCODItem {
  id?: string
  name: string
  price: number
  quantity: number
  image?: string
  color?: string
  size?: string
  bundleDiscount?: number
}

interface ServerPricedCODItem {
  id: string
  name: string
  price: number
  quantity: number
  total: number
  image?: string
  color?: string
  size?: string
  bundleDiscount?: number
}

function isSubmittedFreeGift(item: SubmittedCODItem): boolean {
  return Number(item.price) === 0 || String(item.name || '').toLowerCase().includes('(free)')
}

function getSubmittedProductId(item: SubmittedCODItem): string {
  return String(item.id || '').trim()
}

// Helper function to detect device type from User-Agent
function detectDeviceType(userAgent: string | null): string {
  if (!userAgent) return 'Unknown'
  
  const ua = userAgent.toLowerCase()
  
  // Check for mobile devices
  if (/mobile|android|iphone|ipad|ipod|blackberry|iemobile|opera mini/i.test(ua)) {
    return 'Mobile'
  }
  
  // Check for tablet devices
  if (/tablet|ipad|playbook|silk/i.test(ua)) {
    return 'Tablet'
  }
  
  // Default to desktop
  return 'Desktop'
}

// Each COD order writes a DB row + sends a customer email + an admin email.
// Rate-limit per IP so a script with one CSRF token can't flood orders/email.
// 5 / 10 min is generous for a real shopper.
const codLimiter = rateLimitSimple({ windowMs: 10 * 60 * 1000, max: 5 })

export async function POST(request: NextRequest) {
  // CSRF protection
  const csrfCheck = await requireCsrfToken(request)
  if (!csrfCheck.valid) {
    return csrfCheck.response!
  }

  // Abuse protection (email/DB flood)
  const rl = await codLimiter(`cod:${getClientIdentifierFromNextRequest(request)}`)
  if (!rl.success) {
    return NextResponse.json(
      { error: rl.message || 'Too many requests' },
      { status: 429 }
    )
  }

  try {
    // Detect device type from User-Agent header
    const userAgent = request.headers.get('user-agent')
    const deviceType = detectDeviceType(userAgent)
    
    const orderData = await request.json()
    const {
      orderNumber,
      customerName,
      customerEmail,
      customerPhone,
      customerAddress,
      emirate,
      items,
      locale = 'en'
    } = orderData

    // Optional customer delivery notes (length-capped, plain text)
    const orderNotes =
      typeof orderData.orderNotes === 'string' && orderData.orderNotes.trim()
        ? orderData.orderNotes.trim().slice(0, 1000)
        : null

    // Validate required fields
    if (!customerEmail || !customerEmail.trim()) {
      errorLog('❌ COD order missing customerEmail:', orderNumber)
      return NextResponse.json(
        { error: 'Customer email is required' },
        { status: 400 }
      )
    }

    if (!orderNumber) {
      errorLog('❌ COD order missing orderNumber')
      return NextResponse.json(
        { error: 'Order number is required' },
        { status: 400 }
      )
    }

    debugLog('📧 COD order received:', {
      orderNumber,
      customerEmail,
      customerName,
      itemCount: items?.length || 0
    })

    // Look up user's discount percentage
    const user = await findUserByEmail(customerEmail)
    const userDiscountPct = Number(user?.discountPercentage || 0)
    const hasUserDiscount = Number.isFinite(userDiscountPct) && userDiscountPct > 0 && userDiscountPct < 100
    
    // Production debug logging
    debugLog('🎟️ COD DISCOUNT DEBUG:', JSON.stringify({
      orderNumber,
      customerEmail,
      userFound: !!user,
      userId: user?.id,
      userEmail: user?.email,
      rawDiscountPercentage: user?.discountPercentage,
      userDiscountPct,
      hasUserDiscount
    }))

    // Calculate totals from server-recomputed prices. Client-submitted item prices
    // are ignored except for explicit free-gift markers generated by checkout.
    let subtotal = 0
    let discountAmount = 0  // User discount
    let bundleDiscountAmountCalc = 0  // Bundle discount (calculated server-side)
    let bundleDiscountPercentCalc: number | null = null
    const serverItems: ServerPricedCODItem[] = []
    const productRecords: Array<{ item: SubmittedCODItem; product: Product }> = []

    for (const item of items as SubmittedCODItem[]) {
      const productId = getSubmittedProductId(item)
      if (!productId) {
        return NextResponse.json(
          { error: 'Invalid cart item' },
          { status: 400 }
        )
      }

      const product = await getProductById(productId)
      if (!product) {
        return NextResponse.json(
          { error: `Product not found: ${item.name || productId}` },
          { status: 400 }
        )
      }

      productRecords.push({ item, product })
    }

    const bundleLineCount = productRecords.filter(({ item, product }) =>
      isSubmittedBundleLine(item.bundleDiscount, product)
    ).length

    // Free-gift candidates are collected here and validated against the spend
    // threshold AFTER the paid subtotal is known (below).
    const freeGiftCandidates: Array<{ item: SubmittedCODItem; product: Product; quantity: number; selectedColor: string; selectedSize: string }> = []

    for (const { item, product } of productRecords) {
      const quantity = Number(item.quantity) || 0
      const selectedSize = String(item.size || '').trim()
      const selectedColor = String(item.color || '').trim()
      const isFreeGift = isSubmittedFreeGift(item) && isAllowedFreeGiftProduct(product)
      const bundlePct = getValidatedBundleDiscountPercent(item.bundleDiscount, product, bundleLineCount)

      if (quantity <= 0) {
        return NextResponse.json(
          { error: `Invalid quantity for ${product.name}` },
          { status: 400 }
        )
      }

      if (isFreeGift) {
        freeGiftCandidates.push({ item, product, quantity, selectedColor, selectedSize })
        continue
      }

      // Out-of-stock enforcement (paid items only). The UI disables add-to-cart
      // for OOS products; this closes the crafted-request / went-OOS-mid-checkout gap.
      if (!product.inStock) {
        return NextResponse.json(
          { error: `${product.name} is currently out of stock` },
          { status: 400 }
        )
      }

      const cartItem: CartItem = {
        product,
        quantity,
        ...(selectedColor ? { selectedColor } : {}),
        ...(selectedSize ? { selectedSize } : {}),
        ...(bundlePct ? { fromBundle: true, bundleDiscountPercent: bundlePct } : {}),
      }
      const pricing = getCartLinePricing(cartItem, user)
      subtotal += pricing.lineTotal

      if (pricing.discountType === 'bundle') {
        bundleDiscountAmountCalc += pricing.discountAmount
        if (pricing.discountPercentage > 0) bundleDiscountPercentCalc = pricing.discountPercentage
      } else if (pricing.discountType === 'user' || pricing.discountType === 'black_friday') {
        discountAmount += pricing.discountAmount
      }

      serverItems.push({
        id: product.id,
        name: product.name,
        price: pricing.unitPrice,
        quantity,
        total: pricing.lineTotal,
        image: item.image || product.image,
        ...(selectedColor ? { color: selectedColor } : {}),
        ...(selectedSize ? { size: selectedSize } : {}),
        ...(pricing.discountType === 'bundle' ? { bundleDiscount: pricing.discountPercentage } : {}),
      })
    }

    // Round to 2 decimal places
    subtotal = Math.round(subtotal * 100) / 100
    discountAmount = Math.round(discountAmount * 100) / 100
    bundleDiscountAmountCalc = Math.round(bundleDiscountAmountCalc * 100) / 100

    // Now that the paid subtotal is final, admit only the free masks the spend
    // threshold allows (>=500 → collagen, >=700 → + sea algae). Extra or
    // undeserved free items are silently dropped rather than granted.
    {
      const allowance = allowedFreeGiftUnits(subtotal)
      let collagenLeft = allowance.collagen
      let seaAlgaeLeft = allowance.seaAlgae
      for (const g of freeGiftCandidates) {
        const kind = freeGiftKind(g.product)
        let grant = 0
        if (kind === 'collagen') { grant = Math.min(g.quantity, collagenLeft); collagenLeft -= grant }
        else if (kind === 'sea_algae') { grant = Math.min(g.quantity, seaAlgaeLeft); seaAlgaeLeft -= grant }
        if (grant <= 0) continue
        serverItems.push({
          id: g.product.id,
          name: String(g.item.name || `${g.product.name} (FREE)`),
          price: 0,
          quantity: grant,
          total: 0,
          image: g.item.image || g.product.image,
          ...(g.selectedColor ? { color: g.selectedColor } : {}),
          ...(g.selectedSize ? { size: g.selectedSize } : {}),
        })
      }
    }

    const shippingCost = calculateMobileShipping(subtotal, emirate)
    const total = subtotal + shippingCost
    const vatAmount = Math.round(calculateVatIncluded(total) * 100) / 100
    
    debugLog('🎟️ COD DISCOUNT CALCULATED:', JSON.stringify({
      orderNumber,
      discountAmount: discountAmount.toFixed(2),
      discountPercentage: userDiscountPct,
      bundleDiscountAmount: bundleDiscountAmountCalc.toFixed(2),
      bundleDiscountPercentage: bundleDiscountPercentCalc
    }))

    // Save order to database
    const orderItems: OrderItemData[] = serverItems.map((item) => {
      // Enhance with default size if missing
      const itemName = item.name || 'Product'
      const enhanced = enhanceOrderItemWithDefaultSize({
        productName: itemName,
        size: item.size || null,
        color: item.color || null
      })
      
      return {
        productId: item.id,
        productName: itemName,
        price: item.price,
        quantity: item.quantity,
        image: item.image || '/images/placeholder.jpg',
        ...(enhanced.color ? { color: enhanced.color } : {}),
        ...(enhanced.size ? { size: enhanced.size } : {}),
        ...(item.bundleDiscount && item.bundleDiscount > 0 ? { bundleDiscount: item.bundleDiscount } : {})
      }
    })

    const dbOrder: OrderData = {
      orderNumber,
      customerEmail,
      customerName,
      customerPhone,
      customerEmirate: emirate,
      customerAddress,
      ...(orderNotes ? { orderNotes } : {}),
      items: orderItems,
      subtotal,
      discountPercentage: hasUserDiscount ? userDiscountPct : 0,
      discountAmount: discountAmount > 0 ? discountAmount : 0,
      ...(bundleDiscountPercentCalc ? { bundleDiscountPercentage: bundleDiscountPercentCalc } : {}),
      bundleDiscountAmount: bundleDiscountAmountCalc,
      shipping: shippingCost,
      vat: vatAmount,
      total,
      status: 'PENDING',
      locale: locale || 'en' // Capture locale from request, default to English
    }

    // Save to database with timeout protection
    let savedOrder
    try {
      const savePromise = addOrder(dbOrder)
      const timeoutPromise = new Promise((_, reject) => 
        setTimeout(() => reject(new Error('Database save timeout after 8 seconds')), 8000)
      )
      savedOrder = await Promise.race([savePromise, timeoutPromise]) as Awaited<ReturnType<typeof addOrder>>
      debugLog('✅ COD order saved to database:', savedOrder.id)
    } catch (dbError) {
      errorLog('⚠️ Database save failed or timed out, continuing with order processing:', dbError)
      // Continue even if database save fails - order will be processed via email
      // Create a minimal order object for fallback (matches Order type structure)
      savedOrder = {
        id: 'pending',
        orderNumber: dbOrder.orderNumber,
        customerEmail: dbOrder.customerEmail,
        customerName: dbOrder.customerName,
        customerPhone: dbOrder.customerPhone,
        customerEmirate: dbOrder.customerEmirate,
        customerAddress: dbOrder.customerAddress,
        orderNotes: dbOrder.orderNotes ?? null,
        subtotal: dbOrder.subtotal,
        discountPercentage: dbOrder.discountPercentage ?? 0,
        discountAmount: dbOrder.discountAmount ?? 0,
        bundleDiscountPercentage: bundleDiscountPercentCalc,
        bundleDiscountAmount: bundleDiscountAmountCalc,
        shipping: dbOrder.shipping ?? 0,
        vat: dbOrder.vat,
        total: dbOrder.total,
        status: dbOrder.status ?? 'PENDING',
        locale: dbOrder.locale ?? 'en',
        sessionId: dbOrder.sessionId ?? null,
        paymentMethod: 'cod',
        paymentStatus: 'pending',
        stripeSessionId: null,
        stripePaymentIntentId: null,
        stripeCustomerId: null,
        paidAt: null,
        refundedAt: null,
        refundAmount: null,
        paymentMetadata: null,
        moySkladOrderId: null,
        moySkladSyncedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        items: []
      } as Awaited<ReturnType<typeof addOrder>>
      
      // Try to save asynchronously in background (don't wait)
      addOrder(dbOrder).then((retryOrder) => {
        debugLog('✅ COD order saved to database (retry):', retryOrder.id)
      }).catch((retryError) => {
        errorLog('❌ Retry database save also failed:', retryError)
      })
    }

    // Prepare order HTML data with proper types
    const orderHTMLData: OrderHTMLData = {
      orderNumber,
      customerName: customerName || 'Customer',
      customerEmail: customerEmail || 'N/A',
      customerPhone: customerPhone || 'N/A',
      customerAddress: (customerAddress && customerAddress.trim()) || 'N/A',
      emirate: (emirate && emirate.trim()) || 'N/A',
      discountPercentage: hasUserDiscount ? userDiscountPct : undefined,
      discountAmount: discountAmount > 0 ? discountAmount : undefined,
      bundleDiscountPercentage: bundleDiscountPercentCalc ?? undefined,
      bundleDiscountAmount: bundleDiscountAmountCalc > 0 ? bundleDiscountAmountCalc : undefined,
      items: serverItems.map((item): OrderHTMLItem => {
        // Enhance with default size if missing
        const itemName = item.name || 'Product'
        const originalSize = (item.size && item.size.trim()) || null
        const enhanced = enhanceOrderItemWithDefaultSize({
          productName: itemName,
          size: originalSize,
          color: (item.color && item.color.trim()) || null
        })
        
        // Check item type for discount labeling
        const isFreeItem = item.price === 0 || itemName.toLowerCase().includes('(free)')
        const isBundle = itemName.toLowerCase().includes('beauty box') || itemName.toLowerCase().includes('bundle')
        const isExcludedFromUserDiscount = isUserDiscountExcludedProduct({ name: itemName })
        const hasUserDiscountApplied = hasUserDiscount && !isExcludedFromUserDiscount && !isFreeItem
        
        // Determine discount label and original price
        let discountLabel: string | undefined = undefined
        let originalPrice: number | undefined = undefined
        
        if (isFreeItem) {
          // Free items - no discount label needed
          discountLabel = undefined
          originalPrice = undefined
        } else if (isBundle) {
          // Bundles have 15% discount
          discountLabel = '15% OFF - Bundle'
          originalPrice = item.price / (1 - 0.15) // Reverse calculate from 15% discount
        } else if (hasUserDiscountApplied) {
          // Regular items with user discount
          discountLabel = `${userDiscountPct}% OFF`
          originalPrice = item.price / (1 - userDiscountPct / 100)
        }
        
        debugLog(`📦 COD Order Item: ${itemName}`)
        debugLog(`   Original size: ${originalSize || 'none'}`)
        debugLog(`   Enhanced size: ${enhanced.size || 'none'}`)
        debugLog(`   Color: ${enhanced.color || 'none'}`)
        debugLog(`   Free: ${isFreeItem}, Bundle: ${isBundle}, UserDiscount: ${hasUserDiscountApplied}`)
        debugLog(`   DiscountLabel: ${discountLabel || 'none'}, Original: ${originalPrice?.toFixed(2) || 'N/A'}, Current: ${item.price}`)
        
        const orderItem: OrderHTMLItem = {
          name: itemName,
          quantity: item.quantity,
          price: item.price,
          originalPrice,
          discountLabel,
          bundleDiscount: (item.bundleDiscount && item.bundleDiscount > 0) ? item.bundleDiscount : undefined,
        }
        if (item.image) {
          orderItem.image = item.image
        }
        // Always set size if we have it (from item or default)
        if (enhanced.size && enhanced.size.trim()) {
          orderItem.size = enhanced.size.trim()
        }
        if (enhanced.color && enhanced.color.trim()) {
          orderItem.color = enhanced.color.trim()
        }
        return orderItem
      }),
      subtotal,
      shippingCost,
      vatAmount,
      total
    }

    // Load translations
    const translations = locale === 'ar' 
      ? (await import('@/messages/ar.json')).default.orderEmail.cod
      : locale === 'ru'
      ? (await import('@/messages/ru.json')).default.orderEmail.cod
      : (await import('@/messages/en.json')).default.orderEmail.cod

    const orderHTML = generateCODOrderHTML(orderHTMLData, locale, translations)

    // Use already-fetched user (from discount lookup) for email routing (Apple Private Relay users)
    const emailToUse = user ? getPreferredEmail(user) : customerEmail

    debugLog('📧 COD Email routing:', {
      customerEmail,
      hasUser: !!user,
      hasContactEmail: !!(user?.contactEmail),
      emailToUse,
      isAppleRelay: customerEmail.includes('@privaterelay.appleid.com') || customerEmail.includes('@genosys.local')
    })

    const emailSubject = (translations?.subject || `Order Confirmation #${orderNumber} - GENOSYS Professional`).replace('#{orderNumber}', orderNumber).replace('{orderNumber}', orderNumber)

    // Schedule all background tasks with after() so Vercel keeps the function alive.
    // Without after(), fire-and-forget promises get killed when the serverless function
    // terminates after sending the response — causing missed admin notifications.
    after(async () => {
      // 1. Send order confirmation email to customer (HIGHEST PRIORITY)
      try {
        debugLog('📧 Attempting to send COD confirmation email to customer:', emailToUse)
        const result = await sendEmail(emailToUse.trim(), emailSubject, orderHTML)
        if (result.success) {
          debugLog('✅ COD order confirmation email sent successfully to:', emailToUse)
          debugLog('✅ Message ID:', result.messageId || 'N/A')
        } else {
          errorLog('❌ FAILED to send COD order confirmation email to:', emailToUse)
          errorLog('❌ Error:', result.error)
          errorLog('❌ Order number:', orderNumber)
        }
      } catch (emailError) {
        errorLog('❌ EXCEPTION sending COD order confirmation email to:', emailToUse)
        errorLog('❌ Exception:', emailError)
        errorLog('❌ Order number:', orderNumber)
        errorLog('❌ Stack:', emailError instanceof Error ? emailError.stack : 'No stack')
      }

      // 2. Send admin notification for COD order
      try {
        debugLog('📧 Sending admin notification for COD order:', orderNumber)
        const adminResult = await sendAdminNewOrderNotification({
          orderNumber,
          customerName,
          customerEmail: emailToUse,
          customerPhone,
          total,
          itemCount: orderItems.length,
          items: orderItems.map((item: OrderItemData) => {
            const itemName = item.productName || 'Product'
            
            const isFreeItem = item.price === 0 || itemName.toLowerCase().includes('(free)')
            const isBundle = itemName.toLowerCase().includes('beauty box') || itemName.toLowerCase().includes('bundle')
            const isExcludedFromUserDiscount = isUserDiscountExcludedProduct({ name: itemName })
            const hasUserDiscountApplied = hasUserDiscount && !isExcludedFromUserDiscount && !isFreeItem
            
            let discountLabel: string | undefined = undefined
            let originalPrice: number | undefined = undefined
            
            if (isFreeItem) {
              discountLabel = undefined
              originalPrice = undefined
            } else if (isBundle) {
              discountLabel = '15% OFF - Bundle'
              originalPrice = item.price / (1 - 0.15)
            } else if (hasUserDiscountApplied) {
              discountLabel = `${userDiscountPct}% OFF`
              originalPrice = item.price / (1 - userDiscountPct / 100)
            }
            
            return {
              productName: itemName,
              quantity: item.quantity,
              price: item.price,
              originalPrice,
              image: item.image || '/images/default-product.jpg',
              ...(item.size ? { size: item.size } : {}),
              ...(item.color ? { color: item.color } : {}),
              ...(discountLabel ? { discountLabel } : {}),
              bundleDiscount: item.bundleDiscount ?? undefined
            }
          }),
          subtotal,
          shipping: shippingCost,
          vat: vatAmount,
          address: (customerAddress && customerAddress.trim()) || undefined,
          emirate: (emirate && emirate.trim()) || undefined,
          deviceType,
          paymentStatus: 'COD',
          paymentMethod: 'Cash on Delivery',
          discountPercentage: hasUserDiscount ? userDiscountPct : undefined,
          discountAmount: discountAmount > 0 ? discountAmount : undefined,
          bundleDiscountPercentage: bundleDiscountPercentCalc ?? undefined,
          bundleDiscountAmount: bundleDiscountAmountCalc > 0 ? bundleDiscountAmountCalc : undefined
        })
        if (adminResult.success) {
          debugLog('✅ Admin notification sent successfully for COD order:', orderNumber)
        } else {
          errorLog('❌ FAILED to send admin notification for COD order:', orderNumber)
          errorLog('❌ Admin notification error:', adminResult.error)
        }
      } catch (emailError) {
        errorLog('❌ EXCEPTION sending admin notification for COD order:', orderNumber)
        errorLog('❌ Exception details:', emailError)
        errorLog('❌ Exception stack:', emailError instanceof Error ? emailError.stack : 'No stack')
      }
    })

    // Return success response immediately — after() keeps the function alive for emails
    return NextResponse.json({ 
      success: true, 
      message: 'COD order confirmation sent successfully',
      orderId: savedOrder?.id || 'pending',
      orderNumber: orderNumber
    })

  } catch (error) {
    errorLog('Error sending COD order confirmation:', error)
    Sentry.captureException(error, { tags: { area: 'checkout', op: 'cod-confirmation' } })
    return NextResponse.json(
      {
        error: 'Failed to send COD order confirmation',
        // Don't leak internal error text (DB/SQL/paths) to clients in prod
        ...(process.env.NODE_ENV !== 'production'
          ? { details: error instanceof Error ? error.message : String(error) }
          : {}),
      },
      { status: 500 }
    )
  }
}
