import { NextRequest, NextResponse } from 'next/server'
import { debugLog, errorLog } from '@/lib/logger'

interface SkinAnalysisReportData {
  skinType: string
  confidence: number
  oilinessLevel: number
  hydrationLevel: number
  rednessLevel: number
  skinTone: string
  undertone: string
  textureScore: number
  poreVisibility: string
  evenness: number
  tZoneOiliness: number
  cheekHydration: number
  estimatedSkinAge: number
  concerns: string[]
  recommendations: string[]
  locale?: string
  analysisDate?: string
}

// Apple-style translations
const translations = {
  en: {
    title: 'Skin Analysis Report',
    subtitle: 'AI-Powered Skin Assessment',
    skinType: 'Skin Type',
    keyMetrics: 'Key Metrics',
    oiliness: 'Oiliness',
    hydration: 'Hydration',
    redness: 'Redness',
    detailedAnalysis: 'Detailed Analysis',
    skinTone: 'Skin Tone',
    undertone: 'Undertone',
    tZone: 'T-Zone',
    cheeks: 'Cheeks',
    additionalMetrics: 'Additional Metrics',
    smoothness: 'Smoothness',
    evenness: 'Evenness',
    pores: 'Pores',
    skinAge: 'Skin Age',
    accuracy: 'Accuracy',
    years: 'years',
    concerns: 'Concerns Detected',
    recommendations: 'Recommendations',
    generatedBy: 'Generated by GENOSYS AI',
    disclaimer: 'This analysis is for informational purposes only. Consult a dermatologist for medical advice.',
    date: 'Analysis Date',
    skinTypes: {
      dry: 'Dry',
      oily: 'Oily',
      combination: 'Combination',
      normal: 'Normal',
      sensitive: 'Sensitive'
    },
    skinTones: {
      fair: 'Fair',
      light: 'Light',
      medium: 'Medium',
      tan: 'Tan',
      deep: 'Deep'
    },
    undertones: {
      warm: 'Warm',
      cool: 'Cool',
      neutral: 'Neutral'
    },
    poreLabels: {
      minimal: 'Minimal',
      moderate: 'Moderate',
      visible: 'Visible'
    }
  },
  ar: {
    title: 'تقرير تحليل البشرة',
    subtitle: 'تقييم البشرة بالذكاء الاصطناعي',
    skinType: 'نوع البشرة',
    keyMetrics: 'المؤشرات الرئيسية',
    oiliness: 'الدهنية',
    hydration: 'الترطيب',
    redness: 'الاحمرار',
    detailedAnalysis: 'التحليل المفصل',
    skinTone: 'لون البشرة',
    undertone: 'الدرجة الأساسية',
    tZone: 'منطقة T',
    cheeks: 'الخدين',
    additionalMetrics: 'مقاييس إضافية',
    smoothness: 'نعومة البشرة',
    evenness: 'توحد اللون',
    pores: 'المسام',
    skinAge: 'عمر البشرة',
    accuracy: 'دقة التحليل',
    years: 'سنة',
    concerns: 'المخاوف المكتشفة',
    recommendations: 'التوصيات',
    generatedBy: 'تم إنشاؤه بواسطة GENOSYS AI',
    disclaimer: 'هذا التحليل لأغراض إعلامية فقط. استشر طبيب الجلدية للحصول على نصيحة طبية.',
    date: 'تاريخ التحليل',
    skinTypes: {
      dry: 'جافة',
      oily: 'دهنية',
      combination: 'مختلطة',
      normal: 'عادية',
      sensitive: 'حساسة'
    },
    skinTones: {
      fair: 'فاتح',
      light: 'خفيف',
      medium: 'متوسط',
      tan: 'سمراء',
      deep: 'داكن'
    },
    undertones: {
      warm: 'دافئ',
      cool: 'بارد',
      neutral: 'محايد'
    },
    poreLabels: {
      minimal: 'قليلة',
      moderate: 'معتدلة',
      visible: 'واضحة'
    }
  },
  ru: {
    title: 'Отчёт анализа кожи',
    subtitle: 'AI-оценка состояния кожи',
    skinType: 'Тип кожи',
    keyMetrics: 'Ключевые показатели',
    oiliness: 'Жирность',
    hydration: 'Увлажнение',
    redness: 'Покраснение',
    detailedAnalysis: 'Детальный анализ',
    skinTone: 'Тон кожи',
    undertone: 'Подтон',
    tZone: 'T-зона',
    cheeks: 'Щеки',
    additionalMetrics: 'Дополнительные показатели',
    smoothness: 'Гладкость',
    evenness: 'Однородность',
    pores: 'Поры',
    skinAge: 'Возраст кожи',
    accuracy: 'Точность',
    years: 'лет',
    concerns: 'Выявленные проблемы',
    recommendations: 'Рекомендации',
    generatedBy: 'Создано GENOSYS AI',
    disclaimer: 'Этот анализ носит информационный характер. Для медицинских рекомендаций обратитесь к дерматологу.',
    date: 'Дата анализа',
    skinTypes: {
      dry: 'Сухая',
      oily: 'Жирная',
      combination: 'Комбинированная',
      normal: 'Нормальная',
      sensitive: 'Чувствительная'
    },
    skinTones: {
      fair: 'Светлый',
      light: 'Легкий',
      medium: 'Средний',
      tan: 'Загорелый',
      deep: 'Темный'
    },
    undertones: {
      warm: 'Теплый',
      cool: 'Холодный',
      neutral: 'Нейтральный'
    },
    poreLabels: {
      minimal: 'Минимальные',
      moderate: 'Умеренные',
      visible: 'Заметные'
    }
  }
}

function generateAppleStylePDFHTML(data: SkinAnalysisReportData): string {
  const locale = (data.locale || 'en') as keyof typeof translations
  const t = translations[locale] || translations.en
  const isRTL = locale === 'ar'
  const dir = isRTL ? 'rtl' : 'ltr'
  const textAlign = isRTL ? 'right' : 'left'
  
  const analysisDate = data.analysisDate || new Date().toLocaleDateString(
    locale === 'ar' ? 'ar-AE' : locale === 'ru' ? 'ru-RU' : 'en-US',
    { year: 'numeric', month: 'long', day: 'numeric' }
  )
  
  const skinTypeLabel = t.skinTypes[data.skinType as keyof typeof t.skinTypes] || data.skinType
  const skinToneLabel = t.skinTones[data.skinTone as keyof typeof t.skinTones] || data.skinTone
  const undertoneLabel = t.undertones[data.undertone as keyof typeof t.undertones] || data.undertone
  const poreLabel = t.poreLabels[data.poreVisibility as keyof typeof t.poreLabels] || data.poreVisibility

  // Generate circular progress SVG
  const createCircularProgress = (value: number, color: string, size: number = 80) => {
    const radius = (size - 8) / 2
    const circumference = 2 * Math.PI * radius
    const strokeDashoffset = circumference - (value / 100) * circumference
    
    return `
      <svg width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" style="display: block;">
        <circle cx="${size/2}" cy="${size/2}" r="${radius}" fill="none" stroke="#f0f0f5" stroke-width="6"/>
        <circle cx="${size/2}" cy="${size/2}" r="${radius}" fill="none" stroke="${color}" stroke-width="6" 
          stroke-linecap="round" stroke-dasharray="${circumference}" stroke-dashoffset="${strokeDashoffset}"
          transform="rotate(-90 ${size/2} ${size/2})"/>
        <text x="${size/2}" y="${size/2}" text-anchor="middle" dominant-baseline="central" 
          style="font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Display', sans-serif; font-size: ${size/4}px; font-weight: 600; fill: #1d1d1f;">
          ${value}%
        </text>
      </svg>
    `
  }

  // Generate horizontal progress bar
  const createProgressBar = (value: number, color: string, label: string) => {
    return `
      <div style="margin-bottom: 16px;">
        <div style="display: flex; justify-content: space-between; margin-bottom: 6px;">
          <span style="font-size: 14px; color: #86868b;">${label}</span>
          <span style="font-size: 14px; font-weight: 600; color: #1d1d1f;">${value}%</span>
        </div>
        <div style="height: 8px; background: #f5f5f7; border-radius: 4px; overflow: hidden;">
          <div style="height: 100%; width: ${value}%; background: ${color}; border-radius: 4px;"></div>
        </div>
      </div>
    `
  }

  return `
    <!DOCTYPE html>
    <html dir="${dir}" lang="${locale}">
    <head>
      <meta charset="utf-8">
      <title>${t.title} - GENOSYS</title>
      <style>
        @page {
          size: A4;
          margin: 0;
        }
        
        * {
          box-sizing: border-box;
          margin: 0;
          padding: 0;
        }
        
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Display', 'SF Pro Text', 'Helvetica Neue', Arial, sans-serif;
          background: #ffffff;
          color: #1d1d1f;
          direction: ${dir};
          line-height: 1.5;
          -webkit-font-smoothing: antialiased;
        }
        
        .page {
          width: 210mm;
          min-height: 297mm;
          padding: 40px;
          margin: 0 auto;
          background: #ffffff;
        }
        
        .header {
          text-align: center;
          margin-bottom: 40px;
          padding-bottom: 30px;
          border-bottom: 1px solid #e8e8ed;
        }
        
        .logo {
          margin-bottom: 24px;
        }
        
        .logo img {
          height: 48px;
          width: auto;
        }
        
        .title {
          font-size: 32px;
          font-weight: 700;
          letter-spacing: -0.5px;
          color: #1d1d1f;
          margin-bottom: 8px;
        }
        
        .subtitle {
          font-size: 17px;
          color: #86868b;
          font-weight: 400;
        }
        
        .date-badge {
          display: inline-block;
          margin-top: 16px;
          padding: 8px 16px;
          background: #f5f5f7;
          border-radius: 20px;
          font-size: 13px;
          color: #6e6e73;
        }
        
        .skin-type-hero {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          border-radius: 20px;
          padding: 32px;
          text-align: center;
          margin-bottom: 32px;
          color: white;
        }
        
        .skin-type-label {
          font-size: 14px;
          text-transform: uppercase;
          letter-spacing: 1px;
          opacity: 0.9;
          margin-bottom: 8px;
        }
        
        .skin-type-value {
          font-size: 42px;
          font-weight: 700;
          letter-spacing: -1px;
          margin-bottom: 16px;
        }
        
        .accuracy-badge {
          display: inline-flex;
          align-items: center;
          gap: 8px;
          background: rgba(255,255,255,0.2);
          padding: 10px 20px;
          border-radius: 30px;
          font-size: 15px;
          font-weight: 500;
        }
        
        .accuracy-badge svg {
          width: 18px;
          height: 18px;
        }
        
        .section {
          margin-bottom: 32px;
        }
        
        .section-title {
          font-size: 22px;
          font-weight: 600;
          color: #1d1d1f;
          margin-bottom: 20px;
          text-align: ${textAlign};
          letter-spacing: -0.3px;
        }
        
        .metrics-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 24px;
          margin-bottom: 32px;
        }
        
        .metric-card {
          background: #f5f5f7;
          border-radius: 16px;
          padding: 24px;
          text-align: center;
        }
        
        .metric-label {
          font-size: 13px;
          color: #86868b;
          margin-top: 12px;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }
        
        .detail-grid {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 16px;
        }
        
        .detail-card {
          background: #f5f5f7;
          border-radius: 12px;
          padding: 20px;
        }
        
        .detail-label {
          font-size: 12px;
          color: #86868b;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          margin-bottom: 6px;
          text-align: ${textAlign};
        }
        
        .detail-value {
          font-size: 20px;
          font-weight: 600;
          color: #1d1d1f;
          text-align: ${textAlign};
        }
        
        .progress-section {
          background: #f5f5f7;
          border-radius: 16px;
          padding: 24px;
          margin-bottom: 24px;
        }
        
        .three-col-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 16px;
        }
        
        .stat-box {
          background: white;
          border-radius: 12px;
          padding: 16px;
          text-align: center;
        }
        
        .stat-label {
          font-size: 11px;
          color: #86868b;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          margin-bottom: 4px;
        }
        
        .stat-value {
          font-size: 18px;
          font-weight: 600;
          color: #1d1d1f;
        }
        
        .skin-age-section {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 32px;
          padding: 24px;
          background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
          border-radius: 16px;
          margin-bottom: 32px;
          color: white;
        }
        
        .skin-age-circle {
          width: 100px;
          height: 100px;
          background: rgba(255,255,255,0.2);
          border-radius: 50%;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
        }
        
        .skin-age-value {
          font-size: 36px;
          font-weight: 700;
        }
        
        .skin-age-unit {
          font-size: 12px;
          opacity: 0.9;
        }
        
        .skin-age-text {
          text-align: ${textAlign};
        }
        
        .skin-age-title {
          font-size: 20px;
          font-weight: 600;
          margin-bottom: 4px;
        }
        
        .skin-age-subtitle {
          font-size: 14px;
          opacity: 0.9;
        }
        
        .concerns-list, .recommendations-list {
          list-style: none;
          padding: 0;
        }
        
        .concerns-list li, .recommendations-list li {
          padding: 12px 16px;
          background: #f5f5f7;
          border-radius: 10px;
          margin-bottom: 8px;
          font-size: 15px;
          color: #1d1d1f;
          text-align: ${textAlign};
        }
        
        .concerns-list li::before {
          content: "•";
          color: #ff6b6b;
          font-weight: bold;
          margin-${isRTL ? 'left' : 'right'}: 10px;
        }
        
        .recommendations-list li::before {
          content: "✓";
          color: #51cf66;
          font-weight: bold;
          margin-${isRTL ? 'left' : 'right'}: 10px;
        }
        
        .footer {
          margin-top: 40px;
          padding-top: 24px;
          border-top: 1px solid #e8e8ed;
          text-align: center;
        }
        
        .footer-brand {
          font-size: 13px;
          color: #86868b;
          margin-bottom: 8px;
        }
        
        .footer-disclaimer {
          font-size: 11px;
          color: #aeaeb2;
          max-width: 400px;
          margin: 0 auto;
          line-height: 1.6;
        }
        
        @media print {
          body {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          .page {
            width: 100%;
            padding: 30px;
          }
        }
      </style>
    </head>
    <body>
      <div class="page">
        <!-- Header -->
        <div class="header">
          <div class="logo">
            <img src="https://genosys.ae/Logo/upLOGO.png" alt="GENOSYS" />
          </div>
          <h1 class="title">${t.title}</h1>
          <p class="subtitle">${t.subtitle}</p>
          <div class="date-badge">${t.date}: ${analysisDate}</div>
        </div>
        
        <!-- Skin Type Hero -->
        <div class="skin-type-hero">
          <div class="skin-type-label">${t.skinType}</div>
          <div class="skin-type-value">${skinTypeLabel}</div>
          <div class="accuracy-badge">
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41L9 16.17z"/>
            </svg>
            ${t.accuracy}: ${data.confidence}%
          </div>
        </div>
        
        <!-- Key Metrics -->
        <div class="section">
          <h2 class="section-title">${t.keyMetrics}</h2>
          <div class="metrics-grid">
            <div class="metric-card">
              ${createCircularProgress(data.oilinessLevel, '#f59e0b')}
              <div class="metric-label">${t.oiliness}</div>
            </div>
            <div class="metric-card">
              ${createCircularProgress(data.hydrationLevel, '#3b82f6')}
              <div class="metric-label">${t.hydration}</div>
            </div>
            <div class="metric-card">
              ${createCircularProgress(data.rednessLevel, '#ef4444')}
              <div class="metric-label">${t.redness}</div>
            </div>
          </div>
        </div>
        
        <!-- Skin Age -->
        <div class="skin-age-section">
          <div class="skin-age-circle">
            <div class="skin-age-value">${data.estimatedSkinAge}</div>
            <div class="skin-age-unit">${t.years}</div>
          </div>
          <div class="skin-age-text">
            <div class="skin-age-title">${t.skinAge}</div>
            <div class="skin-age-subtitle">${t.subtitle}</div>
          </div>
        </div>
        
        <!-- Detailed Analysis -->
        <div class="section">
          <h2 class="section-title">${t.detailedAnalysis}</h2>
          <div class="detail-grid">
            <div class="detail-card">
              <div class="detail-label">${t.skinTone}</div>
              <div class="detail-value">${skinToneLabel}</div>
            </div>
            <div class="detail-card">
              <div class="detail-label">${t.undertone}</div>
              <div class="detail-value">${undertoneLabel}</div>
            </div>
          </div>
        </div>
        
        <!-- Zone Analysis -->
        <div class="section">
          <div class="progress-section">
            ${createProgressBar(data.tZoneOiliness, '#f59e0b', t.tZone)}
            ${createProgressBar(data.cheekHydration, '#3b82f6', t.cheeks)}
          </div>
        </div>
        
        <!-- Additional Metrics -->
        <div class="section">
          <h2 class="section-title">${t.additionalMetrics}</h2>
          <div class="three-col-grid">
            <div class="stat-box">
              <div class="stat-label">${t.smoothness}</div>
              <div class="stat-value">${data.textureScore}%</div>
            </div>
            <div class="stat-box">
              <div class="stat-label">${t.evenness}</div>
              <div class="stat-value">${data.evenness}%</div>
            </div>
            <div class="stat-box">
              <div class="stat-label">${t.pores}</div>
              <div class="stat-value">${poreLabel}</div>
            </div>
          </div>
        </div>
        
        <!-- Concerns -->
        ${data.concerns && data.concerns.length > 0 ? `
          <div class="section">
            <h2 class="section-title">${t.concerns}</h2>
            <ul class="concerns-list">
              ${data.concerns.map(c => `<li>${c}</li>`).join('')}
            </ul>
          </div>
        ` : ''}
        
        <!-- Recommendations -->
        ${data.recommendations && data.recommendations.length > 0 ? `
          <div class="section">
            <h2 class="section-title">${t.recommendations}</h2>
            <ul class="recommendations-list">
              ${data.recommendations.map(r => `<li>${r}</li>`).join('')}
            </ul>
          </div>
        ` : ''}
        
        <!-- Footer -->
        <div class="footer">
          <div class="footer-brand">${t.generatedBy}</div>
          <div class="footer-disclaimer">${t.disclaimer}</div>
        </div>
      </div>
    </body>
    </html>
  `
}

export async function POST(request: NextRequest) {
  try {
    const data: SkinAnalysisReportData = await request.json()
    
    debugLog('Generating skin analysis PDF report', { skinType: data.skinType, locale: data.locale })
    
    // Generate the HTML
    const html = generateAppleStylePDFHTML(data)
    
    // Return HTML for client-side PDF generation
    return NextResponse.json({ 
      success: true, 
      html,
      filename: `skin-analysis-report-${new Date().toISOString().split('T')[0]}.pdf`
    })

  } catch (error) {
    errorLog('Error generating skin analysis report:', error)
    return NextResponse.json(
      { success: false, message: 'Failed to generate report' },
      { status: 500 }
    )
  }
}

// Also support GET for direct PDF viewing
export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams
  
  // Parse data from query params (for sharing links)
  const data: SkinAnalysisReportData = {
    skinType: searchParams.get('skinType') || 'normal',
    confidence: parseInt(searchParams.get('confidence') || '0'),
    oilinessLevel: parseInt(searchParams.get('oiliness') || '0'),
    hydrationLevel: parseInt(searchParams.get('hydration') || '0'),
    rednessLevel: parseInt(searchParams.get('redness') || '0'),
    skinTone: searchParams.get('skinTone') || 'medium',
    undertone: searchParams.get('undertone') || 'neutral',
    textureScore: parseInt(searchParams.get('texture') || '0'),
    poreVisibility: searchParams.get('pores') || 'moderate',
    evenness: parseInt(searchParams.get('evenness') || '0'),
    tZoneOiliness: parseInt(searchParams.get('tZone') || '0'),
    cheekHydration: parseInt(searchParams.get('cheeks') || '0'),
    estimatedSkinAge: parseInt(searchParams.get('skinAge') || '0'),
    concerns: [],
    recommendations: [],
    locale: searchParams.get('locale') || 'en'
  }
  
  const html = generateAppleStylePDFHTML(data)
  
  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
    },
  })
}
