/**
 * Render a concern protocol from HTML source to the PDF the site serves.
 *
 * The eight protocol PDFs in `public/documents/PPT/` were static files with no source
 * anywhere in the repo, which is how the hair-loss one drifted into promising
 * month-by-month regrowth and naming ingredients that are not in the products. Anything
 * regenerated by this script has a reviewable source under `scripts/protocols/`.
 *
 * Usage:
 *   npx tsx scripts/build-protocol-pdf.ts hair-loss
 *   npx tsx scripts/build-protocol-pdf.ts hair-loss --open
 *
 * The logo is inlined as a data URI so the rendered page needs no server.
 */

import { readFileSync, statSync } from 'fs'
import { resolve } from 'path'
import { execFileSync } from 'child_process'
import { chromium } from 'playwright'
import { renderProtocol } from './protocols/protocolTemplate'
import { PROTOCOLS as DATA_PROTOCOLS } from './protocols/protocolContent'

/** Hair loss is hand-written HTML; the other seven are data through a shared template. */
const HTML_PROTOCOLS: Record<string, { source: string; out: string }> = {
  'hair-loss': {
    source: 'scripts/protocols/protocol-hair-loss.html',
    out: 'public/documents/PPT/Protocol_Hair_Loss.pdf',
  },
}

const LOGO = 'public/images/genosys-logo-transparent.png'

function knownSlugs(): string[] {
  return [...Object.keys(HTML_PROTOCOLS), ...DATA_PROTOCOLS.map(p => p.slug)]
}

function resolveHtml(slug: string, logoDataUri: string): { html: string; out: string } {
  const fromFile = HTML_PROTOCOLS[slug]
  if (fromFile) {
    return {
      html: readFileSync(resolve(fromFile.source), 'utf8').replace('LOGO_SRC', logoDataUri),
      out: fromFile.out,
    }
  }
  const data = DATA_PROTOCOLS.find(p => p.slug === slug)
  if (!data) {
    console.error(`Unknown protocol "${slug}". Known: ${knownSlugs().join(', ')}`)
    process.exit(1)
  }
  return { html: renderProtocol(data, logoDataUri), out: data.out }
}

async function main() {
  const requested = process.argv[2]
  const slugs = requested === 'all' ? knownSlugs() : [requested]
  const logoDataUri = `data:image/png;base64,${readFileSync(resolve(LOGO)).toString('base64')}`

  const browser = await chromium.launch()
  try {
    for (const slug of slugs) {
      const { html, out } = resolveHtml(slug, logoDataUri)
      const page = await browser.newPage()
      await page.setContent(html, { waitUntil: 'load' })
      await page.pdf({
        path: resolve(out),
        format: 'A4',
        printBackground: true,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate:
          '<div style="width:100%;font-size:7.5pt;color:#8a8a8a;'
          + 'font-family:Helvetica,Arial,sans-serif;text-align:center;padding-bottom:6mm">'
          + '<span class="pageNumber"></span> / <span class="totalPages"></span></div>',
        margin: { top: '16mm', right: '15mm', bottom: '18mm', left: '15mm' },
      })
      await page.close()
      const kb = Math.round(statSync(resolve(out)).size / 1024)
      console.log(`${slug.padEnd(12)} → ${out}  (${kb} KB)`)
    }
  } finally {
    await browser.close()
  }

  if (process.argv.includes('--open') && requested !== 'all') {
    const { out } = resolveHtml(requested, logoDataUri)
    execFileSync('open', [resolve(out)])
  }
}

main().catch(e => {
  console.error(e)
  process.exit(1)
})
