#!/usr/bin/env node

/**
 * Deployment setup script for Vercel
 * This script handles database initialization and setup
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// Load environment variables from .env.local if it exists
const envLocalPath = path.join(process.cwd(), '.env.local');
if (fs.existsSync(envLocalPath)) {
  const envContent = fs.readFileSync(envLocalPath, 'utf8');
  envContent.split('\n').forEach(line => {
    const trimmedLine = line.trim();
    if (trimmedLine && !trimmedLine.startsWith('#')) {
      const [key, ...valueParts] = trimmedLine.split('=');
      if (key && valueParts.length > 0) {
        const value = valueParts.join('=').trim().replace(/^["']|["']$/g, '');
        if (!process.env[key]) {
          process.env[key] = value;
        }
      }
    }
  });
}

console.log('🚀 Starting deployment setup...');

try {
  // Ensure the database directory exists
  const dbDir = path.join(process.cwd(), 'prisma');
  if (!fs.existsSync(dbDir)) {
    fs.mkdirSync(dbDir, { recursive: true });
  }

  // Ensure DATABASE_URL is provided
  if (!process.env.DATABASE_URL) {
    console.error('❌ DATABASE_URL environment variable is required');
    console.error('   Please set DATABASE_URL in your environment or .env.local file');
    process.exit(1);
  }

  // Generate Prisma client (skip if already generated by postinstall)
  console.log('🔧 Verifying Prisma client...');
  try {
    // Only generate if not already generated (postinstall already did it)
    // But verify it exists and has the PasswordResetToken model
    const { PrismaClient } = require('@prisma/client');
    const testClient = new PrismaClient();
    
    // Check if PasswordResetToken model exists
    if (!testClient.passwordResetToken) {
      console.warn('⚠️  PasswordResetToken model not found, regenerating Prisma client...');
      execSync('npx prisma generate', { stdio: 'inherit' });
      
      // Re-require after regeneration
      delete require.cache[require.resolve('@prisma/client')];
      const { PrismaClient: NewPrismaClient } = require('@prisma/client');
      const newTestClient = new NewPrismaClient();
      
      if (!newTestClient.passwordResetToken) {
        console.error('❌ ERROR: PasswordResetToken model still not found after regeneration!');
        console.error('   This will cause password reset feature to fail.');
        console.error('   Please ensure prisma/schema.prisma includes PasswordResetToken model.');
        console.error('   Available models:', Object.keys(newTestClient).filter(k => !k.startsWith('$') && !k.startsWith('_')).join(', '));
        newTestClient.$disconnect();
        throw new Error('PasswordResetToken model not found in Prisma client');
      } else {
        console.log('✅ PasswordResetToken model verified after regeneration');
      }
      newTestClient.$disconnect();
    } else {
      console.log('✅ PasswordResetToken model verified in Prisma client');
    }
    testClient.$disconnect();
  } catch (verifyError) {
    // If verification fails, try to regenerate
    console.warn('⚠️  Prisma client verification failed, attempting regeneration...');
    try {
      execSync('npx prisma generate', { stdio: 'inherit' });
      console.log('✅ Prisma client regenerated successfully');
    } catch (generateError) {
      console.error('❌ Failed to generate Prisma client:', generateError.message);
      throw generateError;
    }
  }

  // Attempt database push to ensure schema is synced
  // This will fail silently in some serverless environments, which is OK
  // Manual migration can be run via: npx prisma db push
  console.log('📋 Attempting to sync database schema...');
  try {
    execSync('npx prisma db push --skip-generate --accept-data-loss', { 
      stdio: 'pipe',
      timeout: 30000 // 30 second timeout
    });
    console.log('✅ Database schema synced successfully');
  } catch (dbPushError) {
    // In serverless environments, db push might not work
    // This is expected and OK - migration can be run manually
    console.log('⏭️  Database push skipped (serverless environment or manual migration required)');
    console.log('   To sync database manually, run: npx prisma db push');
    console.log('   Or use the migration script: node scripts/migrate-password-reset-table.js');
  }

  console.log('✅ Deployment setup completed successfully!');
} catch (error) {
  console.error('❌ Deployment setup failed:', error.message);
  process.exit(1);
}
