import { PrismaClient } from '@prisma/client'
import fs from 'fs'
import path from 'path'

const prisma = new PrismaClient()

/**
 * Translate products from database to Russian
 * This script will:
 * 1. Fetch all products from the database
 * 2. Generate Russian translations for each product
 * 3. Create/update productTranslationsRu.ts file
 */

interface ProductTranslation {
  description?: string
  productDetails?: string
  keyFeatures?: string | null
  benefits?: string
  ingredients?: string | null
  howToUse?: string
  directions?: string
}

// Helper function to translate text (placeholder - you can integrate with translation API)
async function translateToRussian(text: string): Promise<string> {
  // TODO: Integrate with translation API (Google Translate, DeepL, etc.)
  // For now, return placeholder
  // In production, you would call a translation service here
  return `[RUSSIAN TRANSLATION OF: ${text.substring(0, 50)}...]`
}

// Helper function to translate JSON string
async function translateJSONString(jsonStr: string | null): Promise<string | null> {
  if (!jsonStr) return null
  
  try {
    const parsed = JSON.parse(jsonStr)
    
    if (Array.isArray(parsed)) {
      // Translate array items
      const translated = await Promise.all(
        parsed.map(async (item) => {
          if (typeof item === 'string') {
            return await translateToRussian(item)
          } else if (typeof item === 'object' && item !== null) {
            const translatedObj: Record<string, string> = {}
            for (const [key, value] of Object.entries(item)) {
              if (typeof value === 'string') {
                translatedObj[key] = await translateToRussian(value)
              } else {
                translatedObj[key] = value as string
              }
            }
            return translatedObj
          }
          return item
        })
      )
      return JSON.stringify(translated, null, 2)
    } else if (typeof parsed === 'object' && parsed !== null) {
      // Translate object values
      const translated: Record<string, string> = {}
      for (const [key, value] of Object.entries(parsed)) {
        if (typeof value === 'string') {
          translated[key] = await translateToRussian(value)
        } else {
          translated[key] = value as string
        }
      }
      return JSON.stringify(translated, null, 2)
    }
    
    return jsonStr
  } catch (e) {
    console.error('Error parsing JSON:', e)
    return jsonStr
  }
}

async function translateProduct(product: any): Promise<ProductTranslation> {
  const translation: ProductTranslation = {}
  
  if (product.description) {
    translation.description = await translateToRussian(product.description)
  }
  
  if (product.productDetails) {
    const translated = await translateJSONString(product.productDetails)
    if (translated) {
      translation.productDetails = translated
    }
  }
  
  if (product.keyFeatures) {
    translation.keyFeatures = await translateJSONString(product.keyFeatures)
  }
  
  if (product.benefits) {
    const translated = await translateJSONString(product.benefits)
    if (translated) {
      translation.benefits = translated
    }
  }
  
  if (product.ingredients) {
    translation.ingredients = await translateJSONString(product.ingredients)
  }
  
  if (product.howToUse) {
    const translated = await translateJSONString(product.howToUse)
    if (translated) {
      translation.howToUse = translated
    }
  }
  
  if (product.directions) {
    translation.directions = await translateToRussian(product.directions)
  }
  
  return translation
}

async function main() {
  console.log('Fetching all products from database...')
  
  try {
    const products = await prisma.product.findMany({
      where: {
        isHidden: false
      },
      orderBy: {
        id: 'asc'
      }
    })
    
    console.log(`Found ${products.length} products to translate`)
    
    const translations: Record<string, ProductTranslation> = {}
    
    // Translate each product
    for (const product of products) {
      const productId = product.productNumber || product.id
      console.log(`Translating product ${productId}: ${product.name}`)
      
      try {
        translations[productId] = await translateProduct(product)
        console.log(`✓ Translated product ${productId}`)
      } catch (error) {
        console.error(`✗ Error translating product ${productId}:`, error)
      }
    }
    
    // Generate TypeScript file
    const fileContent = `/**
 * Russian translations for products
 * Auto-generated by translate-products-to-russian.ts
 * 
 * Structure:
 * - description: Russian description
 * - productDetails: Russian product details (JSON string)
 * - keyFeatures: Russian key features (JSON array string)
 * - benefits: Russian benefits (JSON array string)
 * - ingredients: Russian ingredients (JSON array string)
 * - howToUse: Russian usage instructions
 * - directions: Russian directions
 */

export interface ProductTranslation {
  description?: string
  productDetails?: string
  keyFeatures?: string | null
  benefits?: string
  ingredients?: string | null
  howToUse?: string
  directions?: string
}

export const productTranslationsRu: Record<string, ProductTranslation> = ${JSON.stringify(translations, null, 2)}

/**
 * Get Russian translation for a product field
 * @param productId - Product ID
 * @param field - Field name to translate
 * @returns Russian translation or null if not available
 */
export function getProductTranslationRu(
  productId: string,
  field: keyof ProductTranslation
): string | null {
  const translation = productTranslationsRu[productId]
  return translation?.[field] || null
}

/**
 * Get all Russian translations for a product
 * @param productId - Product ID
 * @returns ProductTranslation object or null
 */
export function getProductTranslationsRu(productId: string): ProductTranslation | null {
  return productTranslationsRu[productId] || null
}
`
    
    // Write to file
    const filePath = path.join(process.cwd(), 'data', 'productTranslationsRu.ts')
    fs.writeFileSync(filePath, fileContent, 'utf-8')
    
    console.log(`\n✓ Successfully generated ${filePath}`)
    console.log(`✓ Translated ${Object.keys(translations).length} products`)
    
  } catch (error) {
    console.error('Error:', error)
    process.exit(1)
  } finally {
    await prisma.$disconnect()
  }
}

main()



