'use client'

import Link from 'next/link'
import { ArrowLeft, HelpCircle, ChevronDown, ChevronUp } from 'lucide-react'
import BreadcrumbSchema from '@/components/BreadcrumbSchema'
import { useState } from 'react'

const faqs = [
  {
    question: 'What is GENOSYS?',
    answer: 'GENOSYS is a professional Korean dermacosmetics brand distributed by GENOSYS Middle East FZ-LLC in the UAE. We offer premium skincare products and microneedling devices for professional use. Our products are certified by Dubai Municipality and are suitable for licensed practitioners and professional beauty clinics.',
  },
  {
    question: 'Do you ship to all UAE emirates?',
    answer: 'Yes, we ship to all 7 UAE emirates: Dubai, Abu Dhabi, Sharjah, Ajman, Ras Al Khaimah, Fujairah, and Umm Al Quwain. Shipping costs vary by emirate, and orders over 1000 AED qualify for free shipping. Delivery typically takes 1-3 business days depending on your location.',
  },
  {
    question: 'Are GENOSYS products suitable for home use?',
    answer: 'GENOSYS offers both professional-grade products for licensed practitioners and homecare products for personal use. Please check product descriptions for usage guidelines. Some products are specifically designed for professional treatments and should only be used by trained practitioners.',
  },
  {
    question: 'What payment methods do you accept?',
    answer: 'We accept Cash on Delivery (COD) and payment via Stripe checkout online (Apple Pay/Credit and Debit cards) for all orders. The link for payment is generated by our support team once the order is placed.',
  },
  {
    question: 'How long does shipping take?',
    answer: 'Shipping times vary by emirate: Dubai, Sharjah (1-2 hours by Careem), Abu Dhabi and other emirates (48 hours via Quiqup). We process all orders on the same day. Free shipping is available for orders over 1000 AED.',
  },
  {
    question: 'Can I return or exchange products?',
    answer: 'We accept returns and exchanges within 7 days of delivery for unopened products in their original packaging. Please contact our support team at sales@genosys.ae or WhatsApp +971 58 548 76 65 to initiate a return or exchange.',
  },
  {
    question: 'Do you offer professional training?',
    answer: 'Yes, we offer comprehensive professional skincare training for licensed practitioners. Our training covers microneedling techniques, product application methods, and treatment protocols. Training is available for registered users. Contact us for more information about training schedules and requirements.',
  },
  {
    question: 'Are GENOSYS products certified?',
    answer: 'Yes, all GENOSYS products are certified by Dubai Municipality and comply with UAE regulations. We are the official distributor of DTS MG Co., Ltd. Korea in the UAE, ensuring authentic and certified products.',
  },
  {
    question: 'How do I track my order?',
    answer: 'Once your order is confirmed, you will receive an order confirmation email with your order number. Our support team will contact you via phone, email, or WhatsApp to confirm delivery details. You can also contact us directly with your order number for updates. Dubai, Sharjah orders are tracked via Careem delivery. Abu Dhabi and other emirates are tracked via Quiqup delivery.',
  },
  {
    question: 'What is your return policy?',
    answer: 'We accept returns within 7 days of delivery for unopened products. Products must be in their original packaging and unused. Refunds will be processed within 5-7 business days after we receive the returned items. Shipping costs for returns are the responsibility of the customer unless the product is defective.',
  },
  {
    question: 'Do you offer bulk discounts?',
    answer: 'Yes, we offer discounts for bulk orders and professional accounts. Registered users may be eligible for special pricing based on their account type. Contact our sales team at sales@genosys.ae to discuss bulk order pricing and professional account benefits.',
  },
  {
    question: 'How do I become a registered user?',
    answer: 'You can register for an account on our website by clicking the "Login" button and selecting "Register". Registration is free and gives you access to product pricing, professional training materials, and exclusive member benefits.',
  },
  {
    question: 'Are your products suitable for sensitive skin?',
    answer: 'Many GENOSYS products are formulated for sensitive skin, but we recommend consulting with a dermatologist or skincare professional before use. Product descriptions include information about skin types and target concerns. Always perform a patch test before first use.',
  },
  {
    question: 'Do you ship internationally?',
    answer: 'Currently, we only ship within the United Arab Emirates.',
  },
  {
    question: 'How can I contact customer support?',
    answer: 'You can reach our customer support team via email at sales@genosys.ae, WhatsApp at +971 58 548 76 65, or through our contact page. Our support team is available Monday to Friday, 9 AM to 6 PM UAE time.',
  },
]

export default function FAQClient() {
  const [openIndex, setOpenIndex] = useState<number | null>(null)

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index)
  }

  return (
    <div className="bg-gradient-to-b from-gray-50 to-white min-h-screen">
      <BreadcrumbSchema 
        items={[
          { name: 'Home', url: '/' },
          { name: 'FAQ', url: '/faq' }
        ]}
      />
      
      {/* FAQPage Schema */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": faqs.map(faq => ({
              "@type": "Question",
              "name": faq.question,
              "acceptedAnswer": {
                "@type": "Answer",
                "text": faq.answer
              }
            }))
          }, null, 2)
        }}
      />
      
      <div className="container mx-auto px-4 py-8 md:py-16">
        <div className="max-w-4xl mx-auto">
          {/* Navigation Breadcrumb */}
          <nav className="flex flex-col gap-2 text-sm md:text-base text-gray-600 mb-8" aria-label="Breadcrumb">
            {/* Mobile Breadcrumb */}
            <div className="md:hidden flex items-center gap-2">
              <Link 
                href="/"
                className="hover:text-primary-600 transition-colors flex items-center"
              >
                Home
              </Link>
              <span className="flex items-center">/</span>
              <span className="text-gray-900 font-medium flex items-center">
                FAQ
              </span>
            </div>
            
            {/* Mobile Back Button */}
            <Link 
              href="/"
              className="md:hidden flex items-center gap-2 text-primary-600 hover:text-primary-700 transition-colors"
            >
              <ArrowLeft className="h-4 w-4" />
              <span className="font-medium">Back to Home</span>
            </Link>
            
            {/* Desktop Breadcrumb */}
            <div className="hidden md:flex items-center gap-2">
              <Link 
                href="/"
                className="hover:text-primary-600 transition-colors flex items-center"
              >
                Home
              </Link>
              <span className="flex items-center">/</span>
              <span className="text-gray-900 font-medium flex items-center">
                FAQ
              </span>
            </div>
          </nav>

          {/* Page Header */}
          <div className="text-center mb-12">
            <div className="inline-flex items-center justify-center w-16 h-16 bg-primary-100 rounded-full mb-6">
              <HelpCircle className="h-8 w-8 text-primary-600" />
            </div>
            <h1 className="text-4xl md:text-5xl font-bold text-gray-800 mb-4">
              Frequently Asked Questions
            </h1>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              Find answers to common questions about GENOSYS products, shipping, orders, and professional training.
            </p>
          </div>

          {/* FAQ Accordion */}
          <div className="space-y-4 mb-12">
            {faqs.map((faq, index) => {
              const isOpen = openIndex === index
              return (
                <div 
                  key={index} 
                  className="bg-white border border-gray-200 rounded-xl shadow-sm hover:shadow-md transition-all duration-200 overflow-hidden"
                >
                  <button
                    onClick={() => toggleFAQ(index)}
                    className="w-full px-6 py-5 text-left flex items-center justify-between hover:bg-gray-50 transition-colors group"
                    aria-expanded={isOpen}
                  >
                    <div className="flex items-start gap-4 flex-1">
                      <div className={`flex-shrink-0 w-8 h-8 rounded-lg flex items-center justify-center transition-colors ${
                        isOpen ? 'bg-primary-600' : 'bg-gray-100 group-hover:bg-gray-200'
                      }`}>
                        <span className={`text-sm font-bold ${
                          isOpen ? 'text-white' : 'text-gray-600'
                        }`}>
                          {index + 1}
                        </span>
                      </div>
                      <h2 className="text-lg md:text-xl font-semibold text-gray-800 pr-4">
                        {faq.question}
                      </h2>
                    </div>
                    <div className="flex-shrink-0">
                      {isOpen ? (
                        <ChevronUp className="h-5 w-5 text-primary-600 transition-transform" />
                      ) : (
                        <ChevronDown className="h-5 w-5 text-gray-400 group-hover:text-primary-600 transition-transform" />
                      )}
                    </div>
                  </button>
                  <div 
                    className={`overflow-hidden transition-all duration-300 ease-in-out ${
                      isOpen ? 'max-h-[1000px] opacity-100' : 'max-h-0 opacity-0'
                    }`}
                  >
                    <div className="px-6 pb-6 pl-[72px]">
                      <div className="border-l-2 border-primary-200 pl-6">
                        <p className="text-gray-600 leading-relaxed">
                          {faq.answer}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              )
            })}
          </div>

          {/* Contact CTA */}
          <div className="mt-12 p-8 bg-gradient-to-r from-primary-50 to-red-50 rounded-xl border border-primary-100 shadow-sm">
            <div className="text-center">
              <h3 className="text-2xl font-bold text-gray-800 mb-3">
                Still have questions?
              </h3>
              <p className="text-gray-600 mb-6 max-w-xl mx-auto">
                Can't find the answer you're looking for? Our support team is here to help.
              </p>
              <div className="flex flex-col sm:flex-row gap-3 justify-center">
                <Link
                  href="/contact-genosys-uae"
                  className="bg-primary-600 text-white px-8 py-3 rounded-lg font-semibold hover:bg-primary-700 transition-colors text-center shadow-md hover:shadow-lg"
                >
                  Contact Us
                </Link>
                <a
                  href="https://wa.me/971585487665?text=Hi, I have a question about GENOSYS products."
                  target="_blank"
                  rel="noopener noreferrer"
                  className="bg-green-600 text-white px-8 py-3 rounded-lg font-semibold hover:bg-green-700 transition-colors text-center shadow-md hover:shadow-lg"
                >
                  WhatsApp Us
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

